/**
 * AWS Auto Scaling Group -> Azure VMSS / GCP MIG translation.
 * Azure emits 1 resource (Virtual Machine Scale Set).
 * GCP emits 3 resources (Instance Template + Region IGM + Autoscaler).
 *
 * @module compound/asg-mapping
 * @generated by code-generator (TASK-TRANS-004)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
  findSiblingByType,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'desired_capacity',
  'health_check_type',
  'launch_template',
  'max_size',
  'min_size',
  'name',
  'tags',
  'vpc_zone_identifier',
];

// Re-use the instance type map for launch template resolution
const INSTANCE_TYPE_MAP: ReadonlyMap<string, { azure: string; gcp: string }> =
  new Map([
    ['t3.micro', { azure: 'Standard_B1s', gcp: 'e2-micro' }],
    ['t3.small', { azure: 'Standard_B1ms', gcp: 'e2-small' }],
    ['t3.medium', { azure: 'Standard_B2s', gcp: 'e2-medium' }],
    ['t3.large', { azure: 'Standard_B2ms', gcp: 'e2-standard-2' }],
    ['m5.large', { azure: 'Standard_D2s_v5', gcp: 'n2-standard-2' }],
    ['m5.xlarge', { azure: 'Standard_D4s_v5', gcp: 'n2-standard-4' }],
    ['c5.large', { azure: 'Standard_F2s_v2', gcp: 'c2-standard-4' }],
    ['r5.large', { azure: 'Standard_E2s_v5', gcp: 'n2-highmem-2' }],
  ]);

/**
 * Resolves instance type from a sibling launch template resource.
 */
function resolveLaunchTemplateInstanceType(
  ctx: TranslationContext,
): string | undefined {
  const sibling = findSiblingByType(ctx, 'aws_launch_template');
  if (!sibling) return undefined;

  const ltResource = ctx.siblingResources.find((r) => r.id === sibling.id);
  if (!ltResource) return undefined;

  const ltAttrs = ltResource.attributes as Record<string, unknown>;
  return ltAttrs['instance_type'] as string | undefined;
}

// ---------------------------------------------------------------------------
// Azure translation (1 resource: VMSS)
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'compound/asg', 'compound');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const desiredCapacity = (attrs['desired_capacity'] as number | undefined) ?? 1;
  const minSize = (attrs['min_size'] as number | undefined) ?? 1;
  const maxSize = (attrs['max_size'] as number | undefined) ?? 3;

  // Resolve instance type from launch template
  const instanceType = resolveLaunchTemplateInstanceType(ctx) ?? 't3.micro';
  const sizeEntry = INSTANCE_TYPE_MAP.get(instanceType);
  const sku = sizeEntry?.azure ?? 'Standard_B1s';

  const vmssAttrs: Record<string, unknown> = {
    admin_username: 'adminuser',
    instances: desiredCapacity,
    location: '${azurerm_resource_group.main.location}',
    name: sourceName,
    network_interface: {
      ip_configuration: {
        name: 'internal',
        primary: true,
        subnet_id: '${azurerm_subnet.main.id}',
      },
      name: `${sourceName}-nic`,
      primary: true,
    },
    os_disk: {
      caching: 'ReadWrite',
      storage_account_type: 'StandardSSD_LRS',
    },
    resource_group_name: '${azurerm_resource_group.main.name}',
    sku: sku,
    source_image_reference: {
      offer: 'UbuntuServer',
      publisher: 'Canonical',
      sku: '18.04-LTS',
      version: 'latest',
    },
  };

  // Autoscaling profile
  vmssAttrs['automatic_instance_repair'] = { enabled: true };

  if (tags) vmssAttrs['tags'] = transformTags('azure', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_linux_virtual_machine_scale_set',
      targetName: sourceName,
      attributes: vmssAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'COMPOUND_EXPANSION',
      `1 aws_autoscaling_group -> 1 azure resources`,
    ),
    createFinding(
      resource.id,
      'info',
      'ASG_SCALING_ADVISORY',
      `Azure VMSS autoscale requires a separate azurerm_monitor_autoscale_setting for min=${minSize}/max=${maxSize} policy`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation (3 resources: Template + IGM + Autoscaler)
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'compound/asg', 'compound');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const desiredCapacity = (attrs['desired_capacity'] as number | undefined) ?? 1;
  const minSize = (attrs['min_size'] as number | undefined) ?? 1;
  const maxSize = (attrs['max_size'] as number | undefined) ?? 3;

  // Resolve instance type from launch template
  const instanceType = resolveLaunchTemplateInstanceType(ctx) ?? 't3.micro';
  const sizeEntry = INSTANCE_TYPE_MAP.get(instanceType);
  const machineType = sizeEntry?.gcp ?? 'e2-micro';

  // 1. Instance Template
  const tplAttrs: Record<string, unknown> = {
    disk: {
      auto_delete: true,
      boot: true,
      source_image: 'ubuntu-os-cloud/ubuntu-1804-lts',
    },
    machine_type: machineType,
    name: `${sourceName}-tpl`,
    network_interface: {
      network: '${google_compute_network.main.id}',
      subnetwork: '${google_compute_subnetwork.main.id}',
    },
  };
  if (tags) tplAttrs['labels'] = transformTags('gcp', tags);

  // 2. Region Instance Group Manager
  const igmAttrs: Record<string, unknown> = {
    base_instance_name: sourceName,
    name: sourceName,
    region: '${var.region}',
    target_size: desiredCapacity,
    version: {
      instance_template: `\${google_compute_instance_template.${sourceName}_tpl.id}`,
    },
  };

  // 3. Region Autoscaler
  const asAttrs: Record<string, unknown> = {
    autoscaling_policy: {
      max_replicas: maxSize,
      min_replicas: minSize,
    },
    name: `${sourceName}-as`,
    region: '${var.region}',
    target: `\${google_compute_region_instance_group_manager.${sourceName}.id}`,
  };

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_instance_template',
      targetName: `${sourceName}_tpl`,
      attributes: tplAttrs,
      sourceId: resource.id,
      traceability,
    },
    {
      targetType: 'google_compute_region_instance_group_manager',
      targetName: sourceName,
      attributes: igmAttrs,
      sourceId: resource.id,
      traceability,
    },
    {
      targetType: 'google_compute_region_autoscaler',
      targetName: `${sourceName}_as`,
      attributes: asAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'COMPOUND_EXPANSION',
      `1 aws_autoscaling_group -> 3 gcp resources`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_autoscaling_group resource to Azure or GCP equivalents.
 */
export function translateAsg(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
