/**
 * Pure helper functions for AWS Load Balancer sibling resolution and protocol mapping.
 *
 * Resolves listener, target group, and WAF configuration from sibling IR resources,
 * and maps AWS protocols to Azure / GCP equivalents.
 *
 * @module compound/lb-helpers
 * @generated by code-generator (TASK-NET-004)
 */

import type { TranslationContext } from '../mapping-engine.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ListenerConfig {
  readonly port: number;
  readonly protocol: string;
  readonly sslCertificateArn?: string;
  readonly sslPolicy?: string;
}

export interface TargetGroupConfig {
  readonly port: number;
  readonly protocol: string;
  readonly healthCheckPath?: string;
  readonly healthCheckProtocol?: string;
  readonly healthCheckPort?: number;
}

export interface ProtocolMapResult {
  readonly protocol: string;
  readonly unknownProtocol: boolean;
}

// ---------------------------------------------------------------------------
// Finding code constants
// ---------------------------------------------------------------------------

export const LB_SSL_CERTIFICATE = 'LB_SSL_CERTIFICATE';
export const LB_WAF_ADVISORY = 'LB_WAF_ADVISORY';
export const LB_UNKNOWN_PROTOCOL = 'LB_UNKNOWN_PROTOCOL';

// ---------------------------------------------------------------------------
// Azure protocol map
// ---------------------------------------------------------------------------

const AZURE_PROTOCOL_MAP: ReadonlyMap<string, string> = new Map([
  ['HTTP', 'Http'],
  ['HTTPS', 'Https'],
  ['TCP', 'Tcp'],
  ['TLS', 'Tcp'],
  ['UDP', 'Udp'],
]);

// ---------------------------------------------------------------------------
// GCP protocol maps (ALB vs NLB)
// ---------------------------------------------------------------------------

const GCP_ALB_PROTOCOL_MAP: ReadonlyMap<string, string> = new Map([
  ['HTTP', 'HTTP'],
  ['HTTPS', 'HTTPS'],
]);

const GCP_NLB_PROTOCOL_MAP: ReadonlyMap<string, string> = new Map([
  ['TCP', 'TCP'],
  ['TLS', 'SSL'],
  ['UDP', 'UDP'],
]);

// ---------------------------------------------------------------------------
// Sibling resolution helpers
// ---------------------------------------------------------------------------

/**
 * Scans siblingResources for an aws_lb_listener and extracts listener config.
 * Falls back to port 80 and the given defaultProtocol (default 'HTTP') when no sibling is found.
 */
export function resolveListenerConfig(
  ctx: TranslationContext,
  defaultProtocol = 'HTTP',
): ListenerConfig {
  const listener = ctx.siblingResources.find(
    (r) => r.sourceType === 'aws_lb_listener',
  );
  if (!listener) {
    return { port: 80, protocol: defaultProtocol };
  }

  const attrs = listener.attributes as Record<string, unknown>;
  const port = typeof attrs['port'] === 'number' ? attrs['port'] : 80;
  const protocol =
    typeof attrs['protocol'] === 'string'
      ? attrs['protocol'].toUpperCase()
      : 'HTTP';
  const sslCertificateArn =
    typeof attrs['certificate_arn'] === 'string'
      ? attrs['certificate_arn']
      : undefined;
  const sslPolicy =
    typeof attrs['ssl_policy'] === 'string' ? attrs['ssl_policy'] : undefined;

  return { port, protocol, sslCertificateArn, sslPolicy };
}

/**
 * Scans siblingResources for an aws_lb_target_group and extracts target group config.
 * Falls back to port 80 and the given defaultProtocol (default 'HTTP') when no sibling is found.
 */
export function resolveTargetGroupConfig(
  ctx: TranslationContext,
  defaultProtocol = 'HTTP',
): TargetGroupConfig {
  const tg = ctx.siblingResources.find(
    (r) => r.sourceType === 'aws_lb_target_group',
  );
  if (!tg) {
    return { port: 80, protocol: defaultProtocol };
  }

  const attrs = tg.attributes as Record<string, unknown>;
  const port = typeof attrs['port'] === 'number' ? attrs['port'] : 80;
  const protocol =
    typeof attrs['protocol'] === 'string'
      ? attrs['protocol'].toUpperCase()
      : 'HTTP';

  // Health check block
  const hc = attrs['health_check'] as Record<string, unknown> | undefined;
  const healthCheckPath =
    hc && typeof hc['path'] === 'string' ? hc['path'] : undefined;
  const healthCheckProtocol =
    hc && typeof hc['protocol'] === 'string'
      ? hc['protocol'].toUpperCase()
      : undefined;
  const healthCheckPort =
    hc && typeof hc['port'] === 'number' ? hc['port'] : undefined;

  return { port, protocol, healthCheckPath, healthCheckProtocol, healthCheckPort };
}

/**
 * Checks whether a sibling aws_wafv2_web_acl_association exists.
 */
export function detectWafAssociation(ctx: TranslationContext): boolean {
  return ctx.siblingResources.some(
    (r) => r.sourceType === 'aws_wafv2_web_acl_association',
  );
}

// ---------------------------------------------------------------------------
// Protocol mapping
// ---------------------------------------------------------------------------

/**
 * Maps an AWS protocol string to its Azure equivalent.
 */
export function mapProtocolToAzure(protocol: string): ProtocolMapResult {
  const upper = protocol.toUpperCase();
  const mapped = AZURE_PROTOCOL_MAP.get(upper);
  if (mapped) {
    return { protocol: mapped, unknownProtocol: false };
  }
  // Fallback: pass through title-cased
  return {
    protocol: upper.charAt(0) + upper.slice(1).toLowerCase(),
    unknownProtocol: true,
  };
}

/**
 * Maps an AWS protocol string to its GCP equivalent.
 * Uses the ALB map when isAlb is true, NLB map otherwise.
 */
export function mapProtocolToGcp(
  protocol: string,
  isAlb: boolean,
): ProtocolMapResult {
  const upper = protocol.toUpperCase();
  const map = isAlb ? GCP_ALB_PROTOCOL_MAP : GCP_NLB_PROTOCOL_MAP;
  const mapped = map.get(upper);
  if (mapped) {
    return { protocol: mapped, unknownProtocol: false };
  }
  // Fallback: pass through uppercased
  return { protocol: upper, unknownProtocol: true };
}
