/**
 * AWS RDS Instance -> Azure DB / GCP Cloud SQL translation.
 * Internal dispatch on engine type (postgres, mysql, sqlserver).
 *
 * Azure postgres/mysql: 1 resource (Flexible Server)
 * Azure sqlserver:      2 resources (MSSQL Server + MSSQL Database)
 * GCP (all engines):    3 resources (SQL Instance + SQL Database + SQL User)
 *
 * @module compound/rds-mapping
 * @generated by code-generator (TASK-TRANS-004, TASK-DATA-001)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';
import { createAdvisoryStub } from '../advisory/advisory-helpers.js';
import { resolveParameterGroup } from './rds-parameter-group.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'allocated_storage',
  'backup_retention_period',
  'backup_window',
  'db_name',
  'deletion_protection',
  'engine',
  'engine_version',
  'instance_class',
  'kms_key_id',
  'multi_az',
  'parameter_group_name',
  'parameters',
  'password',
  'port',
  'publicly_accessible',
  'storage_encrypted',
  'storage_type',
  'tags',
  'username',
];

// ---------------------------------------------------------------------------
// Instance class mapping
// ---------------------------------------------------------------------------

const RDS_INSTANCE_MAP: ReadonlyMap<string, { azure: string; gcp: string }> =
  new Map([
    ['db.t3.micro', { azure: 'B_Standard_B1ms', gcp: 'db-f1-micro' }],
    ['db.t3.small', { azure: 'B_Standard_B1ms', gcp: 'db-g1-small' }],
    ['db.t3.medium', { azure: 'B_Standard_B2s', gcp: 'db-custom-2-4096' }],
    ['db.m5.large', { azure: 'GP_Standard_D2ds_v4', gcp: 'db-custom-2-8192' }],
    ['db.m5.xlarge', { azure: 'GP_Standard_D4ds_v4', gcp: 'db-custom-4-16384' }],
    ['db.m5.2xlarge', { azure: 'GP_Standard_D8ds_v4', gcp: 'db-custom-8-32768' }],
    ['db.r5.large', { azure: 'MO_Standard_E2ds_v4', gcp: 'db-custom-2-16384' }],
    ['db.r5.xlarge', { azure: 'MO_Standard_E4ds_v4', gcp: 'db-custom-4-32768' }],
  ]);

// Azure target type by engine
const AZURE_ENGINE_MAP: ReadonlyMap<string, string> = new Map([
  ['postgres', 'azurerm_postgresql_flexible_server'],
  ['mysql', 'azurerm_mysql_flexible_server'],
  ['mariadb', 'azurerm_mysql_flexible_server'],
]);

// GCP database_version by engine
const GCP_VERSION_MAP: ReadonlyMap<string, string> = new Map([
  ['postgres', 'POSTGRES_15'],
  ['mysql', 'MYSQL_8_0'],
  ['mariadb', 'MYSQL_8_0'],
  ['sqlserver-ee', 'SQLSERVER_2019_ENTERPRISE'],
  ['sqlserver-se', 'SQLSERVER_2019_STANDARD'],
  ['sqlserver-ex', 'SQLSERVER_2019_EXPRESS'],
  ['sqlserver-web', 'SQLSERVER_2019_WEB'],
]);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function isSqlServer(engine: string): boolean {
  return engine.startsWith('sqlserver');
}

function resolveGcpVersion(engine: string, engineVersion?: string): string {
  const mapped = GCP_VERSION_MAP.get(engine);
  if (mapped) return mapped;

  // Fallback: construct from engine + version
  if (engine === 'postgres' && engineVersion) {
    const major = engineVersion.split('.')[0];
    return `POSTGRES_${major}`;
  }
  if (engine === 'mysql' && engineVersion) {
    const parts = engineVersion.split('.');
    return `MYSQL_${parts[0]}_${parts[1]}`;
  }
  return 'POSTGRES_15';
}

// ---------------------------------------------------------------------------
// Azure translation: postgres/mysql -> 1 Flexible Server
// ---------------------------------------------------------------------------

function translateFlexibleServerToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'compound/rds', 'compound');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const engine = (attrs['engine'] as string | undefined) ?? 'postgres';
  const engineVersion = attrs['engine_version'] as string | undefined;
  const instanceClass = (attrs['instance_class'] as string | undefined) ?? 'db.t3.micro';
  const allocatedStorage = (attrs['allocated_storage'] as number | undefined) ?? 20;
  const backupRetention = (attrs['backup_retention_period'] as number | undefined) ?? 7;
  const multiAz = attrs['multi_az'] as boolean | undefined;
  const deletionProtection = attrs['deletion_protection'] as boolean | undefined;

  const sizeEntry = RDS_INSTANCE_MAP.get(instanceClass);
  const sku = sizeEntry?.azure ?? 'B_Standard_B1ms';
  const resolvedTargetType = AZURE_ENGINE_MAP.get(engine);
  const targetType = resolvedTargetType ?? 'azurerm_postgresql_flexible_server';

  const serverAttrs: Record<string, unknown> = {
    administrator_login: (attrs['username'] as string | undefined) ?? 'adminuser',
    administrator_password: (attrs['password'] as string | undefined) ?? '${var.db_password}',
    backup_retention_days: backupRetention,
    location: '${azurerm_resource_group.main.location}',
    name: sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    sku_name: sku,
    storage_mb: allocatedStorage * 1024,
  };

  if (engineVersion) {
    serverAttrs['version'] = engineVersion;
  }

  if (multiAz === true) {
    serverAttrs['high_availability'] = { mode: 'ZoneRedundant' };
  }

  if (tags) serverAttrs['tags'] = transformTags('azure', tags);

  const translated: TranslatedResource[] = [
    {
      targetType,
      targetName: sourceName,
      attributes: serverAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  // Resolve parameter group parameters when present
  const rawParameters = attrs['parameters'] as Record<string, string> | undefined;
  const paramGroupResult = rawParameters
    ? resolveParameterGroup(resource.id, engine, 'azure', rawParameters)
    : null;
  if (paramGroupResult && Object.keys(paramGroupResult.mappedParameters).length > 0) {
    serverAttrs['server_configuration'] = paramGroupResult.mappedParameters;
  }

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    ...(paramGroupResult?.findings ?? []),
    createFinding(
      resource.id,
      'info',
      'COMPOUND_EXPANSION',
      `1 aws_db_instance -> 1 azure resources`,
    ),
  ];

  if (!resolvedTargetType) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'RDS_UNKNOWN_ENGINE_AZURE',
        `Engine '${engine}' has no known Azure Flexible Server mapping; defaulting to azurerm_postgresql_flexible_server`,
      ),
    );
  }

  if (!sizeEntry) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'UNKNOWN_INSTANCE_CLASS',
        `Instance class '${instanceClass}' has no known Azure mapping; defaulting to B_Standard_B1ms`,
      ),
    );
  }

  if (deletionProtection === true) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'RDS_DELETION_PROTECTION',
        `deletion_protection is enabled but Azure Flexible Server does not have a direct equivalent; manual lock recommended`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Azure translation: sqlserver -> 2 resources (Server + Database)
// ---------------------------------------------------------------------------

function translateSqlServerToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'compound/rds', 'compound');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const dbName = (attrs['db_name'] as string | undefined) ?? 'default';
  const multiAz = attrs['multi_az'] as boolean | undefined;
  const storageEncrypted = attrs['storage_encrypted'] as boolean | undefined;

  // 1. MSSQL Server
  const serverAttrs: Record<string, unknown> = {
    administrator_login: (attrs['username'] as string | undefined) ?? 'adminuser',
    administrator_login_password: (attrs['password'] as string | undefined) ?? '${var.db_password}',
    location: '${azurerm_resource_group.main.location}',
    name: sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    version: '12.0',
  };
  if (tags) serverAttrs['tags'] = transformTags('azure', tags);

  // 2. MSSQL Database
  const dbAttrs: Record<string, unknown> = {
    name: dbName,
    server_id: `\${azurerm_mssql_server.${sourceName}.id}`,
    sku_name: 'S0',
  };
  if (tags) dbAttrs['tags'] = transformTags('azure', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_mssql_server',
      targetName: sourceName,
      attributes: serverAttrs,
      sourceId: resource.id,
      traceability,
    },
    {
      targetType: 'azurerm_mssql_database',
      targetName: `${sourceName}_db`,
      attributes: dbAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  // Resolve parameter group parameters when present
  const engine = (attrs['engine'] as string | undefined) ?? 'sqlserver-ee';
  const rawParameters = attrs['parameters'] as Record<string, string> | undefined;
  const paramGroupResult = rawParameters
    ? resolveParameterGroup(resource.id, engine, 'azure', rawParameters)
    : null;
  if (paramGroupResult && Object.keys(paramGroupResult.mappedParameters).length > 0) {
    dbAttrs['server_configuration'] = paramGroupResult.mappedParameters;
  }

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    ...(paramGroupResult?.findings ?? []),
    createFinding(
      resource.id,
      'info',
      'COMPOUND_EXPANSION',
      `1 aws_db_instance -> 2 azure resources`,
    ),
  ];

  if (multiAz === true) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'RDS_SQLSERVER_MULTI_AZ',
        `multi_az is enabled but Azure MSSQL Server uses a different HA model (failover groups); manual configuration required`,
      ),
    );
  }

  if (storageEncrypted === true) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'RDS_SQLSERVER_TDE',
        `Azure MSSQL enables Transparent Data Encryption (TDE) by default; no additional configuration needed`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation (3 resources: SQL Instance + Database + User)
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'compound/rds', 'compound');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const engine = (attrs['engine'] as string | undefined) ?? 'postgres';
  const engineVersion = attrs['engine_version'] as string | undefined;
  const instanceClass = (attrs['instance_class'] as string | undefined) ?? 'db.t3.micro';
  const allocatedStorage = (attrs['allocated_storage'] as number | undefined) ?? 20;
  const dbName = (attrs['db_name'] as string | undefined) ?? 'default';
  const username = (attrs['username'] as string | undefined) ?? 'adminuser';
  const password = (attrs['password'] as string | undefined) ?? '${var.db_password}';

  const multiAz = attrs['multi_az'] as boolean | undefined;
  const backupRetention = (attrs['backup_retention_period'] as number | undefined) ?? 7;
  const deletionProtection = attrs['deletion_protection'] as boolean | undefined;

  const sizeEntry = RDS_INSTANCE_MAP.get(instanceClass);
  const tier = sizeEntry?.gcp ?? 'db-f1-micro';
  const resolvedGcpVersion = GCP_VERSION_MAP.get(engine);
  const databaseVersion = resolveGcpVersion(engine, engineVersion);

  const storageType = (attrs['storage_type'] as string | undefined) === 'io1'
    ? 'PD_SSD'
    : 'PD_HDD';

  // 1. SQL Database Instance
  const settings: Record<string, unknown> = {
    availability_type: multiAz === true ? 'REGIONAL' : 'ZONAL',
    backup_configuration: {
      enabled: true,
      binary_log_enabled: engine === 'mysql' || engine === 'mariadb',
      transaction_log_retention_days: backupRetention,
    },
    disk_autoresize: true,
    disk_size: allocatedStorage,
    disk_type: storageType,
    tier,
  };

  const instanceAttrs: Record<string, unknown> = {
    database_version: databaseVersion,
    deletion_protection_enabled: deletionProtection === true,
    name: sourceName,
    region: '${var.region}',
    settings,
  };
  if (tags) instanceAttrs['labels'] = transformTags('gcp', tags);

  // 2. SQL Database
  const dbAttrs: Record<string, unknown> = {
    instance: `\${google_sql_database_instance.${sourceName}.name}`,
    name: dbName,
  };

  // 3. SQL User
  const userAttrs: Record<string, unknown> = {
    instance: `\${google_sql_database_instance.${sourceName}.name}`,
    name: username,
    password,
  };

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_sql_database_instance',
      targetName: sourceName,
      attributes: instanceAttrs,
      sourceId: resource.id,
      traceability,
    },
    {
      targetType: 'google_sql_database',
      targetName: `${sourceName}_db`,
      attributes: dbAttrs,
      sourceId: resource.id,
      traceability,
    },
    {
      targetType: 'google_sql_user',
      targetName: `${sourceName}_user`,
      attributes: userAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  // Resolve parameter group parameters when present
  const rawParameters = attrs['parameters'] as Record<string, string> | undefined;
  const paramGroupResult = rawParameters
    ? resolveParameterGroup(resource.id, engine, 'gcp', rawParameters)
    : null;
  if (paramGroupResult && Object.keys(paramGroupResult.mappedParameters).length > 0) {
    settings['database_flags'] = Object.entries(paramGroupResult.mappedParameters).map(
      ([name, value]) => ({ name, value }),
    );
  }

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    ...(paramGroupResult?.findings ?? []),
    createFinding(
      resource.id,
      'info',
      'COMPOUND_EXPANSION',
      `1 aws_db_instance -> 3 gcp resources`,
    ),
  ];

  if (!resolvedGcpVersion) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'RDS_UNKNOWN_ENGINE_GCP',
        `Engine '${engine}' has no known GCP Cloud SQL version mapping; defaulting to POSTGRES_15`,
      ),
    );
  }

  if (!sizeEntry) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'UNKNOWN_INSTANCE_CLASS',
        `Instance class '${instanceClass}' has no known GCP mapping; defaulting to db-f1-micro`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_db_instance resource to Azure or GCP equivalents.
 * Dispatches internally based on the engine attribute.
 */
export function translateRds(ctx: TranslationContext): EngineResult {
  const attrs = ctx.resource.attributes as Record<string, unknown>;
  const engine = (attrs['engine'] as string | undefined) ?? 'postgres';

  // Oracle gate: no automated translation available
  if (engine.startsWith('oracle')) {
    return createAdvisoryStub(
      ctx,
      'RDS_ORACLE_ADVISORY',
      `Oracle engine '${engine}' has no automated translation path; manual migration required`,
      [
        'Export schema and data using Oracle Data Pump',
        'Evaluate target database compatibility (PostgreSQL, MySQL, or managed Oracle)',
        'Use AWS SCT or equivalent tool for schema conversion',
        'Validate stored procedures and PL/SQL compatibility',
        'Plan data migration and cutover strategy',
      ],
      ctx.targetProvider === 'azure'
        ? ['Azure Database for PostgreSQL', 'Azure SQL Managed Instance', 'Oracle on Azure VM']
        : ['Cloud SQL for PostgreSQL', 'Cloud SQL for MySQL', 'Bare Metal Oracle on GCP'],
    );
  }

  // publicly_accessible blocker: security gate
  const publiclyAccessible = attrs['publicly_accessible'];
  if (publiclyAccessible === true) {
    return {
      translated: [],
      findings: [
        createFinding(
          ctx.resource.id,
          'blocker',
          'RDS_PUBLICLY_ACCESSIBLE',
          `publicly_accessible is true; database must not be exposed to the public internet — translation blocked`,
        ),
      ],
    };
  }

  if (ctx.targetProvider === 'azure') {
    return isSqlServer(engine)
      ? translateSqlServerToAzure(ctx)
      : translateFlexibleServerToAzure(ctx);
  }
  return translateToGcp(ctx);
}
