/**
 * Top-level orchestrator for HCL validation.
 * Writes files to a temp directory, runs Terraform validate, maps findings.
 * Uses try/finally for guaranteed temp-dir cleanup.
 *
 * @module validation/hcl-validator
 * @generated by code-generator (TASK-VAL-001)
 */

import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import type { TranslationFinding } from '@tla/shared';
import { createFinding } from '../engines/direct/attribute-transformer.js';
import {
  runTerraformValidate,
  type TerraformRunOptions,
} from './terraform-runner.js';
import {
  mapTerraformDiagnostics,
  HCL_VALIDATION_RESOURCE_ID,
} from './finding-mapper.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Options forwarded to the Terraform runner. */
export interface ValidateHclOptions extends TerraformRunOptions {}

/** Result of HCL validation. */
export interface ValidationResult {
  /** All findings produced during validation. */
  readonly findings: TranslationFinding[];
  /** True when no blocker-severity findings exist. */
  readonly valid: boolean;
}

// ---------------------------------------------------------------------------
// Implementation
// ---------------------------------------------------------------------------

/**
 * Validates generated HCL files by writing them to a temporary directory
 * and invoking `terraform validate -json`.
 *
 * @param files - Map of filename to HCL content (e.g. `{ "main.tf": "..." }`).
 * @param options - Optional runner configuration.
 * @returns Validation result containing findings and an overall validity flag.
 */
export function validateHcl(
  files: Record<string, string>,
  options?: ValidateHclOptions,
): ValidationResult {
  // --- Guard: empty input ---
  const entries = Object.entries(files);
  if (entries.length === 0) {
    const findings = [
      createFinding(
        HCL_VALIDATION_RESOURCE_ID,
        'info',
        'HCL_VALIDATION_SKIPPED',
        'No files provided for HCL validation.',
      ),
    ];
    return { findings, valid: true };
  }

  // --- Write files to temp dir, validate, clean up ---
  let tempDir: string | undefined;
  try {
    tempDir = mkdtempSync(join(tmpdir(), 'tla-hcl-'));

    for (const [filename, content] of entries) {
      writeFileSync(join(tempDir, filename), content, 'utf-8');
    }

    const result = runTerraformValidate(tempDir, options);

    if (!result.ok) {
      const severity = result.code === 'HCL_VALIDATION_SKIPPED' ? 'info' : 'warning';
      const findings = [
        createFinding(
          HCL_VALIDATION_RESOURCE_ID,
          severity,
          result.code,
          result.message,
        ),
      ];
      return { findings, valid: true };
    }

    const findings = mapTerraformDiagnostics(result.stdout);
    const valid = !findings.some((f) => f.severity === 'blocker');
    return { findings, valid };
  } catch (err: unknown) {
    // Unexpected errors — should not happen, but never throw.
    const message = err instanceof Error ? err.message : String(err);
    const findings = [
      createFinding(
        HCL_VALIDATION_RESOURCE_ID,
        'warning',
        'HCL_VALIDATION_ERROR',
        `Unexpected error during HCL validation: ${message}`,
      ),
    ];
    return { findings, valid: false };
  } finally {
    if (tempDir) {
      try {
        rmSync(tempDir, { recursive: true, force: true });
      } catch {
        // Best-effort cleanup — swallow errors.
      }
    }
  }
}
