/**
 * HCL validation module — validates generated Terraform files via
 * `terraform validate -json`.
 *
 * @module validation
 * @generated by code-generator (TASK-VAL-001)
 */

export { validateHcl, type ValidateHclOptions, type ValidationResult } from './hcl-validator.js';
export { runTerraformValidate, type TerraformRunOptions, type TerraformRunResult, type TerraformRunSuccess, type TerraformRunFailure } from './terraform-runner.js';
export { mapTerraformDiagnostics, HCL_VALIDATION_RESOURCE_ID } from './finding-mapper.js';
