/**
 * Synchronous Terraform CLI runner for HCL validation.
 * Uses execFileSync with array args (no shell injection).
 * Never throws — all errors become typed results.
 *
 * @module validation/terraform-runner
 * @generated by code-generator (TASK-VAL-001)
 */

import { execFileSync } from 'node:child_process';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Options for the Terraform validation runner. */
export interface TerraformRunOptions {
  /** Timeout in milliseconds for each CLI invocation. Default: 30_000. */
  readonly timeoutMs?: number;
  /** Override the terraform binary path. Takes precedence over `tool`. */
  readonly terraformBin?: string;
  /**
   * Which Terraform-compatible CLI to use.
   * Ignored when `terraformBin` is explicitly set.
   * Default: 'terraform'.
   */
  readonly tool?: 'terraform' | 'tofu';
}

/** Successful run — stdout contains `terraform validate -json` output. */
export interface TerraformRunSuccess {
  readonly ok: true;
  readonly stdout: string;
}

/** Failed run — code indicates the failure category. */
export interface TerraformRunFailure {
  readonly ok: false;
  readonly code: 'HCL_VALIDATION_SKIPPED' | 'HCL_VALIDATION_TIMEOUT' | 'HCL_VALIDATION_ERROR';
  readonly message: string;
}

/** Discriminated union returned by {@link runTerraformValidate}. */
export type TerraformRunResult = TerraformRunSuccess | TerraformRunFailure;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEFAULT_TIMEOUT_MS = 30_000;
const DEFAULT_BIN = 'terraform';

// ---------------------------------------------------------------------------
// Implementation
// ---------------------------------------------------------------------------

/**
 * Runs `terraform init -backend=false` then `terraform validate -json`
 * inside the given working directory.
 *
 * @param cwd - Directory containing .tf files to validate.
 * @param options - Optional runner configuration.
 * @returns A discriminated union describing success or categorised failure.
 */
export function runTerraformValidate(
  cwd: string,
  options?: TerraformRunOptions,
): TerraformRunResult {
  const bin = options?.terraformBin ?? options?.tool ?? DEFAULT_BIN;
  const timeout = options?.timeoutMs ?? DEFAULT_TIMEOUT_MS;

  // --- terraform init ---
  try {
    execFileSync(bin, ['init', '-backend=false', '-no-color'], {
      cwd,
      encoding: 'utf-8',
      timeout,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
  } catch (err: unknown) {
    return categoriseError(err, 'init');
  }

  // --- terraform validate -json ---
  try {
    const stdout = execFileSync(bin, ['validate', '-json'], {
      cwd,
      encoding: 'utf-8',
      timeout,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return { ok: true, stdout };
  } catch (err: unknown) {
    // Terraform exits non-zero on validation errors but still writes JSON to
    // stdout — treat that as a success so the caller can parse diagnostics.
    const execErr = err as { stdout?: string; killed?: boolean; code?: string };
    if (execErr.stdout && typeof execErr.stdout === 'string' && execErr.stdout.trim().length > 0) {
      return { ok: true, stdout: execErr.stdout };
    }
    return categoriseError(err, 'validate');
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function categoriseError(err: unknown, phase: string): TerraformRunFailure {
  const execErr = err as { code?: string; killed?: boolean; message?: string };

  if (execErr.code === 'ENOENT') {
    return {
      ok: false,
      code: 'HCL_VALIDATION_SKIPPED',
      message: 'Terraform binary not found on PATH — validation skipped.',
    };
  }

  if (execErr.killed === true) {
    return {
      ok: false,
      code: 'HCL_VALIDATION_TIMEOUT',
      message: `Terraform ${phase} timed out.`,
    };
  }

  return {
    ok: false,
    code: 'HCL_VALIDATION_ERROR',
    message: `Terraform ${phase} failed: ${execErr.message ?? 'unknown error'}`,
  };
}
