// ---------------------------------------------------------------------------
// Compliance finding codes
// ---------------------------------------------------------------------------

export const COMPLIANCE_CODES = {
  ENCRYPTION_AT_REST: 'COMPLIANCE_ENCRYPTION_AT_REST',
  ENCRYPTION_IN_TRANSIT: 'COMPLIANCE_ENCRYPTION_IN_TRANSIT',
  NETWORK_OPEN_INGRESS: 'COMPLIANCE_NETWORK_OPEN_INGRESS',
  NETWORK_SSH_RESTRICTED: 'COMPLIANCE_NETWORK_SSH_RESTRICTED',
  NETWORK_PUBLIC_IP: 'COMPLIANCE_NETWORK_PUBLIC_IP',
  LOGGING_ENABLED: 'COMPLIANCE_LOGGING_ENABLED',
  IAM_ADMIN_POLICY: 'COMPLIANCE_IAM_ADMIN_POLICY',
  IAM_MFA_REQUIRED: 'COMPLIANCE_IAM_MFA_REQUIRED',
  ENGINE_ERROR: 'COMPLIANCE_ENGINE_ERROR',
} as const;

export type ComplianceCode = (typeof COMPLIANCE_CODES)[keyof typeof COMPLIANCE_CODES];
