/**
 * Azure Terraform code generator.
 *
 * Takes an array of {@link TranslatedResource} objects (produced by the
 * translation engines) and emits a set of `.tf` files ready for
 * `terraform init && terraform plan`.
 *
 * Output files:
 * - `main.tf`       — resource blocks sorted by (targetType, targetName)
 * - `providers.tf`  — `provider "azurerm"` with `features {}`
 * - `terraform.tf`  — `required_providers` block
 * - `variables.tf`  — location, resource_group_name, environment, subscription_id
 * - `outputs.tf`    — resource_group_name, resource_group_id
 *
 * @module codegen/azure-codegen
 * @generated by code-generator (TASK-TRANS-006)
 */

import type { TranslatedResource } from '@tla/shared';
import { createComponentLogger } from '@tla/shared';

import {
  literal,
  expr,
  hclMap,
  block,
  list,
  writeResourceBlock,
  writeProviderBlock,
  writeTerraformBlock,
  writeVariableBlock,
  writeOutputBlock,
} from './hcl-writer.js';
import type { HclValue, HclMapEntry, HclMap, HclBlock } from './hcl-writer.js';
import { resolveAzureRegion } from './azure/region-mapping.js';
import { sanitizeAzureName } from './azure/naming.js';

const logger = createComponentLogger('azure-codegen');

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

/**
 * Options for the Azure code generator.
 */
export interface AzureGenOptions {
  /** AWS source region for location mapping. Default `'us-east-1'`. */
  readonly sourceRegion?: string;
  /** Terraform name for the resource group. Default `'main'`. */
  readonly resourceGroupName?: string;
  /** If set, adds `subscription_id` to the provider block. */
  readonly subscriptionIdVar?: string;
  /** Environment tag value. Default `'dev'`. */
  readonly environment?: string;
  /** Emit `# Source:` comments above resource blocks. Default `true`. */
  readonly emitComments?: boolean;
  /** Sort attributes alphabetically within each resource. Default `true`. */
  readonly sortKeys?: boolean;
  /** Emit an `azurerm_resource_group` block in main.tf. Default `true`. */
  readonly emitResourceGroup?: boolean;
}

// ---------------------------------------------------------------------------
// Generated file map
// ---------------------------------------------------------------------------

export type GeneratedFiles = Map<string, string>;

// ---------------------------------------------------------------------------
// Block key detection set
// ---------------------------------------------------------------------------

/**
 * Attribute keys that must be rendered as HCL blocks (no `=`, no commas)
 * rather than map literals. Exception: `tags` is always a map.
 */
const AZURE_BLOCK_KEYS: ReadonlySet<string> = new Set([
  'ip_configuration',
  'os_disk',
  'source_image_reference',
  'admin_ssh_key',
  'network_interface',
  'backend_address_pool',
  'backend_http_settings',
  'frontend_ip_configuration',
  'frontend_port',
  'gateway_ip_configuration',
  'http_listener',
  'request_routing_rule',
  'rule',
  'probe',
  'default_node_pool',
  'identity',
  'oms_agent',
  'template',
  'container',
  'scaling',
  'ingress',
  'site_config',
  'application_stack',
  'blob_properties',
  'subnet',
  'delegation',
  'service_delegation',
  'record',
  'access_policy',
  'network_acls',
  'criteria',
  'high_availability',
  'authentication',
  'sku',
  'private_service_connection',
  'private_dns_zone_group',
]);

// ---------------------------------------------------------------------------
// Value conversion
// ---------------------------------------------------------------------------

/**
 * Converts an arbitrary JS value (from TranslatedResource.attributes) into
 * an {@link HclValue} using the heuristics described in the architecture.
 *
 * @internal Exported for unit-test access only. Not part of the public API
 *           contract -- prefer {@link AzureCodeGenerator.generate} for
 *           external consumers.
 * @param value     - The value to convert.
 * @param parentKey - The attribute key that holds this value (used for
 *                    block-vs-map disambiguation).
 */
export function convertValue(value: unknown, parentKey?: string): HclValue {
  if (value === null || value === undefined) {
    return literal(null);
  }
  if (typeof value === 'boolean') {
    return literal(value);
  }
  if (typeof value === 'number') {
    return literal(value);
  }
  if (typeof value === 'string') {
    // Terraform interpolation: ${...} → expression
    const interpMatch = /^\$\{(.+)\}$/.exec(value);
    if (interpMatch) {
      return expr(interpMatch[1]!);
    }
    return literal(value);
  }

  if (Array.isArray(value)) {
    // Arrays of objects where the parent key is a block key → blocks
    if (
      value.length > 0 &&
      value.every((v) => typeof v === 'object' && v !== null && !Array.isArray(v)) &&
      parentKey !== undefined &&
      AZURE_BLOCK_KEYS.has(parentKey)
    ) {
      const blockEntries: HclMapEntry[] = value.map((item) => ({
        key: parentKey,
        value: convertObject(item as Record<string, unknown>, true),
      }));
      return { kind: 'blocks', blocks: blockEntries };
    }
    // Regular list
    return list(value.map((v) => convertValue(v)));
  }

  if (typeof value === 'object') {
    return convertObject(value as Record<string, unknown>, isBlockKey(parentKey));
  }

  // Fallback — stringify
  return literal(String(value));
}

/**
 * Converts a plain object to either an HclMap or HclBlock.
 */
function convertObject(
  obj: Record<string, unknown>,
  asBlock: boolean,
): HclMap | HclBlock {
  const entries: HclMapEntry[] = Object.keys(obj).map((k) => ({
    key: k,
    value: convertValue(obj[k], k),
  }));

  if (asBlock) {
    return { kind: 'block', body: entries };
  }
  return { kind: 'map', entries };
}

/**
 * Determines whether a key should produce a block (not a map).
 * `tags` is always a map; keys in AZURE_BLOCK_KEYS are blocks.
 */
function isBlockKey(key: string | undefined): boolean {
  if (key === undefined) return false;
  if (key === 'tags') return false;
  return AZURE_BLOCK_KEYS.has(key);
}

// ---------------------------------------------------------------------------
// Resource conversion
// ---------------------------------------------------------------------------

/**
 * Converts a TranslatedResource's attributes into an array of HclMapEntry.
 */
function resourceToEntries(
  resource: TranslatedResource,
  sortKeys: boolean,
): HclMapEntry[] {
  const attrs = resource.attributes as Record<string, unknown>;
  const keys = sortKeys
    ? Object.keys(attrs).sort((a, b) => a.localeCompare(b))
    : Object.keys(attrs);

  return keys.map((k) => ({ key: k, value: convertValue(attrs[k], k) }));
}

// ---------------------------------------------------------------------------
// File generators
// ---------------------------------------------------------------------------

function generateMainTf(
  resources: readonly TranslatedResource[],
  options: Required<AzureGenOptions>,
): string {
  const sorted = [...resources].sort((a, b) => {
    const typeCmp = a.targetType.localeCompare(b.targetType);
    return typeCmp !== 0 ? typeCmp : a.targetName.localeCompare(b.targetName);
  });

  const blocks: string[] = [];

  // Optional resource group
  if (options.emitResourceGroup) {
    const rgBody: HclMapEntry[] = [
      { key: 'name', value: expr('var.resource_group_name') },
      { key: 'location', value: expr('var.location') },
      { key: 'tags', value: hclMap({
        environment: expr('var.environment'),
      }) },
    ];
    blocks.push(
      writeResourceBlock(
        'azurerm_resource_group',
        options.resourceGroupName,
        rgBody,
        { comment: 'Resource Group', sortKeys: options.sortKeys },
      ),
    );
  }

  for (const resource of sorted) {
    const entries = resourceToEntries(resource, options.sortKeys);
    const comment = options.emitComments
      ? `Source: ${resource.traceability.sourceType} (${resource.sourceId}), engine: ${resource.traceability.engineUsed}, confidence: ${resource.traceability.confidence}`
      : undefined;

    blocks.push(
      writeResourceBlock(
        resource.targetType,
        sanitizeAzureName(
          extractTypeShort(resource.targetType),
          resource.targetName,
        ),
        entries,
        { comment, sortKeys: options.sortKeys },
      ),
    );
  }

  if (blocks.length === 0) {
    return '# No resources translated\n';
  }

  return blocks.join('\n\n') + '\n';
}

function generateProvidersTf(options: Required<AzureGenOptions>): string {
  const body: HclMapEntry[] = [
    { key: 'features', value: block({}) },
  ];

  if (options.subscriptionIdVar) {
    body.push({
      key: 'subscription_id',
      value: expr(`var.${options.subscriptionIdVar}`),
    });
  }

  return writeProviderBlock('azurerm', body) + '\n';
}

function generateTerraformTf(): string {
  const azurermProvider: HclMapEntry[] = [
    {
      key: 'azurerm',
      value: block({
        source: literal('hashicorp/azurerm'),
        version: literal('~> 3.0'),
      }),
    },
  ];

  const body: HclMapEntry[] = [
    {
      key: 'required_providers',
      value: { kind: 'block' as const, body: azurermProvider },
    },
  ];

  return writeTerraformBlock(body) + '\n';
}

function generateVariablesTf(
  options: Required<AzureGenOptions>,
): string {
  const azureRegion = resolveAzureRegion(options.sourceRegion);

  const blocks: string[] = [
    writeVariableBlock('location', {
      description: 'Azure region for all resources',
      type: 'string',
      defaultValue: literal(azureRegion),
    }),
    writeVariableBlock('resource_group_name', {
      description: 'Name of the resource group',
      type: 'string',
      defaultValue: literal(`rg-${options.environment}`),
    }),
    writeVariableBlock('environment', {
      description: 'Deployment environment',
      type: 'string',
      defaultValue: literal(options.environment),
    }),
    writeVariableBlock('subscription_id', {
      description: 'Azure subscription ID',
      type: 'string',
      sensitive: true,
    }),
  ];

  return blocks.join('\n\n') + '\n';
}

function generateOutputsTf(
  options: Required<AzureGenOptions>,
): string {
  if (!options.emitResourceGroup) {
    return '# No outputs (resource group emission disabled)\n';
  }

  const blocks: string[] = [
    writeOutputBlock('resource_group_name', {
      description: 'The name of the resource group',
      value: expr(`azurerm_resource_group.${options.resourceGroupName}.name`),
    }),
    writeOutputBlock('resource_group_id', {
      description: 'The ID of the resource group',
      value: expr(`azurerm_resource_group.${options.resourceGroupName}.id`),
    }),
  ];

  return blocks.join('\n\n') + '\n';
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Extracts a short type key from an `azurerm_*` resource type string.
 * E.g. `'azurerm_virtual_network'` → `'vnet'`.
 */
const TYPE_SHORT_MAP: ReadonlyMap<string, string> = new Map([
  ['azurerm_resource_group', 'rg'],
  ['azurerm_virtual_network', 'vnet'],
  ['azurerm_subnet', 'snet'],
  ['azurerm_network_security_group', 'nsg'],
  ['azurerm_public_ip', 'pip'],
  ['azurerm_network_interface', 'nic'],
  ['azurerm_linux_virtual_machine', 'vm'],
  ['azurerm_windows_virtual_machine', 'vm'],
  ['azurerm_managed_disk', 'disk'],
  ['azurerm_storage_account', 'st'],
  ['azurerm_storage_container', 'sc'],
  ['azurerm_kubernetes_cluster', 'aks'],
  ['azurerm_key_vault', 'kv'],
  ['azurerm_postgresql_flexible_server', 'psql'],
  ['azurerm_mssql_server', 'sql'],
  ['azurerm_linux_function_app', 'func'],
  ['azurerm_lb', 'lb'],
  ['azurerm_application_gateway', 'agw'],
  ['azurerm_linux_virtual_machine_scale_set', 'vmss'],
  ['azurerm_windows_virtual_machine_scale_set', 'vmss'],
]);

function extractTypeShort(azurermType: string): string {
  return TYPE_SHORT_MAP.get(azurermType) ?? 'resource';
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Azure Terraform code generator.
 *
 * Stateless — construct and call {@link generate} with resources and options.
 */
export class AzureCodeGenerator {
  /**
   * Generates a set of `.tf` files from translated resources.
   *
   * @param resources - Translated Azure resources from the engine pipeline.
   * @param options   - Generation options (all optional with sensible defaults).
   * @returns A Map of filename → file content.
   */
  generate(
    resources: readonly TranslatedResource[],
    options?: AzureGenOptions,
  ): GeneratedFiles {
    const resolved: Required<AzureGenOptions> = {
      sourceRegion: options?.sourceRegion ?? 'us-east-1',
      resourceGroupName: options?.resourceGroupName ?? 'main',
      subscriptionIdVar: options?.subscriptionIdVar ?? '',
      environment: options?.environment ?? 'dev',
      emitComments: options?.emitComments ?? true,
      sortKeys: options?.sortKeys ?? true,
      emitResourceGroup: options?.emitResourceGroup ?? true,
    };

    logger.info({ resourceCount: resources.length, region: resolved.sourceRegion }, 'Generating Azure HCL');

    const files: GeneratedFiles = new Map();

    files.set('main.tf', generateMainTf(resources, resolved));
    files.set('providers.tf', generateProvidersTf(resolved));
    files.set('terraform.tf', generateTerraformTf());
    files.set('variables.tf', generateVariablesTf(resolved));
    files.set('outputs.tf', generateOutputsTf(resolved));

    logger.debug({ files: files.size }, 'Azure codegen complete');

    return files;
  }
}
