/**
 * Code generation barrel — public API for the `codegen` module.
 *
 * @module codegen
 * @generated by code-generator (TASK-TRANS-006)
 */

// HCL writer types and functions
export type {
  HclValue,
  HclLiteral,
  HclExpr,
  HclMap,
  HclBlock,
  HclList,
  HclBlocks,
  HclMapEntry,
  BlockWriteOptions,
} from './hcl-writer.js';

export {
  literal,
  expr,
  hclMap,
  block,
  list,
  writeHclValue,
  writeResourceBlock,
  writeProviderBlock,
  writeTerraformBlock,
  writeVariableBlock,
  writeOutputBlock,
} from './hcl-writer.js';

// Azure code generator
export { AzureCodeGenerator } from './azure-codegen.js';
export type { AzureGenOptions, GeneratedFiles } from './azure-codegen.js';
export { convertValue } from './azure-codegen.js';

// Azure region mapping
export {
  AWS_TO_AZURE_REGION,
  resolveAzureRegion,
  azToAzureZone,
} from './azure/region-mapping.js';

// Azure naming
export type { AzureNameConstraint } from './azure/naming.js';
export {
  AZURE_NAME_LIMITS,
  sanitizeAzureName,
} from './azure/naming.js';

// GCP codegen
export { GcpCodeGenerator } from './gcp-codegen.js';
export type { GcpGenOptions } from './gcp-codegen.js';
export { convertValue as convertGcpValue } from './gcp-codegen.js';

// GCP utilities
export { AWS_TO_GCP_REGION, resolveGcpRegion, awsAzToGcpZone } from './gcp/region-mapping.js';
export { sanitizeGcpName } from './gcp/naming.js';
export type { LabelTransformResult } from './gcp/label-transformer.js';
export { transformLabels } from './gcp/label-transformer.js';
