/**
 * AWS Direct Connect -> Azure ExpressRoute / GCP Interconnect Attachment translation.
 *
 * Handles:
 * - aws_dx_connection -> Azure: azurerm_express_route_circuit, GCP: google_compute_interconnect_attachment
 * - aws_dx_gateway   -> Azure: azurerm_express_route_gateway, GCP: google_compute_router (with BGP ASN)
 *
 * Location requires physical procurement; a ${var.dx_location} placeholder is used.
 *
 * @module parametric/direct-connect-mapping
 * @generated by code-generator (TASK-GAP-010)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Bandwidth normalisation
// Accepts values like "1Gbps", "10Gbps", "100Mbps", "1000Mbps" etc.
// ---------------------------------------------------------------------------

/**
 * Normalises AWS bandwidth string to Mbps integer.
 * Returns undefined when the value cannot be parsed.
 */
function parseBandwidthMbps(raw: string): number | undefined {
  const match = /^(\d+(?:\.\d+)?)\s*(Gbps|Mbps)$/i.exec(raw.trim());
  if (!match) return undefined;
  const value = parseFloat(match[1]!);
  const unit = match[2]!.toUpperCase();
  return unit === 'GBPS' ? Math.round(value * 1000) : Math.round(value);
}

/**
 * Maps Mbps to the nearest Azure ExpressRoute circuit bandwidth string.
 * Azure accepted values: 50, 100, 200, 500, 1000, 2000, 5000, 10000.
 */
function toAzureBandwidthMbps(mbps: number): number {
  const AZURE_TIERS = [50, 100, 200, 500, 1000, 2000, 5000, 10000];
  for (const tier of AZURE_TIERS) {
    if (mbps <= tier) return tier;
  }
  return 10000;
}

/**
 * Maps Mbps to GCP interconnect attachment bandwidth enum.
 * GCP accepted VLAN attachment bandwidths (sample set).
 */
function toGcpBandwidthEnum(mbps: number): string {
  if (mbps <= 50) return 'BPS_50M';
  if (mbps <= 100) return 'BPS_100M';
  if (mbps <= 200) return 'BPS_200M';
  if (mbps <= 300) return 'BPS_300M';
  if (mbps <= 400) return 'BPS_400M';
  if (mbps <= 500) return 'BPS_500M';
  if (mbps <= 1000) return 'BPS_1G';
  if (mbps <= 2000) return 'BPS_2G';
  if (mbps <= 5000) return 'BPS_5G';
  if (mbps <= 10000) return 'BPS_10G';
  return 'BPS_100G';
}

// ---------------------------------------------------------------------------
// Mapped attribute keys
// ---------------------------------------------------------------------------

const MAPPED_KEYS_DX_CONNECTION: readonly string[] = [
  'name',
  'bandwidth',
  'location',
  'provider_name',
  'tags',
];

const MAPPED_KEYS_DX_GATEWAY: readonly string[] = [
  'name',
  'amazon_side_asn',
  'tags',
];

// ---------------------------------------------------------------------------
// aws_dx_connection -> Azure: azurerm_express_route_circuit
// ---------------------------------------------------------------------------

function translateDxConnectionToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/direct-connect', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const rawBandwidth = attrs['bandwidth'] as string | undefined;
  const mbps = rawBandwidth ? parseBandwidthMbps(rawBandwidth) : undefined;
  const azureBandwidth = mbps !== undefined ? toAzureBandwidthMbps(mbps) : 1000;

  const azureAttrs: Record<string, unknown> = {
    bandwidth_in_mbps: azureBandwidth,
    location: '${var.dx_location}',
    name: resource.sourceName,
    peering_location: '${var.dx_location}',
    resource_group_name: '${azurerm_resource_group.main.name}',
    service_provider_name: (attrs['provider_name'] as string | undefined) ?? '${var.dx_provider}',
    sku: {
      family: 'MeteredData',
      tier: 'Standard',
    },
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_express_route_circuit',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_DX_CONNECTION),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'DX_PHYSICAL_PROCUREMENT',
      'Physical connectivity requires separate procurement; ' +
        '${var.dx_location} placeholder must be replaced with the actual ExpressRoute peering location',
    ),
  ];

  if (mbps === undefined && rawBandwidth) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DX_BANDWIDTH_UNKNOWN',
        `Could not parse bandwidth '${rawBandwidth}'; defaulting to 1000 Mbps`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// aws_dx_connection -> GCP: google_compute_interconnect_attachment
// ---------------------------------------------------------------------------

function translateDxConnectionToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/direct-connect', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const rawBandwidth = attrs['bandwidth'] as string | undefined;
  const mbps = rawBandwidth ? parseBandwidthMbps(rawBandwidth) : undefined;
  const gcpBandwidth = mbps !== undefined ? toGcpBandwidthEnum(mbps) : 'BPS_1G';

  const gcpAttrs: Record<string, unknown> = {
    bandwidth: gcpBandwidth,
    interconnect: '${var.dx_location}',
    name: resource.sourceName,
    region: '${var.region}',
    router: '${google_compute_router.main.id}',
    type: 'DEDICATED',
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_interconnect_attachment',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_DX_CONNECTION),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'DX_PHYSICAL_PROCUREMENT',
      'Physical connectivity requires separate procurement; ' +
        '${var.dx_location} placeholder must be replaced with the actual Cloud Interconnect facility',
    ),
  ];

  if (mbps === undefined && rawBandwidth) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DX_BANDWIDTH_UNKNOWN',
        `Could not parse bandwidth '${rawBandwidth}'; defaulting to BPS_1G`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// aws_dx_gateway -> Azure: azurerm_express_route_gateway
// ---------------------------------------------------------------------------

function translateDxGatewayToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/direct-connect-gateway', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const azureAttrs: Record<string, unknown> = {
    location: '${azurerm_resource_group.main.location}',
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    scale_units: 1,
    virtual_hub_id: '${azurerm_virtual_hub.main.id}',
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_express_route_gateway',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_DX_GATEWAY),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'DX_PHYSICAL_PROCUREMENT',
      'Physical connectivity requires separate procurement; ' +
        'ExpressRoute Gateway must be associated with an ExpressRoute circuit after provisioning',
    ),
  ];

  const asn = attrs['amazon_side_asn'];
  if (asn !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'DX_BGP_ASN',
        `AWS Direct Connect Gateway ASN (${asn}) must be configured in the ExpressRoute private peering settings`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// aws_dx_gateway -> GCP: google_compute_router (with BGP ASN)
// ---------------------------------------------------------------------------

function translateDxGatewayToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/direct-connect-gateway', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const asn = (attrs['amazon_side_asn'] as number | string | undefined) ?? 64512;

  const gcpAttrs: Record<string, unknown> = {
    bgp: {
      asn: Number(asn),
    },
    name: resource.sourceName,
    network: '${google_compute_network.main.id}',
    region: '${var.region}',
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_router',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_DX_GATEWAY),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'DX_PHYSICAL_PROCUREMENT',
      'Physical connectivity requires separate procurement; ' +
        'Cloud Router must be attached to an Interconnect attachment after provisioning',
    ),
    createFinding(
      resource.id,
      'info',
      'DX_BGP_ASN',
      `AWS Direct Connect Gateway ASN (${asn}) mapped to Cloud Router bgp.asn; verify BGP peering configuration`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/**
 * Translates an aws_dx_connection resource to Azure or GCP equivalents.
 *
 * Azure: azurerm_express_route_circuit (with bandwidth, SKU, peering location placeholder)
 * GCP:   google_compute_interconnect_attachment (with bandwidth enum, type=DEDICATED)
 */
export function translateDxConnection(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateDxConnectionToAzure(ctx);
  }
  return translateDxConnectionToGcp(ctx);
}

/**
 * Translates an aws_dx_gateway resource to Azure or GCP equivalents.
 *
 * Azure: azurerm_express_route_gateway (associated with virtual hub)
 * GCP:   google_compute_router (with bgp.asn from amazon_side_asn)
 */
export function translateDxGateway(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateDxGatewayToAzure(ctx);
  }
  return translateDxGatewayToGcp(ctx);
}
