/**
 * AWS EKS Cluster -> Azure AKS / GCP GKE translation.
 * Emits advisory findings for IRSA, CNI, and encryption gaps.
 *
 * @module parametric/eks-mapping
 * @generated by code-generator (TASK-TRANS-003)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

const MAPPED_KEYS: readonly string[] = [
  'name',
  'version',
  'role_arn',
  'vpc_config',
  'encryption_config',
  'enabled_cluster_log_types',
  'kubernetes_network_config',
  'tags',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/eks', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const clusterName = (attrs['name'] as string | undefined) ?? resource.sourceName;
  const version = attrs['version'] as string | undefined;

  const azureAttrs: Record<string, unknown> = {
    default_node_pool: {
      name: 'default',
      node_count: 1,
      vm_size: 'Standard_D2_v5',
    },
    dns_prefix: clusterName,
    identity: {
      type: 'SystemAssigned',
    },
    location: '${azurerm_resource_group.main.location}',
    name: clusterName,
    network_profile: {
      network_plugin: 'azure',
    },
    resource_group_name: '${azurerm_resource_group.main.name}',
  };

  if (version) {
    azureAttrs['kubernetes_version'] = version;
  }

  // Log types mapping
  const logTypes = attrs['enabled_cluster_log_types'] as string[] | undefined;
  if (Array.isArray(logTypes) && logTypes.length > 0) {
    azureAttrs['oms_agent'] = {
      log_analytics_workspace_id: '${azurerm_log_analytics_workspace.main.id}',
    };
  }

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_kubernetes_cluster',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  // IRSA advisory
  if (attrs['role_arn']) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'IRSA_WORKLOAD_IDENTITY',
        'AWS IRSA (IAM Roles for Service Accounts) must be manually migrated to Azure Workload Identity',
      ),
    );
  }

  // CNI advisory
  const k8sNetConfig = attrs['kubernetes_network_config'] as
    | Record<string, unknown>
    | undefined;
  if (k8sNetConfig) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'CNI_GAP',
        'AWS VPC CNI configuration mapped to Azure CNI; verify IP allocation and pod networking',
      ),
    );
  }

  // Encryption advisory
  if (attrs['encryption_config']) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'EKS_ENCRYPTION_ADVISORY',
        'AWS EKS envelope encryption requires Azure Key Vault + Azure Disk Encryption for AKS secrets encryption',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/eks', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const clusterName = (attrs['name'] as string | undefined) ?? resource.sourceName;
  const version = attrs['version'] as string | undefined;

  const gcpAttrs: Record<string, unknown> = {
    initial_node_count: 1,
    ip_allocation_policy: {},
    location: '${var.region}',
    name: clusterName,
    remove_default_node_pool: true,
  };

  if (version) {
    gcpAttrs['min_master_version'] = version;
  }

  if (tags) {
    gcpAttrs['resource_labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_container_cluster',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  // IRSA advisory
  if (attrs['role_arn']) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'IRSA_WORKLOAD_IDENTITY',
        'AWS IRSA (IAM Roles for Service Accounts) must be manually migrated to GCP Workload Identity',
      ),
    );
  }

  // CNI advisory
  const k8sNetConfig = attrs['kubernetes_network_config'] as
    | Record<string, unknown>
    | undefined;
  if (k8sNetConfig) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'CNI_GAP',
        'AWS VPC CNI configuration has no direct GKE equivalent; GKE uses VPC-native mode by default',
      ),
    );
  }

  // Encryption advisory
  if (attrs['encryption_config']) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'EKS_ENCRYPTION_ADVISORY',
        'AWS EKS envelope encryption requires GCP KMS + Application-layer Secrets Encryption for GKE',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_eks_cluster resource to Azure or GCP equivalents.
 */
export function translateEks(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
