/**
 * AWS KMS Key -> Azure Key Vault Key / GCP KMS Crypto Key translation.
 * Policy content is NEVER included in translated attributes (PROHIB-1).
 *
 * @module parametric/kms-mapping
 * @generated by code-generator (TASK-TRANS-003)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

const MAPPED_KEYS: readonly string[] = [
  'description',
  'key_usage',
  'customer_master_key_spec',
  'deletion_window_in_days',
  'enable_key_rotation',
  'policy',
  'tags',
];

// ---------------------------------------------------------------------------
// Spec mapping tables
// ---------------------------------------------------------------------------

const SPEC_TO_AZURE_KEY_TYPE: ReadonlyMap<string, { key_type: string; key_size: number }> =
  new Map([
    ['SYMMETRIC_DEFAULT', { key_type: 'RSA', key_size: 2048 }],
    ['RSA_2048', { key_type: 'RSA', key_size: 2048 }],
    ['RSA_3072', { key_type: 'RSA', key_size: 3072 }],
    ['RSA_4096', { key_type: 'RSA', key_size: 4096 }],
    ['ECC_NIST_P256', { key_type: 'EC', key_size: 256 }],
    ['ECC_NIST_P384', { key_type: 'EC', key_size: 384 }],
    ['ECC_NIST_P521', { key_type: 'EC', key_size: 521 }],
    ['ECC_SECG_P256K1', { key_type: 'EC', key_size: 256 }],
  ]);

const USAGE_TO_AZURE_KEY_OPTS: ReadonlyMap<string, readonly string[]> = new Map([
  ['ENCRYPT_DECRYPT', ['decrypt', 'encrypt', 'wrapKey', 'unwrapKey']],
  ['SIGN_VERIFY', ['sign', 'verify']],
]);

const SPEC_TO_GCP_ALGORITHM: ReadonlyMap<string, string> = new Map([
  ['SYMMETRIC_DEFAULT', 'GOOGLE_SYMMETRIC_ENCRYPTION'],
  ['RSA_2048', 'RSA_DECRYPT_OAEP_2048_SHA256'],
  ['RSA_3072', 'RSA_DECRYPT_OAEP_3072_SHA256'],
  ['RSA_4096', 'RSA_DECRYPT_OAEP_4096_SHA256'],
  ['ECC_NIST_P256', 'EC_SIGN_P256_SHA256'],
  ['ECC_NIST_P384', 'EC_SIGN_P384_SHA384'],
  ['ECC_NIST_P521', 'EC_SIGN_P384_SHA384'], // No P521 in GCP; closest match
  ['ECC_SECG_P256K1', 'EC_SIGN_SECP256K1_SHA256'],
]);

const USAGE_TO_GCP_PURPOSE: ReadonlyMap<string, string> = new Map([
  ['ENCRYPT_DECRYPT', 'ENCRYPT_DECRYPT'],
  ['SIGN_VERIFY', 'ASYMMETRIC_SIGN'],
]);

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/kms', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const spec = (attrs['customer_master_key_spec'] as string | undefined) ?? 'SYMMETRIC_DEFAULT';
  const usage = (attrs['key_usage'] as string | undefined) ?? 'ENCRYPT_DECRYPT';

  const azureSpec = SPEC_TO_AZURE_KEY_TYPE.get(spec) ?? { key_type: 'RSA', key_size: 2048 };
  const keyOpts = USAGE_TO_AZURE_KEY_OPTS.get(usage) ?? ['decrypt', 'encrypt'];

  const azureAttrs: Record<string, unknown> = {
    key_opts: [...keyOpts],
    key_size: azureSpec.key_size,
    key_type: azureSpec.key_type,
    key_vault_id: '${azurerm_key_vault.main.id}',
    name: resource.sourceName,
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_key_vault_key',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  // Policy advisory — NEVER include policy content
  if (attrs['policy'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'KMS_POLICY_RBAC',
        'AWS KMS key policy must be manually translated to Azure Key Vault access policies or RBAC',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/kms', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const spec = (attrs['customer_master_key_spec'] as string | undefined) ?? 'SYMMETRIC_DEFAULT';
  const usage = (attrs['key_usage'] as string | undefined) ?? 'ENCRYPT_DECRYPT';
  const rotationEnabled = attrs['enable_key_rotation'] === true;

  const algorithm = SPEC_TO_GCP_ALGORITHM.get(spec) ?? 'GOOGLE_SYMMETRIC_ENCRYPTION';
  const purpose = USAGE_TO_GCP_PURPOSE.get(usage) ?? 'ENCRYPT_DECRYPT';

  const gcpAttrs: Record<string, unknown> = {
    key_ring: '${google_kms_key_ring.main.id}',
    name: resource.sourceName,
    purpose,
    version_template: { algorithm },
  };

  if (rotationEnabled) {
    gcpAttrs['rotation_period'] = '7776000s'; // 90 days
  }

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_kms_crypto_key',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  // Policy advisory — NEVER include policy content
  if (attrs['policy'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'KMS_POLICY_RBAC',
        'AWS KMS key policy must be manually translated to GCP IAM bindings on the key ring',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_kms_key resource to Azure or GCP equivalents.
 */
export function translateKms(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
