/**
 * AWS NAT Gateway -> Azure NAT Gateway / GCP Cloud NAT translation.
 * Both providers emit 2 resources (compound-like output from parametric engine).
 *
 * @module parametric/nat-mapping
 * @generated by code-generator (TASK-TRANS-003)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
  findSiblingVpc,
} from '../direct/attribute-transformer.js';

const MAPPED_KEYS: readonly string[] = [
  'subnet_id',
  'allocation_id',
  'connectivity_type',
  'tags',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/nat', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  // Azure requires a Public IP + NAT Gateway
  const publicIpAttrs: Record<string, unknown> = {
    allocation_method: 'Static',
    location: '${azurerm_resource_group.main.location}',
    name: `${resource.sourceName}_pip`,
    resource_group_name: '${azurerm_resource_group.main.name}',
    sku: 'Standard',
  };

  if (tags) {
    publicIpAttrs['tags'] = transformTags('azure', tags);
  }

  const natGwAttrs: Record<string, unknown> = {
    idle_timeout_in_minutes: 10,
    location: '${azurerm_resource_group.main.location}',
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    sku_name: 'Standard',
  };

  if (tags) {
    natGwAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_public_ip',
      targetName: `${resource.sourceName}_pip`,
      attributes: publicIpAttrs,
      sourceId: resource.id,
      traceability,
    },
    {
      targetType: 'azurerm_nat_gateway',
      targetName: resource.sourceName,
      attributes: natGwAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  // Allocation ID advisory
  if (attrs['allocation_id']) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'NAT_EIP_ASSOCIATION',
        'AWS allocation_id (EIP) mapped to a dedicated azurerm_public_ip; verify association',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/nat', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const vpc = findSiblingVpc(ctx);
  const networkRef = vpc
    ? `\${google_compute_network.${vpc.sourceName}.id}`
    : '';

  // GCP requires a Router + Router NAT
  const routerAttrs: Record<string, unknown> = {
    name: `${resource.sourceName}_router`,
    network: networkRef,
    region: '${var.region}',
  };

  const routerNatAttrs: Record<string, unknown> = {
    name: resource.sourceName,
    nat_ip_allocate_option: 'AUTO_ONLY',
    router: `\${google_compute_router.${resource.sourceName}_router.name}`,
    source_subnetwork_ip_ranges_to_nat: 'ALL_SUBNETWORKS_ALL_IP_RANGES',
  };

  if (tags) {
    // Labels only on the router (NAT doesn't support labels directly)
    routerAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_router',
      targetName: `${resource.sourceName}_router`,
      attributes: routerAttrs,
      sourceId: resource.id,
      traceability,
    },
    {
      targetType: 'google_compute_router_nat',
      targetName: resource.sourceName,
      attributes: routerNatAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  // Connectivity type advisory
  if (attrs['connectivity_type'] === 'private') {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'NAT_PRIVATE_CONNECTIVITY',
        'AWS private NAT connectivity has no direct GCP Cloud NAT equivalent',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_nat_gateway resource to Azure or GCP equivalents.
 */
export function translateNat(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
