/**
 * AWS Secrets Manager -> Azure Key Vault Secret / GCP Secret Manager translation.
 *
 * Handles both aws_secretsmanager_secret and aws_secretsmanager_secret_version.
 *
 * @module parametric/secrets-mapping
 * @generated by code-generator (TASK-TRANS-003 / TASK-DATA-003)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
  findSiblingByType,
} from '../direct/attribute-transformer.js';

const MAPPED_KEYS_SECRET: readonly string[] = [
  'name',
  'description',
  'kms_key_id',
  'recovery_window_in_days',
  'rotation_rules',
  'tags',
  'policy',
];

const MAPPED_KEYS_VERSION: readonly string[] = [
  'secret_id',
  'secret_string',
  'secret_binary',
  'version_stages',
];

// ---------------------------------------------------------------------------
// Azure translation — aws_secretsmanager_secret
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/secrets', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const secretName = (attrs['name'] as string | undefined) ?? resource.sourceName;
  const description = attrs['description'] as string | undefined;

  const azureAttrs: Record<string, unknown> = {
    key_vault_id: '${azurerm_key_vault.main.id}',
    name: secretName,
    value: '${var.secret_value}',
  };

  if (description) {
    azureAttrs['content_type'] = description;
  }

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_key_vault_secret',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_SECRET),
    ...emitBehavioralGapFindings(ctx),
  ];

  // Rotation rules advisory
  if (attrs['rotation_rules'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'SECRET_ROTATION',
        'AWS Secrets Manager rotation_rules must be manually implemented via Azure Automation or Key Vault rotation policy',
      ),
    );
  }

  // KMS CMK advisory
  if (attrs['kms_key_id'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SECRET_CMEK',
        'AWS KMS key encryption mapped to Azure Key Vault managed encryption; configure Key Vault-level CMK if needed',
      ),
    );
  }

  // Recovery window advisory
  if (attrs['recovery_window_in_days'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SECRET_RECOVERY_WINDOW',
        'AWS recovery_window_in_days has no direct Azure equivalent; Azure Key Vault uses soft-delete with a fixed 7-90 day retention configured at vault level',
      ),
    );
  }

  // Policy advisory
  if (attrs['policy'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'SECRET_POLICY',
        'AWS Secrets Manager resource policy has no Azure equivalent; use Azure Key Vault access policies or RBAC instead',
      ),
    );
  }

  // RBAC advisory (always)
  findings.push(
    createFinding(
      resource.id,
      'warning',
      'SECRET_RBAC',
      'Azure Key Vault requires explicit access policy or RBAC role assignment for secret consumers',
    ),
  );

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation — aws_secretsmanager_secret
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/secrets', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const secretName = (attrs['name'] as string | undefined) ?? resource.sourceName;

  const gcpAttrs: Record<string, unknown> = {
    replication: { auto: {} },
    secret_id: secretName,
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_secret_manager_secret',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_SECRET),
    ...emitBehavioralGapFindings(ctx),
  ];

  // Rotation rules advisory
  if (attrs['rotation_rules'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'SECRET_ROTATION',
        'AWS Secrets Manager rotation_rules must be manually implemented via GCP Cloud Functions or Pub/Sub triggers',
      ),
    );
  }

  // KMS CMK advisory
  if (attrs['kms_key_id'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SECRET_CMEK',
        'AWS KMS key encryption mapped to GCP CMEK; configure customer_managed_encryption on the secret if needed',
      ),
    );
  }

  // Recovery window advisory
  if (attrs['recovery_window_in_days'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SECRET_RECOVERY_WINDOW',
        'AWS recovery_window_in_days has no direct GCP equivalent; GCP Secret Manager does not support scheduled secret deletion',
      ),
    );
  }

  // Policy advisory
  if (attrs['policy'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'SECRET_POLICY',
        'AWS Secrets Manager resource policy has no GCP equivalent; use GCP IAM bindings on the secret resource instead',
      ),
    );
  }

  // RBAC advisory (always)
  findings.push(
    createFinding(
      resource.id,
      'warning',
      'SECRET_RBAC',
      'GCP Secret Manager requires explicit IAM bindings (roles/secretmanager.secretAccessor) for secret consumers',
    ),
  );

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Azure translation — aws_secretsmanager_secret_version
// ---------------------------------------------------------------------------

function translateVersionToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_VERSION),
    ...emitBehavioralGapFindings(ctx),
  ];

  // Azure Key Vault secrets don't have a separate version resource;
  // the secret value is set directly on the azurerm_key_vault_secret resource.
  findings.push(
    createFinding(
      resource.id,
      'info',
      'SECRET_VERSION_MERGED',
      'Azure Key Vault manages versions implicitly; secret_version is merged into the parent azurerm_key_vault_secret resource',
    ),
  );

  if (attrs['secret_binary'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SECRET_BINARY',
        'AWS secret_binary must be base64-encoded and stored as the secret value in Azure Key Vault',
      ),
    );
  }

  return { translated: [], findings };
}

// ---------------------------------------------------------------------------
// GCP translation — aws_secretsmanager_secret_version
// ---------------------------------------------------------------------------

function translateVersionToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/secrets-version', 'parametric');
  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_VERSION),
    ...emitBehavioralGapFindings(ctx),
  ];

  // Resolve parent secret reference
  const parent = findSiblingByType(ctx, 'aws_secretsmanager_secret');
  const secretRef = parent
    ? `\${google_secret_manager_secret.${parent.sourceName}.id}`
    : '${google_secret_manager_secret.main.id}';

  if (!parent) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'SECRET_VERSION_ORPHAN',
        'No parent aws_secretsmanager_secret found in IR; using default reference google_secret_manager_secret.main',
      ),
    );
  }

  const gcpAttrs: Record<string, unknown> = {
    secret: secretRef,
    secret_data: '${var.secret_value}',
  };

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_secret_manager_secret_version',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  if (attrs['secret_binary'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SECRET_BINARY',
        'AWS secret_binary must be base64-encoded and stored as secret_data in GCP Secret Manager version',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/**
 * Translates an aws_secretsmanager_secret resource to Azure or GCP equivalents.
 */
export function translateSecrets(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}

/**
 * Translates an aws_secretsmanager_secret_version resource to Azure or GCP equivalents.
 *
 * - Azure: no separate resource (merged into parent secret); emits SECRET_VERSION_MERGED finding.
 * - GCP: emits google_secret_manager_secret_version with parent ref via findSiblingByType.
 *
 * Security: secret_string and secret_binary values are NEVER included in translated output
 * (PRD NFR-SEC-001). A `${var.secret_value}` placeholder is used instead.
 */
export function translateSecretVersion(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateVersionToAzure(ctx);
  }
  return translateVersionToGcp(ctx);
}
