/**
 * AWS Subnet -> Azure Subnet / GCP Subnetwork translation.
 *
 * @module parametric/subnet-mapping
 * @generated by code-generator (TASK-TRANS-003)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  transformRegion,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
  findSiblingVpc,
  azToRegion,
} from '../direct/attribute-transformer.js';

const MAPPED_KEYS: readonly string[] = [
  'cidr_block',
  'availability_zone',
  'vpc_id',
  'map_public_ip_on_launch',
  'tags',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/subnet', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const cidr = (attrs['cidr_block'] as string | undefined) ?? '10.0.1.0/24';
  const vpc = findSiblingVpc(ctx);

  const azureAttrs: Record<string, unknown> = {
    address_prefixes: [cidr],
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    virtual_network_name: vpc
      ? `\${azurerm_virtual_network.${vpc.sourceName}.name}`
      : (attrs['vpc_id'] as string) ?? '',
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  // map_public_ip_on_launch has no direct Azure equivalent
  if (attrs['map_public_ip_on_launch'] === true) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'PUBLIC_IP_LAUNCH',
        'map_public_ip_on_launch requires a separate Azure Public IP association',
      ),
    );
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_subnet',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/subnet', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const cidr = (attrs['cidr_block'] as string | undefined) ?? '10.0.1.0/24';
  const az = attrs['availability_zone'] as string | undefined;
  const vpc = findSiblingVpc(ctx);

  // Derive GCP region from AZ via azToRegion then transformRegion
  const awsRegion = az ? azToRegion(az) : 'us-east-1';
  const gcpRegion = transformRegion('gcp', awsRegion);

  const gcpAttrs: Record<string, unknown> = {
    ip_cidr_range: cidr,
    name: resource.sourceName,
    network: vpc
      ? `\${google_compute_network.${vpc.sourceName}.id}`
      : (attrs['vpc_id'] as string) ?? '',
    region: gcpRegion,
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_subnetwork',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_subnet resource to Azure or GCP equivalents.
 */
export function translateSubnet(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
