/**
 * AWS VPC -> Azure Virtual Network / GCP Compute Network translation.
 *
 * @module parametric/vpc-mapping
 * @generated by code-generator (TASK-TRANS-003)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  transformRegion,
  collectUnmappedAttrs,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

const MAPPED_KEYS: readonly string[] = [
  'cidr_block',
  'enable_dns_support',
  'enable_dns_hostnames',
  'instance_tenancy',
  'tags',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/vpc', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const cidr = (attrs['cidr_block'] as string | undefined) ?? '10.0.0.0/16';

  const azureAttrs: Record<string, unknown> = {
    address_space: [cidr],
    location: transformRegion('azure', 'us-east-1'),
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_virtual_network',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/vpc', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const gcpAttrs: Record<string, unknown> = {
    auto_create_subnetworks: false,
    name: resource.sourceName,
    routing_mode: 'REGIONAL',
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_network',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_vpc resource to Azure or GCP equivalents.
 */
export function translateVpc(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
