/**
 * AWS Site-to-Site VPN -> Azure VPN Gateway / GCP Cloud VPN translation.
 *
 * Handles:
 * - aws_vpn_gateway    -> Azure: azurerm_virtual_network_gateway (type=Vpn)
 *                         GCP:   google_compute_vpn_gateway
 * - aws_vpn_connection -> Azure: azurerm_virtual_network_gateway_connection
 *                         GCP:   google_compute_vpn_tunnel
 * - aws_customer_gateway -> Azure: azurerm_local_network_gateway (ip_address, bgp_settings)
 *                           GCP:   google_compute_external_vpn_gateway
 *
 * Security: pre-shared keys are NEVER included in translated attributes (NFR-SEC-001).
 * A ${var.vpn_psk} placeholder is used instead.
 *
 * Advisory: AWS dual-tunnel HA may require manual configuration on the target side.
 * IKEv1 sources targeting providers that require IKEv2 receive an advisory finding.
 *
 * @module parametric/vpn-mapping
 * @generated by code-generator (TASK-GAP-010)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Mapped attribute keys
// ---------------------------------------------------------------------------

const MAPPED_KEYS_VPN_GATEWAY: readonly string[] = [
  'amazon_side_asn',
  'availability_zone',
  'vpc_id',
  'tags',
];

const MAPPED_KEYS_VPN_CONNECTION: readonly string[] = [
  'customer_gateway_id',
  'vpn_gateway_id',
  'type',
  'static_routes_only',
  'tunnel1_ike_versions',
  'tunnel2_ike_versions',
  'tunnel1_preshared_key',
  'tunnel2_preshared_key',
  'tags',
];

const MAPPED_KEYS_CUSTOMER_GATEWAY: readonly string[] = [
  'bgp_asn',
  'certificate_arn',
  'device_name',
  'ip_address',
  'type',
  'tags',
];

// ---------------------------------------------------------------------------
// IKE version detection
// ---------------------------------------------------------------------------

/**
 * Returns true when all declared IKE versions are IKEv1 only.
 */
function isIkev1Only(attrs: Record<string, unknown>): boolean {
  const t1 = attrs['tunnel1_ike_versions'] as string[] | undefined;
  const t2 = attrs['tunnel2_ike_versions'] as string[] | undefined;
  const allVersions = [...(t1 ?? []), ...(t2 ?? [])];
  if (allVersions.length === 0) return false;
  return allVersions.every((v) => v === 'ikev1');
}

// ---------------------------------------------------------------------------
// aws_vpn_gateway
// ---------------------------------------------------------------------------

function translateVpnGatewayToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/vpn-gateway', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const azureAttrs: Record<string, unknown> = {
    ip_configuration: {
      name: `${resource.sourceName}-ipconfig`,
      private_ip_address_allocation: 'Dynamic',
      public_ip_address_id: `\${azurerm_public_ip.${resource.sourceName}_pip.id}`,
      subnet_id: '${azurerm_subnet.GatewaySubnet.id}',
    },
    location: '${azurerm_resource_group.main.location}',
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    sku: 'VpnGw1',
    type: 'Vpn',
    vpn_type: 'RouteBased',
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_virtual_network_gateway',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_VPN_GATEWAY),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'VPN_DUAL_TUNNEL_HA',
      'AWS VPN Gateway supports dual tunnels for HA; Azure VPN Gateway active-active mode may require manual configuration',
    ),
  ];

  const asn = attrs['amazon_side_asn'];
  if (asn !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'VPN_BGP_ASN',
        `AWS amazon_side_asn (${asn}) maps to Azure VPN Gateway BGP settings; configure bgp_settings block manually`,
      ),
    );
  }

  return { translated, findings };
}

function translateVpnGatewayToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/vpn-gateway', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const gcpAttrs: Record<string, unknown> = {
    name: resource.sourceName,
    network: '${google_compute_network.main.id}',
    region: '${var.region}',
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_vpn_gateway',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_VPN_GATEWAY),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'VPN_DUAL_TUNNEL_HA',
      'AWS dual tunnels may require manual HA setup; use google_compute_ha_vpn_gateway for high availability',
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// aws_vpn_connection
// ---------------------------------------------------------------------------

function translateVpnConnectionToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/vpn-connection', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const azureAttrs: Record<string, unknown> = {
    connection_protocol: 'IKEv2',
    local_network_gateway_id: '${azurerm_local_network_gateway.main.id}',
    location: '${azurerm_resource_group.main.location}',
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    // NFR-SEC-001: pre-shared key NEVER literal
    shared_key: '${var.vpn_psk}',
    type: 'IPsec',
    virtual_network_gateway_id: '${azurerm_virtual_network_gateway.main.id}',
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_virtual_network_gateway_connection',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_VPN_CONNECTION),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'VPN_PSK_PLACEHOLDER',
      'Pre-shared key is not included in translated output (NFR-SEC-001); set ${var.vpn_psk} via secure variable injection',
    ),
    createFinding(
      resource.id,
      'warning',
      'VPN_DUAL_TUNNEL_HA',
      'AWS dual tunnels may require manual HA setup; Azure supports active-active VPN Gateway configuration',
    ),
  ];

  if (isIkev1Only(attrs)) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'VPN_IKE_VERSION',
        'Source VPN connection uses IKEv1; Azure VPN Gateway connection_protocol defaults to IKEv2 — verify compatibility',
      ),
    );
  }

  return { translated, findings };
}

function translateVpnConnectionToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/vpn-connection', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const gcpAttrs: Record<string, unknown> = {
    ike_version: 2,
    name: resource.sourceName,
    peer_ip: '${google_compute_external_vpn_gateway.main.id}',
    region: '${var.region}',
    router: '${google_compute_router.main.id}',
    // NFR-SEC-001: pre-shared key NEVER literal
    shared_secret: '${var.vpn_psk}',
    target_vpn_gateway: '${google_compute_vpn_gateway.main.id}',
    vpn_gateway_interface: 0,
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_vpn_tunnel',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_VPN_CONNECTION),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'VPN_PSK_PLACEHOLDER',
      'Pre-shared key is not included in translated output (NFR-SEC-001); set ${var.vpn_psk} via secure variable injection',
    ),
    createFinding(
      resource.id,
      'warning',
      'VPN_DUAL_TUNNEL_HA',
      'AWS dual tunnels may require manual HA setup; create a second google_compute_vpn_tunnel on interface 1 for HA',
    ),
  ];

  if (isIkev1Only(attrs)) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'VPN_IKE_VERSION',
        'Source VPN connection uses IKEv1; GCP Cloud VPN tunnel ike_version set to 2 — verify compatibility',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// aws_customer_gateway
// ---------------------------------------------------------------------------

function translateCustomerGatewayToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/customer-gateway', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const ipAddress = (attrs['ip_address'] as string | undefined) ?? '${var.customer_gateway_ip}';
  const bgpAsn = attrs['bgp_asn'];

  const azureAttrs: Record<string, unknown> = {
    ip_address: ipAddress,
    location: '${azurerm_resource_group.main.location}',
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
  };

  if (bgpAsn !== undefined) {
    azureAttrs['bgp_settings'] = {
      asn: Number(bgpAsn),
      bgp_peering_address: '${var.customer_bgp_peering_address}',
    };
  }

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_local_network_gateway',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_CUSTOMER_GATEWAY),
    ...emitBehavioralGapFindings(ctx),
  ];

  if (bgpAsn !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'VPN_BGP_ASN',
        `Customer gateway BGP ASN (${bgpAsn}) mapped to azurerm_local_network_gateway bgp_settings.asn`,
      ),
    );
  }

  return { translated, findings };
}

function translateCustomerGatewayToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'parametric/customer-gateway', 'parametric');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const ipAddress = (attrs['ip_address'] as string | undefined) ?? '${var.customer_gateway_ip}';

  const gcpAttrs: Record<string, unknown> = {
    interfaces: [{ id: 0, ip_address: ipAddress }],
    name: resource.sourceName,
    redundancy_type: 'SINGLE_IP_INTERNALLY_REDUNDANT',
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_external_vpn_gateway',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS_CUSTOMER_GATEWAY),
    ...emitBehavioralGapFindings(ctx),
  ];

  const bgpAsn = attrs['bgp_asn'];
  if (bgpAsn !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'VPN_BGP_ASN',
        `Customer gateway BGP ASN (${bgpAsn}) must be configured in the Cloud Router BGP peer settings`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/**
 * Translates an aws_vpn_gateway to Azure azurerm_virtual_network_gateway (type=Vpn)
 * or GCP google_compute_vpn_gateway.
 */
export function translateVpnGateway(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateVpnGatewayToAzure(ctx);
  }
  return translateVpnGatewayToGcp(ctx);
}

/**
 * Translates an aws_vpn_connection to Azure azurerm_virtual_network_gateway_connection
 * or GCP google_compute_vpn_tunnel.
 *
 * Security: PSK values (tunnel1_preshared_key, tunnel2_preshared_key) are NEVER
 * included in translated attributes (NFR-SEC-001). A ${var.vpn_psk} placeholder is used.
 */
export function translateVpnConnection(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateVpnConnectionToAzure(ctx);
  }
  return translateVpnConnectionToGcp(ctx);
}

/**
 * Translates an aws_customer_gateway to Azure azurerm_local_network_gateway
 * or GCP google_compute_external_vpn_gateway.
 */
export function translateCustomerGateway(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateCustomerGatewayToAzure(ctx);
  }
  return translateCustomerGatewayToGcp(ctx);
}
