/**
 * Zod schemas for cloud-agnostic portable resource types.
 *
 * The `cloud_*` provider concept lets users describe infrastructure in
 * cloud-neutral terms; the portable compiler then emits native target
 * resources for the chosen provider (AWS / Azure / GCP).
 *
 * Supported portable resources
 *   - cloud_object_storage    — blob / object storage bucket
 *   - cloud_container_registry — private container image registry
 *   - cloud_cache_redis        — managed Redis-compatible cache
 *
 * @module types/portable-provider
 * @generated by code-generator (TASK-MCP-006)
 */

import { z } from 'zod';
import { CloudProvider } from '../constants.js';

// ---------------------------------------------------------------------------
// Shared sub-schemas
// ---------------------------------------------------------------------------

/**
 * Common encryption configuration used by portable resources.
 */
export const PortableEncryptionSchema = z.object({
  /**
   * Enable at-rest encryption (default: true when present).
   */
  enabled: z.boolean().default(true),
  /**
   * Optional provider-specific KMS/CMK key reference.
   * When provided, the compiler maps this to the appropriate CMK
   * parameter for the target provider.
   */
  kms_key_ref: z.string().optional(),
});
export type PortableEncryption = z.infer<typeof PortableEncryptionSchema>;

// ---------------------------------------------------------------------------
// cloud_object_storage
// ---------------------------------------------------------------------------

/**
 * Cloud-neutral object / blob storage bucket.
 *
 * Target mappings:
 *   aws   → aws_s3_bucket
 *   azure → azurerm_storage_account + azurerm_storage_container
 *   gcp   → google_storage_bucket
 */
export const CloudObjectStorageSchema = z.object({
  /** Discriminant for the PortableResource union. */
  resource_type: z.literal('cloud_object_storage'),
  /**
   * Logical name of the storage resource (used as the Terraform resource name
   * and as the basis for provider-specific identifiers).
   */
  name: z.string().min(1),
  /**
   * Optional versioning — keeps previous versions of objects.
   */
  versioning_enabled: z.boolean().optional(),
  /**
   * At-rest encryption configuration.
   */
  encryption: PortableEncryptionSchema.optional(),
  /**
   * Arbitrary provider-agnostic tags / labels.
   */
  tags: z.record(z.string(), z.string()).optional(),
  /**
   * Target cloud provider override. When omitted the compiler uses the
   * global target passed at runtime.
   */
  target_provider: CloudProvider.optional(),
  /**
   * Provider-specific attribute overrides applied after compilation.
   * Keys are provider names ('azure', 'gcp'); values are free-form attribute
   * maps that are shallow-merged onto each translated resource's attributes.
   * Use this to inject provider-specific fields not expressible in the
   * portable schema (e.g. Azure resource_group_name, GCP project).
   */
  provider_overrides: z.object({
    azure: z.record(z.string(), z.unknown()).optional(),
    gcp: z.record(z.string(), z.unknown()).optional(),
  }).optional(),
});
export type CloudObjectStorage = z.infer<typeof CloudObjectStorageSchema>;

// ---------------------------------------------------------------------------
// cloud_container_registry
// ---------------------------------------------------------------------------

/**
 * Cloud-neutral private container image registry.
 *
 * Target mappings:
 *   aws   → aws_ecr_repository
 *   azure → azurerm_container_registry
 *   gcp   → google_artifact_registry_repository
 */
export const CloudContainerRegistrySchema = z.object({
  /** Discriminant for the PortableResource union. */
  resource_type: z.literal('cloud_container_registry'),
  /**
   * Logical name of the registry resource.
   */
  name: z.string().min(1),
  /**
   * When true, image tags cannot be overwritten after being pushed.
   * Maps to IMMUTABLE mutability on AWS, and equivalent settings on Azure/GCP.
   */
  immutable_tags: z.boolean().optional(),
  /**
   * Enable vulnerability scanning on image push.
   */
  scan_on_push: z.boolean().optional(),
  /**
   * At-rest encryption configuration (CMK).
   */
  encryption: PortableEncryptionSchema.optional(),
  /**
   * Arbitrary provider-agnostic tags / labels.
   */
  tags: z.record(z.string(), z.string()).optional(),
  /**
   * Target cloud provider override.
   */
  target_provider: CloudProvider.optional(),
  /**
   * Provider-specific attribute overrides applied after compilation.
   * Shallow-merged onto each translated resource's attributes for the
   * matching target provider.
   */
  provider_overrides: z.object({
    azure: z.record(z.string(), z.unknown()).optional(),
    gcp: z.record(z.string(), z.unknown()).optional(),
  }).optional(),
});
export type CloudContainerRegistry = z.infer<typeof CloudContainerRegistrySchema>;

// ---------------------------------------------------------------------------
// cloud_cache_redis
// ---------------------------------------------------------------------------

/**
 * T-shirt sizes for the Redis cache, provider-independent.
 * Compiler maps these to node types / SKU tiers.
 */
export const RedisCacheSizeSchema = z.enum([
  'xs',   // ~1 GB
  'sm',   // ~2-4 GB
  'md',   // ~8-16 GB
  'lg',   // ~26-32 GB
  'xl',   // ~58 GB +
]);
export type RedisCacheSize = z.infer<typeof RedisCacheSizeSchema>;

/**
 * Cloud-neutral Redis-compatible managed cache.
 *
 * Target mappings:
 *   aws   → aws_elasticache_replication_group
 *   azure → azurerm_redis_cache
 *   gcp   → google_redis_instance
 */
export const CloudCacheRedisSchema = z.object({
  /** Discriminant for the PortableResource union. */
  resource_type: z.literal('cloud_cache_redis'),
  /**
   * Logical name of the cache resource.
   */
  name: z.string().min(1),
  /**
   * T-shirt size for the cache instance.
   * When omitted the compiler defaults to 'sm'.
   */
  size: RedisCacheSizeSchema.optional(),
  /**
   * Redis major version string (e.g. "6", "7").
   * Defaults to "6" when not specified.
   */
  engine_version: z.string().optional(),
  /**
   * Number of replicas (in addition to the primary node).
   * 0 = no replicas; defaults to 0.
   */
  replicas: z.number().int().nonnegative().optional(),
  /**
   * Enable TLS / transit encryption.
   */
  transit_encryption: z.boolean().optional(),
  /**
   * At-rest encryption configuration.
   */
  encryption: PortableEncryptionSchema.optional(),
  /**
   * Arbitrary provider-agnostic tags / labels.
   */
  tags: z.record(z.string(), z.string()).optional(),
  /**
   * Target cloud provider override.
   */
  target_provider: CloudProvider.optional(),
  /**
   * Provider-specific attribute overrides applied after compilation.
   * Shallow-merged onto each translated resource's attributes for the
   * matching target provider.
   */
  provider_overrides: z.object({
    azure: z.record(z.string(), z.unknown()).optional(),
    gcp: z.record(z.string(), z.unknown()).optional(),
  }).optional(),
});
export type CloudCacheRedis = z.infer<typeof CloudCacheRedisSchema>;

// ---------------------------------------------------------------------------
// PortableResource — discriminated union
// ---------------------------------------------------------------------------

/**
 * Discriminated union of all supported portable resources.
 * Use `resource_type` to narrow to a specific variant.
 */
export const PortableResourceSchema = z.discriminatedUnion('resource_type', [
  CloudObjectStorageSchema,
  CloudContainerRegistrySchema,
  CloudCacheRedisSchema,
]);
export type PortableResource = z.infer<typeof PortableResourceSchema>;
