/**
 * AWS CloudWatch -> Azure Monitor / GCP Cloud Monitoring translation.
 *
 * Metric Alarm: Azure monitor_metric_alert / GCP monitoring_alert_policy.
 * Log Group:    Azure log_analytics_workspace / GCP logging_project_bucket_config.
 *
 * @module structural/cloudwatch-mapping
 * @generated by code-generator (TASK-TRANS-005)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Metric name mapping
// ---------------------------------------------------------------------------

const METRIC_NAME_MAP: ReadonlyMap<string, { azure: string; gcp: string }> = new Map([
  ['CPUUtilization', { azure: 'Percentage CPU', gcp: 'compute.googleapis.com/instance/cpu/utilization' }],
  ['MemoryUtilization', { azure: 'Available Memory Bytes', gcp: 'compute.googleapis.com/instance/memory/balloon/ram_used' }],
  ['NetworkIn', { azure: 'Network In Total', gcp: 'compute.googleapis.com/instance/network/received_bytes_count' }],
  ['NetworkOut', { azure: 'Network Out Total', gcp: 'compute.googleapis.com/instance/network/sent_bytes_count' }],
  ['DiskReadOps', { azure: 'Disk Read Operations/Sec', gcp: 'compute.googleapis.com/instance/disk/read_ops_count' }],
  ['DiskWriteOps', { azure: 'Disk Write Operations/Sec', gcp: 'compute.googleapis.com/instance/disk/write_ops_count' }],
  ['StatusCheckFailed', { azure: 'VM Availability Metric', gcp: 'compute.googleapis.com/instance/uptime' }],
  ['DatabaseConnections', { azure: 'active_connections', gcp: 'cloudsql.googleapis.com/database/network/connections' }],
  ['FreeableMemory', { azure: 'memory_percent', gcp: 'cloudsql.googleapis.com/database/memory/utilization' }],
  ['ReadLatency', { azure: 'io_consumption_percent', gcp: 'cloudsql.googleapis.com/database/disk/read_ops_count' }],
]);

// ---------------------------------------------------------------------------
// Comparison operator mapping
// ---------------------------------------------------------------------------

const COMPARISON_MAP_AZURE: ReadonlyMap<string, string> = new Map([
  ['GreaterThanOrEqualToThreshold', 'GreaterThanOrEqual'],
  ['GreaterThanThreshold', 'GreaterThan'],
  ['LessThanOrEqualToThreshold', 'LessThanOrEqual'],
  ['LessThanThreshold', 'LessThan'],
]);

const COMPARISON_MAP_GCP: ReadonlyMap<string, string> = new Map([
  ['GreaterThanOrEqualToThreshold', 'COMPARISON_GE'],
  ['GreaterThanThreshold', 'COMPARISON_GT'],
  ['LessThanOrEqualToThreshold', 'COMPARISON_LE'],
  ['LessThanThreshold', 'COMPARISON_LT'],
]);

// ---------------------------------------------------------------------------
// Alarm: mapped keys
// ---------------------------------------------------------------------------

const ALARM_MAPPED_KEYS: readonly string[] = [
  'alarm_actions',
  'alarm_description',
  'alarm_name',
  'comparison_operator',
  'evaluation_periods',
  'metric_name',
  'namespace',
  'period',
  'statistic',
  'tags',
  'threshold',
];

// ---------------------------------------------------------------------------
// Alarm -> Azure (monitor_metric_alert)
// ---------------------------------------------------------------------------

function translateAlarmToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/cloudwatch-alarm', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const alarmName = (attrs['alarm_name'] as string | undefined) ?? sourceName;
  const metricName = (attrs['metric_name'] as string | undefined) ?? 'CPUUtilization';
  const metricEntry = METRIC_NAME_MAP.get(metricName);
  const azureMetric = metricEntry?.azure ?? metricName;
  const comparison = (attrs['comparison_operator'] as string | undefined) ?? 'GreaterThanOrEqualToThreshold';
  const threshold = (attrs['threshold'] as number | undefined) ?? 80;
  const period = (attrs['period'] as number | undefined) ?? 300;
  const evalPeriods = (attrs['evaluation_periods'] as number | undefined) ?? 1;
  const statistic = (attrs['statistic'] as string | undefined) ?? 'Average';

  const alertAttrs: Record<string, unknown> = {
    criteria: {
      aggregation: statistic,
      metric_name: azureMetric,
      metric_namespace: 'Microsoft.Compute/virtualMachines',
      operator: COMPARISON_MAP_AZURE.get(comparison) ?? 'GreaterThanOrEqual',
      threshold,
    },
    description: (attrs['alarm_description'] as string | undefined) ?? '',
    frequency: `PT${Math.max(1, Math.floor(period / 60))}M`,
    name: alarmName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    scopes: ['${azurerm_linux_virtual_machine.main.id}'],
    severity: 2,
    window_size: `PT${Math.max(1, Math.floor((period * evalPeriods) / 60))}M`,
  };
  if (tags) alertAttrs['tags'] = transformTags('azure', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_monitor_metric_alert',
      targetName: sourceName,
      attributes: alertAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, ALARM_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_cloudwatch_metric_alarm -> 1 azure resource (monitor_metric_alert)`,
    ),
  ];

  if (!metricEntry) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'UNKNOWN_METRIC',
        `Metric '${metricName}' has no known Azure mapping; using name as-is`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Alarm -> GCP (monitoring_alert_policy)
// ---------------------------------------------------------------------------

function translateAlarmToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/cloudwatch-alarm', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const alarmName = (attrs['alarm_name'] as string | undefined) ?? sourceName;
  const metricName = (attrs['metric_name'] as string | undefined) ?? 'CPUUtilization';
  const metricEntry = METRIC_NAME_MAP.get(metricName);
  const gcpMetric = metricEntry?.gcp ?? `custom.googleapis.com/${metricName}`;
  const comparison = (attrs['comparison_operator'] as string | undefined) ?? 'GreaterThanOrEqualToThreshold';
  const threshold = (attrs['threshold'] as number | undefined) ?? 80;
  const period = (attrs['period'] as number | undefined) ?? 300;
  const statistic = ((attrs['statistic'] as string | undefined) ?? 'Average').toUpperCase();

  const alertAttrs: Record<string, unknown> = {
    combiner: 'OR',
    conditions: [
      {
        condition_threshold: {
          aggregations: [{
            alignment_period: `${period}s`,
            per_series_aligner: `ALIGN_${statistic === 'SUM' ? 'SUM' : 'MEAN'}`,
          }],
          comparison: COMPARISON_MAP_GCP.get(comparison) ?? 'COMPARISON_GE',
          filter: `metric.type="${gcpMetric}"`,
          threshold_value: threshold,
        },
        display_name: alarmName,
      },
    ],
    display_name: alarmName,
  };
  if (tags) alertAttrs['user_labels'] = transformTags('gcp', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_monitoring_alert_policy',
      targetName: sourceName,
      attributes: alertAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, ALARM_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_cloudwatch_metric_alarm -> 1 gcp resource (monitoring_alert_policy)`,
    ),
  ];

  if (!metricEntry) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'UNKNOWN_METRIC',
        `Metric '${metricName}' has no known GCP mapping; using custom metric type`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Logs: mapped keys
// ---------------------------------------------------------------------------

const LOGS_MAPPED_KEYS: readonly string[] = [
  'kms_key_id',
  'name',
  'retention_in_days',
  'tags',
];

// ---------------------------------------------------------------------------
// Log Group -> Azure (log_analytics_workspace)
// ---------------------------------------------------------------------------

function translateLogsToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/cloudwatch-logs', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const retention = (attrs['retention_in_days'] as number | undefined) ?? 30;
  const name = (attrs['name'] as string | undefined) ?? sourceName;

  const wsAttrs: Record<string, unknown> = {
    location: '${azurerm_resource_group.main.location}',
    name,
    resource_group_name: '${azurerm_resource_group.main.name}',
    retention_in_days: retention,
    sku: 'PerGB2018',
  };
  if (tags) wsAttrs['tags'] = transformTags('azure', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_log_analytics_workspace',
      targetName: sourceName,
      attributes: wsAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, LOGS_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_cloudwatch_log_group -> 1 azure resource (log_analytics_workspace)`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Log Group -> GCP (logging_project_bucket_config)
// ---------------------------------------------------------------------------

function translateLogsToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/cloudwatch-logs', 'structural');
  const sourceName = resource.sourceName;

  const retention = (attrs['retention_in_days'] as number | undefined) ?? 30;
  const name = (attrs['name'] as string | undefined) ?? sourceName;

  const bucketAttrs: Record<string, unknown> = {
    bucket_id: name,
    location: 'global',
    project: '${var.project_id}',
    retention_days: retention,
  };

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_logging_project_bucket_config',
      targetName: sourceName,
      attributes: bucketAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, LOGS_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_cloudwatch_log_group -> 1 gcp resource (logging_project_bucket_config)`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/**
 * Translates an aws_cloudwatch_metric_alarm to Azure Monitor or GCP Monitoring.
 */
export function translateCloudwatchAlarm(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateAlarmToAzure(ctx);
  }
  return translateAlarmToGcp(ctx);
}

/**
 * Translates an aws_cloudwatch_log_group to Azure Log Analytics or GCP Logging.
 */
export function translateCloudwatchLogs(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateLogsToAzure(ctx);
  }
  return translateLogsToGcp(ctx);
}
