/**
 * AWS VPC DHCP Options -> Azure / GCP translation.
 * Azure: DHCP is absorbed into VNet config — no separate resource emitted.
 * GCP: custom DNS servers -> google_dns_policy; otherwise no resource.
 *
 * @module structural/dhcp-options-mapping
 * @generated by code-generator (TASK-NET-001)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'domain_name',
  'domain_name_servers',
  'netbios_name_servers',
  'netbios_node_type',
  'ntp_servers',
  'tags',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_vpc_dhcp_options -> 0 azure resources (DHCP absorbed into VNet)',
    ),
    createFinding(
      resource.id,
      'info',
      'DHCP_ABSORBED_INTO_VNET',
      'Azure VNet manages DNS settings natively via dns_servers attribute; no separate DHCP resource needed',
    ),
  ];

  // NTP advisory
  const ntpServers = attrs['ntp_servers'] as readonly string[] | undefined;
  if (Array.isArray(ntpServers) && ntpServers.length > 0) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DHCP_NTP_UNSUPPORTED',
        'Custom NTP servers are not configurable in Azure VNet DHCP; instances use Azure-provided NTP by default',
      ),
    );
  }

  // NetBIOS advisory
  const netbiosServers = attrs['netbios_name_servers'] as readonly string[] | undefined;
  const netbiosNodeType = attrs['netbios_node_type'] as string | undefined;
  if ((Array.isArray(netbiosServers) && netbiosServers.length > 0) || netbiosNodeType) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DHCP_NETBIOS_UNSUPPORTED',
        'NetBIOS settings are not configurable in Azure VNet DHCP; manual configuration required on instances',
      ),
    );
  }

  return { translated: [], findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/dhcp-options', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const dnsServers = attrs['domain_name_servers'] as readonly string[] | undefined;
  const hasCustomDns =
    Array.isArray(dnsServers) &&
    dnsServers.length > 0 &&
    !(dnsServers.length === 1 && dnsServers[0] === 'AmazonProvidedDNS');

  const translated: TranslatedResource[] = [];
  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  if (hasCustomDns) {
    // Filter out AmazonProvidedDNS entries — only real IPs go into target servers
    const customIps = (dnsServers as readonly string[]).filter(
      (ip) => ip !== 'AmazonProvidedDNS',
    );
    // Emit a google_dns_policy for custom DNS servers
    const policyAttrs: Record<string, unknown> = {
      enable_inbound_forwarding: true,
      name: `${resource.sourceName}-dns-policy`,
      alternative_name_server_config: {
        target_name_servers: customIps.map((ip) => ({
          ipv4_address: ip,
        })),
      },
    };
    if (tags) {
      policyAttrs['labels'] = transformTags('gcp', tags);
    }

    translated.push({
      targetType: 'google_dns_policy',
      targetName: `${resource.sourceName}_dns_policy`,
      attributes: policyAttrs,
      sourceId: resource.id,
      traceability,
    });

    findings.push(
      createFinding(
        resource.id,
        'info',
        'STRUCTURAL_TOPOLOGY',
        '1 aws_vpc_dhcp_options -> 1 google_dns_policy (custom DNS servers)',
      ),
    );
  } else {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'STRUCTURAL_TOPOLOGY',
        '1 aws_vpc_dhcp_options -> 0 gcp resources (default DNS used)',
      ),
    );
  }

  // NTP advisory
  const ntpServers = attrs['ntp_servers'] as readonly string[] | undefined;
  if (Array.isArray(ntpServers) && ntpServers.length > 0) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DHCP_NTP_UNSUPPORTED',
        'Custom NTP servers are not configurable in GCP VPC; instances use Google-provided NTP by default',
      ),
    );
  }

  // NetBIOS advisory
  const netbiosServers = attrs['netbios_name_servers'] as readonly string[] | undefined;
  const netbiosNodeType = attrs['netbios_node_type'] as string | undefined;
  if ((Array.isArray(netbiosServers) && netbiosServers.length > 0) || netbiosNodeType) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DHCP_NETBIOS_UNSUPPORTED',
        'NetBIOS settings are not configurable in GCP VPC; manual configuration required on instances',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates aws_vpc_dhcp_options to Azure (absorbed into VNet) or GCP
 * (google_dns_policy for custom DNS servers).
 */
export function translateDhcpOptions(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
