/**
 * Route53 Zone / Record -> Azure DNS / GCP Cloud DNS structural translation.
 *
 * Ported from direct/dns-mapping and enhanced with:
 * - Private zone detection (vpc attribute presence)
 * - Azure private DNS zone + virtual network link companion resource
 * - GCP private_visibility_config block for private zones
 * - Routing policy advisory warnings
 * - Behavioral gap findings and structural topology info
 *
 * @module structural/dns-mapping
 * @generated by code-generator (TASK-NET-005)
 */

import type { TranslatedResource, TranslationFinding } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Mapped keys
// ---------------------------------------------------------------------------

const ZONE_MAPPED_KEYS: readonly string[] = [
  'comment',
  'force_destroy',
  'name',
  'tags',
  'vpc',
];

const RECORD_MAPPED_KEYS: readonly string[] = [
  'alias',
  'failover_routing_policy',
  'health_check_id',
  'name',
  'records',
  'set_identifier',
  'ttl',
  'type',
  'weighted_routing_policy',
  'zone_id',
];

// ---------------------------------------------------------------------------
// Azure record type maps (public & private)
// ---------------------------------------------------------------------------

const AZURE_RECORD_TYPE_MAP: ReadonlyMap<string, string> = new Map([
  ['A', 'azurerm_dns_a_record'],
  ['AAAA', 'azurerm_dns_aaaa_record'],
  ['CAA', 'azurerm_dns_caa_record'],
  ['CNAME', 'azurerm_dns_cname_record'],
  ['MX', 'azurerm_dns_mx_record'],
  ['NS', 'azurerm_dns_ns_record'],
  ['PTR', 'azurerm_dns_ptr_record'],
  ['SRV', 'azurerm_dns_srv_record'],
  ['TXT', 'azurerm_dns_txt_record'],
]);

const AZURE_PRIVATE_RECORD_TYPE_MAP: ReadonlyMap<string, string> = new Map([
  ['A', 'azurerm_private_dns_a_record'],
  ['AAAA', 'azurerm_private_dns_aaaa_record'],
  ['CNAME', 'azurerm_private_dns_cname_record'],
  ['MX', 'azurerm_private_dns_mx_record'],
  ['NS', 'azurerm_private_dns_ns_record'],
  ['SRV', 'azurerm_private_dns_srv_record'],
  ['TXT', 'azurerm_private_dns_txt_record'],
]);

// ---------------------------------------------------------------------------
// Routing policy advisory
// ---------------------------------------------------------------------------

const DNS_ROUTING_POLICY_ADVISORY =
  'Route53 routing policies (weighted, failover, latency, geolocation) have no direct equivalent; ' +
  'Azure Traffic Manager or GCP Cloud DNS routing policies require manual reconfiguration';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Detects whether an aws_route53_zone is private based on vpc attribute presence.
 */
function isPrivateZone(attrs: Record<string, unknown>): boolean {
  const vpc = attrs['vpc'];
  return vpc !== undefined && vpc !== null;
}

/**
 * Checks whether routing policy attributes are present and returns a warning finding.
 */
function checkRoutingPolicy(
  resourceId: string,
  attrs: Record<string, unknown>,
): TranslationFinding | undefined {
  const hasWeighted = attrs['weighted_routing_policy'] !== undefined;
  const hasFailover = attrs['failover_routing_policy'] !== undefined;
  if (hasWeighted || hasFailover) {
    return createFinding(
      resourceId,
      'warning',
      'DNS_ROUTING_POLICY_ADVISORY',
      DNS_ROUTING_POLICY_ADVISORY,
    );
  }
  return undefined;
}

// ---------------------------------------------------------------------------
// Zone translation - Azure
// ---------------------------------------------------------------------------

function translateZoneToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/dns', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;
  const privateZone = isPrivateZone(attrs);

  const translated: TranslatedResource[] = [];
  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, ZONE_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  if (privateZone) {
    // Azure private DNS zone
    const azureAttrs: Record<string, unknown> = {
      name: attrs['name'] ?? resource.sourceName,
      resource_group_name: '${azurerm_resource_group.main.name}',
    };
    if (tags) {
      azureAttrs['tags'] = transformTags('azure', tags);
    }

    translated.push({
      targetType: 'azurerm_private_dns_zone',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    });

    // Companion virtual network link
    const linkAttrs: Record<string, unknown> = {
      name: `${resource.sourceName}-vnet-link`,
      private_dns_zone_name:
        '${azurerm_private_dns_zone.' + resource.sourceName + '.name}',
      resource_group_name: '${azurerm_resource_group.main.name}',
      virtual_network_id: '${azurerm_virtual_network.main.id}',
    };
    if (tags) {
      linkAttrs['tags'] = transformTags('azure', tags);
    }

    translated.push({
      targetType: 'azurerm_private_dns_zone_virtual_network_link',
      targetName: `${resource.sourceName}_vnet_link`,
      attributes: linkAttrs,
      sourceId: resource.id,
      traceability,
    });

    findings.push(
      createFinding(
        resource.id,
        'info',
        'STRUCTURAL_TOPOLOGY',
        '1 aws_route53_zone (private) -> 1 azurerm_private_dns_zone + 1 azurerm_private_dns_zone_virtual_network_link',
      ),
    );
  } else {
    // Public DNS zone
    const azureAttrs: Record<string, unknown> = {
      name: attrs['name'] ?? resource.sourceName,
      resource_group_name: '${azurerm_resource_group.main.name}',
    };
    if (tags) {
      azureAttrs['tags'] = transformTags('azure', tags);
    }

    translated.push({
      targetType: 'azurerm_dns_zone',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    });

    findings.push(
      createFinding(
        resource.id,
        'info',
        'STRUCTURAL_TOPOLOGY',
        '1 aws_route53_zone (public) -> 1 azurerm_dns_zone',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Zone translation - GCP
// ---------------------------------------------------------------------------

function translateZoneToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/dns', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;
  const privateZone = isPrivateZone(attrs);

  const zoneName = (attrs['name'] as string | undefined) ?? resource.sourceName;
  const gcpAttrs: Record<string, unknown> = {
    description: (attrs['comment'] as string | undefined) ?? '',
    dns_name: zoneName.endsWith('.') ? zoneName : `${zoneName}.`,
    name: resource.sourceName.replace(/[^a-z0-9-]/gi, '-').toLowerCase(),
  };

  if (privateZone) {
    gcpAttrs['visibility'] = 'private';
    gcpAttrs['private_visibility_config'] = {
      networks: [
        { network_url: '${google_compute_network.main.id}' },
      ],
    };
  }

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, ZONE_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  const topologyDetail = privateZone
    ? '1 aws_route53_zone (private) -> 1 google_dns_managed_zone (private_visibility_config)'
    : '1 aws_route53_zone (public) -> 1 google_dns_managed_zone';

  findings.push(
    createFinding(resource.id, 'info', 'STRUCTURAL_TOPOLOGY', topologyDetail),
  );

  return {
    translated: [
      {
        targetType: 'google_dns_managed_zone',
        targetName: resource.sourceName,
        attributes: gcpAttrs,
        sourceId: resource.id,
        traceability,
      },
    ],
    findings,
  };
}

// ---------------------------------------------------------------------------
// Record translation - Azure
// ---------------------------------------------------------------------------

function translateRecordToAzure(ctx: TranslationContext): EngineResult {
  const { resource, ir } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/dns', 'structural');
  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, RECORD_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  const recordType = (attrs['type'] as string | undefined) ?? 'A';
  const alias = attrs['alias'] as Record<string, unknown> | undefined;

  // Detect whether parent zone is private by scanning IR for the zone resource
  const zoneId = attrs['zone_id'] as string | undefined;
  const parentZonePrivate = detectParentZonePrivate(ir, zoneId);

  // Alias records are not directly portable
  if (alias) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DNS_ALIAS_NOT_PORTABLE',
        'Route53 alias records have no direct equivalent in Azure DNS; translated as CNAME',
      ),
    );
  }

  // Routing policy advisory
  const routingFinding = checkRoutingPolicy(resource.id, attrs);
  if (routingFinding) {
    findings.push(routingFinding);
  }

  const typeMap = parentZonePrivate
    ? AZURE_PRIVATE_RECORD_TYPE_MAP
    : AZURE_RECORD_TYPE_MAP;
  const defaultType = parentZonePrivate
    ? 'azurerm_private_dns_a_record'
    : 'azurerm_dns_a_record';

  const azureType = alias
    ? (parentZonePrivate ? 'azurerm_private_dns_cname_record' : 'azurerm_dns_cname_record')
    : typeMap.get(recordType) ?? defaultType;

  const zoneRef = parentZonePrivate
    ? '${azurerm_private_dns_zone.main.name}'
    : '${azurerm_dns_zone.main.name}';

  const azureAttrs: Record<string, unknown> = {
    name: attrs['name'] ?? resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    ttl: attrs['ttl'] ?? 300,
    zone_name: zoneRef,
  };

  if (alias) {
    azureAttrs['record'] = alias['name'] ?? '';
  } else {
    const records = attrs['records'] as string[] | undefined;
    if (records) {
      azureAttrs['records'] = [...records].sort();
    }
  }

  const topologyTarget = parentZonePrivate ? 'azurerm_private_dns_*_record' : 'azurerm_dns_*_record';
  findings.push(
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_route53_record -> 1 ${topologyTarget} (type: ${recordType})`,
    ),
  );

  return {
    translated: [
      {
        targetType: azureType,
        targetName: resource.sourceName,
        attributes: azureAttrs,
        sourceId: resource.id,
        traceability,
      },
    ],
    findings,
  };
}

// ---------------------------------------------------------------------------
// Record translation - GCP
// ---------------------------------------------------------------------------

function translateRecordToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/dns', 'structural');
  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, RECORD_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  const recordType = (attrs['type'] as string | undefined) ?? 'A';
  const alias = attrs['alias'] as Record<string, unknown> | undefined;

  if (alias) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DNS_ALIAS_NOT_PORTABLE',
        'Route53 alias records have no direct equivalent in GCP Cloud DNS; translated as CNAME',
      ),
    );
  }

  // Routing policy advisory
  const routingFinding = checkRoutingPolicy(resource.id, attrs);
  if (routingFinding) {
    findings.push(routingFinding);
  }

  const gcpAttrs: Record<string, unknown> = {
    managed_zone: '${google_dns_managed_zone.main.name}',
    name: attrs['name'] ?? resource.sourceName,
    ttl: attrs['ttl'] ?? 300,
    type: alias ? 'CNAME' : recordType,
  };

  if (alias) {
    const aliasName = (alias['name'] as string) ?? '';
    gcpAttrs['rrdatas'] = [aliasName.endsWith('.') ? aliasName : `${aliasName}.`];
  } else {
    const records = attrs['records'] as string[] | undefined;
    if (records) {
      gcpAttrs['rrdatas'] = [...records].sort();
    }
  }

  const emittedType = alias ? 'CNAME' : recordType;
  findings.push(
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_route53_record -> 1 google_dns_record_set (type: ${emittedType})`,
    ),
  );

  return {
    translated: [
      {
        targetType: 'google_dns_record_set',
        targetName: resource.sourceName,
        attributes: gcpAttrs,
        sourceId: resource.id,
        traceability,
      },
    ],
    findings,
  };
}

// ---------------------------------------------------------------------------
// IR helpers
// ---------------------------------------------------------------------------

/**
 * Scans the IR for the parent Route53 zone to determine if it is private.
 * Returns true if the zone has a `vpc` attribute, false otherwise.
 */
function detectParentZonePrivate(
  ir: TranslationContext['ir'],
  zoneId: string | undefined,
): boolean {
  if (!zoneId) return false;
  for (const res of ir.resources) {
    if (res.sourceType !== 'aws_route53_zone') continue;
    // Match by resource id or by terraform interpolation reference
    if (res.id === zoneId || zoneId.includes(res.sourceName)) {
      const zoneAttrs = res.attributes as Record<string, unknown>;
      return isPrivateZone(zoneAttrs);
    }
  }
  return false;
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates aws_route53_zone or aws_route53_record to Azure or GCP equivalents.
 *
 * Structural mapper: detects private vs public zones, emits companion resources
 * (Azure VNet link), routing policy advisories, and behavioral gap findings.
 */
export function translateDns(ctx: TranslationContext): EngineResult {
  const isZone = ctx.resource.sourceType === 'aws_route53_zone';

  if (ctx.targetProvider === 'azure') {
    return isZone ? translateZoneToAzure(ctx) : translateRecordToAzure(ctx);
  }
  return isZone ? translateZoneToGcp(ctx) : translateRecordToGcp(ctx);
}
