/**
 * AWS ECS Service -> Azure Container Apps / GCP Cloud Run (Fargate)
 * or Azure AKS / GCP GKE (EC2 launch type) translation.
 *
 * FARGATE (default): Azure container_app_environment + container_app /
 *                    GCP cloud_run_v2_service.
 * EC2 launch type:   Azure kubernetes_cluster / GCP container_cluster.
 *
 * @module structural/ecs-mapping
 * @generated by code-generator (TASK-TRANS-005)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'cluster',
  'desired_count',
  'launch_type',
  'network_configuration',
  'tags',
  'task_definition',
];

// ---------------------------------------------------------------------------
// Fargate -> Azure (container_app_environment + container_app)
// ---------------------------------------------------------------------------

function translateFargateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/ecs-fargate', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const desiredCount = (attrs['desired_count'] as number | undefined) ?? 1;

  const translated: TranslatedResource[] = [];

  // 1. Container App Environment
  const envAttrs: Record<string, unknown> = {
    location: '${azurerm_resource_group.main.location}',
    name: `${sourceName}-env`,
    resource_group_name: '${azurerm_resource_group.main.name}',
  };
  if (tags) envAttrs['tags'] = transformTags('azure', tags);

  translated.push({
    targetType: 'azurerm_container_app_environment',
    targetName: `${sourceName}_env`,
    attributes: envAttrs,
    sourceId: resource.id,
    traceability,
  });

  // 2. Container App
  const appAttrs: Record<string, unknown> = {
    container_app_environment_id: `\${azurerm_container_app_environment.${sourceName}_env.id}`,
    name: sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    revision_mode: 'Single',
    template: {
      container: {
        cpu: 0.25,
        image: '${var.container_image}',
        memory: '0.5Gi',
        name: sourceName,
      },
      max_replicas: desiredCount * 2,
      min_replicas: desiredCount,
    },
  };
  if (tags) appAttrs['tags'] = transformTags('azure', tags);

  translated.push({
    targetType: 'azurerm_container_app',
    targetName: sourceName,
    attributes: appAttrs,
    sourceId: resource.id,
    traceability,
  });

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_ecs_service (Fargate) -> 2 azure resources (environment + container_app)`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Fargate -> GCP (cloud_run_v2_service)
// ---------------------------------------------------------------------------

function translateFargateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/ecs-fargate', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const desiredCount = (attrs['desired_count'] as number | undefined) ?? 1;

  const runAttrs: Record<string, unknown> = {
    location: '${var.region}',
    name: sourceName,
    template: {
      containers: {
        image: '${var.container_image}',
      },
      scaling: {
        max_instance_count: desiredCount * 2,
        min_instance_count: desiredCount,
      },
    },
  };
  if (tags) runAttrs['labels'] = transformTags('gcp', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_cloud_run_v2_service',
      targetName: sourceName,
      attributes: runAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_ecs_service (Fargate) -> 1 gcp resource (cloud_run_v2_service)`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// EC2 launch type -> Azure AKS / GCP GKE
// ---------------------------------------------------------------------------

function translateEc2ToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/ecs-ec2', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const desiredCount = (attrs['desired_count'] as number | undefined) ?? 1;

  const aksAttrs: Record<string, unknown> = {
    default_node_pool: {
      name: 'default',
      node_count: desiredCount,
      vm_size: 'Standard_D2s_v5',
    },
    dns_prefix: sourceName,
    identity: {
      type: 'SystemAssigned',
    },
    location: '${azurerm_resource_group.main.location}',
    name: sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
  };
  if (tags) aksAttrs['tags'] = transformTags('azure', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_kubernetes_cluster',
      targetName: sourceName,
      attributes: aksAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_ecs_service (EC2) -> 1 azure resource (kubernetes_cluster)`,
    ),
  ];

  return { translated, findings };
}

function translateEc2ToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/ecs-ec2', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const desiredCount = (attrs['desired_count'] as number | undefined) ?? 1;

  const gkeAttrs: Record<string, unknown> = {
    initial_node_count: desiredCount,
    location: '${var.region}',
    name: sourceName,
    node_config: {
      machine_type: 'e2-standard-2',
    },
  };
  if (tags) gkeAttrs['labels'] = transformTags('gcp', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_container_cluster',
      targetName: sourceName,
      attributes: gkeAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_ecs_service (EC2) -> 1 gcp resource (container_cluster)`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_ecs_service to Azure or GCP equivalents.
 * Dispatches based on launch_type: FARGATE (default) vs EC2.
 */
export function translateEcs(ctx: TranslationContext): EngineResult {
  const attrs = ctx.resource.attributes as Record<string, unknown>;
  const launchType = ((attrs['launch_type'] as string | undefined) ?? 'FARGATE').toUpperCase();

  if (launchType === 'EC2') {
    return ctx.targetProvider === 'azure'
      ? translateEc2ToAzure(ctx)
      : translateEc2ToGcp(ctx);
  }

  // Default: FARGATE
  return ctx.targetProvider === 'azure'
    ? translateFargateToAzure(ctx)
    : translateFargateToGcp(ctx);
}
