/**
 * AWS VPC Flow Log -> Azure Network Watcher Flow Log / GCP (per-subnet) translation.
 * Azure: azurerm_network_watcher_flow_log with storage + retention config.
 * GCP: VPC flow logs are per-subnet, not per-VPC — advisory only.
 *
 * @module structural/flow-log-mapping
 * @generated by code-generator (TASK-NET-001)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
  findSiblingVpc,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'iam_role_arn',
  'log_destination',
  'log_destination_type',
  'max_aggregation_interval',
  'tags',
  'traffic_type',
  'vpc_id',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/flow-log', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const vpcRef = findSiblingVpc(ctx);
  const nsgRef = vpcRef
    ? `\${azurerm_network_security_group.${vpcRef.sourceName}.id}`
    : '${azurerm_network_security_group.main.id}';

  const logDestination = attrs['log_destination'] as string | undefined;
  const maxAggregation = attrs['max_aggregation_interval'] as number | undefined;

  const azureAttrs: Record<string, unknown> = {
    enabled: true,
    name: resource.sourceName,
    network_security_group_id: nsgRef,
    network_watcher_name: '${azurerm_network_watcher.main.name}',
    resource_group_name: '${azurerm_resource_group.main.name}',
    storage_account_id: logDestination ?? '${azurerm_storage_account.flow_logs.id}',
    retention_policy: {
      enabled: true,
      days: 90,
    },
  };

  // Map aggregation interval
  if (typeof maxAggregation === 'number') {
    azureAttrs['traffic_analytics'] = {
      enabled: true,
      workspace_region: '${azurerm_resource_group.main.location}',
      interval_in_minutes: maxAggregation <= 60 ? 1 : 10,
    };
  }

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_network_watcher_flow_log',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_flow_log -> 1 azurerm_network_watcher_flow_log',
    ),
  ];

  // Missing log_destination advisory
  if (!logDestination) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'FLOW_LOG_DESTINATION_MISSING',
        'log_destination is missing; defaulting to placeholder storage account reference',
      ),
    );
  }

  // Validate traffic_type
  const trafficType = attrs['traffic_type'] as string | undefined;
  const VALID_TRAFFIC_TYPES = ['ALL', 'ACCEPT', 'REJECT'];
  if (trafficType && !VALID_TRAFFIC_TYPES.includes(trafficType.toUpperCase())) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'FLOW_LOG_TRAFFIC_TYPE_UNKNOWN',
        `Unrecognized traffic_type '${trafficType}'; expected one of ALL, ACCEPT, REJECT`,
      ),
    );
  }

  // IAM role advisory
  if (attrs['iam_role_arn']) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'FLOW_LOG_IAM_IGNORED',
        'iam_role_arn has no Azure equivalent; Azure uses managed identity or storage account keys',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_flow_log -> 0 gcp resources (flow logs configured per-subnet in GCP)',
    ),
    createFinding(
      resource.id,
      'warning',
      'FLOW_LOG_SUBNET_CONFIG',
      'GCP VPC flow logs are enabled per-subnet via log_config block on google_compute_subnetwork, not at VPC level; enable on each subnet manually',
    ),
  ];

  return { translated: [], findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_flow_log to Azure Network Watcher Flow Log or emits
 * advisory for GCP (flow logs are per-subnet in GCP).
 */
export function translateFlowLog(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
