/**
 * AWS Internet Gateway -> Azure / GCP translation.
 * Both providers: internet gateways are implicit — no separate resource emitted.
 * Azure: internet routing is built into VNet.
 * GCP: default-internet-gateway exists automatically per VPC.
 *
 * @module structural/internet-gateway-mapping
 * @generated by code-generator (TASK-NET-001)
 */

import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  collectUnmappedAttrs,
  createFinding,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'tags',
  'vpc_id',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_internet_gateway -> 0 azure resources (implicit in VNet)',
    ),
    createFinding(
      resource.id,
      'info',
      'IGW_IMPLICIT_AZURE',
      'Azure VNet provides internet connectivity natively; no separate internet gateway resource is needed',
    ),
  ];

  if (!attrs['vpc_id']) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'IGW_VPC_ID_MISSING',
        'vpc_id is missing; internet gateway cannot be associated with a specific VNet',
      ),
    );
  }

  return { translated: [], findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_internet_gateway -> 0 gcp resources (implicit default-internet-gateway)',
    ),
    createFinding(
      resource.id,
      'info',
      'IGW_IMPLICIT_GCP',
      'GCP VPC includes a default-internet-gateway automatically; no separate internet gateway resource is needed',
    ),
  ];

  if (!attrs['vpc_id']) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'IGW_VPC_ID_MISSING',
        'vpc_id is missing; internet gateway cannot be associated with a specific VPC network',
      ),
    );
  }

  return { translated: [], findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_internet_gateway. Both Azure and GCP have implicit
 * internet gateways, so no resources are emitted — only advisory findings.
 */
export function translateInternetGateway(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
