/**
 * AWS Lambda Function -> Azure Function App / GCP Cloud Functions translation.
 * Azure: 3 resources (Service Plan + Storage Account + Function App).
 * GCP: 1 resource (cloudfunctions2_function).
 *
 * Trigger detection: scans sibling resources for api_gateway (http),
 * sqs (queue), s3 (storage), otherwise unknown.
 *
 * @module structural/lambda-mapping
 * @generated by code-generator (TASK-TRANS-005)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,

  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,

} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'environment',
  'function_name',
  'handler',
  'layers',
  'memory_size',
  'runtime',
  'tags',
  'timeout',
  'vpc_config',
];

// ---------------------------------------------------------------------------
// Runtime mapping
// ---------------------------------------------------------------------------

const RUNTIME_MAP: ReadonlyMap<string, { azure: string; gcp: string }> = new Map([
  ['nodejs18.x', { azure: 'node', gcp: 'nodejs18' }],
  ['nodejs20.x', { azure: 'node', gcp: 'nodejs20' }],
  ['python3.9', { azure: 'python', gcp: 'python39' }],
  ['python3.10', { azure: 'python', gcp: 'python310' }],
  ['python3.11', { azure: 'python', gcp: 'python311' }],
  ['python3.12', { azure: 'python', gcp: 'python312' }],
  ['java17', { azure: 'java', gcp: 'java17' }],
  ['java21', { azure: 'java', gcp: 'java21' }],
  ['dotnet6', { azure: 'dotnet', gcp: 'dotnet6' }],
  ['dotnet8', { azure: 'dotnet-isolated', gcp: 'dotnet8' }],
  ['go1.x', { azure: 'custom', gcp: 'go121' }],
]);

// ---------------------------------------------------------------------------
// Trigger detection
// ---------------------------------------------------------------------------

type TriggerKind = 'http' | 'queue' | 'storage' | 'unknown';

function detectTrigger(ctx: TranslationContext): TriggerKind {
  // Scan sibling resources for known trigger types
  for (const sibling of ctx.siblingResources) {
    if (sibling.sourceType.includes('api_gateway')) return 'http';
    if (sibling.sourceType === 'aws_sqs_queue') return 'queue';
    if (sibling.sourceType === 'aws_s3_bucket') return 'storage';
  }

  // Also check relationships
  for (const rel of ctx.relationships) {
    const otherId = rel.from === ctx.resource.id ? rel.to : rel.from;
    const sibling = ctx.siblingResources.find(r => r.id === otherId);
    if (!sibling) continue;
    if (sibling.sourceType.includes('api_gateway')) return 'http';
    if (sibling.sourceType === 'aws_sqs_queue') return 'queue';
    if (sibling.sourceType === 'aws_s3_bucket') return 'storage';
  }

  return 'unknown';
}

// ---------------------------------------------------------------------------
// Azure translation (3 resources)
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/lambda', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const runtime = (attrs['runtime'] as string | undefined) ?? 'nodejs18.x';
  const runtimeEntry = RUNTIME_MAP.get(runtime);
  const azureRuntime = runtimeEntry?.azure ?? 'custom';
  const functionName = (attrs['function_name'] as string | undefined) ?? sourceName;

  const env = (attrs['environment'] as Record<string, unknown> | undefined);
  const envVars = (env?.['variables'] as Record<string, string> | undefined) ?? {};

  const trigger = detectTrigger(ctx);

  const translated: TranslatedResource[] = [];

  // 1. Service Plan (Consumption)
  const planAttrs: Record<string, unknown> = {
    location: '${azurerm_resource_group.main.location}',
    name: `${sourceName}-plan`,
    os_type: 'Linux',
    resource_group_name: '${azurerm_resource_group.main.name}',
    sku_name: 'Y1',
  };
  if (tags) planAttrs['tags'] = transformTags('azure', tags);

  translated.push({
    targetType: 'azurerm_service_plan',
    targetName: `${sourceName}_plan`,
    attributes: planAttrs,
    sourceId: resource.id,
    traceability,
  });

  // 2. Storage Account (required for Azure Functions)
  const storageAttrs: Record<string, unknown> = {
    account_replication_type: 'LRS',
    account_tier: 'Standard',
    location: '${azurerm_resource_group.main.location}',
    name: sanitizeStorageName(sourceName),
    resource_group_name: '${azurerm_resource_group.main.name}',
  };
  if (tags) storageAttrs['tags'] = transformTags('azure', tags);

  translated.push({
    targetType: 'azurerm_storage_account',
    targetName: `${sourceName}_storage`,
    attributes: storageAttrs,
    sourceId: resource.id,
    traceability,
  });

  // 3. Function App
  const appSettings: Record<string, string> = { ...envVars };
  const fnAttrs: Record<string, unknown> = {
    app_settings: appSettings,
    functions_extension_version: '~4',
    location: '${azurerm_resource_group.main.location}',
    name: functionName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    service_plan_id: `\${azurerm_service_plan.${sourceName}_plan.id}`,
    site_config: {
      application_stack: {
        [azureRuntime === 'dotnet-isolated' ? 'dotnet_version' : `${azureRuntime}_version`]:
          runtime.replace(/[^0-9.]/g, '') || 'latest',
      },
    },
    storage_account_access_key: `\${azurerm_storage_account.${sourceName}_storage.primary_access_key}`,
    storage_account_name: `\${azurerm_storage_account.${sourceName}_storage.name}`,
  };
  if (tags) fnAttrs['tags'] = transformTags('azure', tags);

  // VPC config -> virtual_network_subnet_id
  const vpcConfig = attrs['vpc_config'] as Record<string, unknown> | undefined;
  if (vpcConfig?.['subnet_ids']) {
    const subnetIds = vpcConfig['subnet_ids'] as string[];
    if (subnetIds.length > 0) {
      fnAttrs['virtual_network_subnet_id'] = subnetIds[0];
    }
  }

  translated.push({
    targetType: 'azurerm_linux_function_app',
    targetName: sourceName,
    attributes: fnAttrs,
    sourceId: resource.id,
    traceability,
  });

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_lambda_function -> 3 azure resources (plan + storage + function_app)`,
    ),
    createFinding(
      resource.id,
      'info',
      'TRIGGER_DETECTED',
      `Detected trigger type: ${trigger}`,
    ),
  ];

  if (!runtimeEntry) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'UNKNOWN_RUNTIME',
        `Runtime '${runtime}' has no known Azure mapping; defaulting to custom`,
      ),
    );
  }

  if ((attrs['layers'] as unknown[] | undefined)?.length) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'LAYERS_NOT_SUPPORTED',
        'Lambda layers have no direct Azure equivalent; manual migration required',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation (1 resource)
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/lambda', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const runtime = (attrs['runtime'] as string | undefined) ?? 'nodejs18.x';
  const runtimeEntry = RUNTIME_MAP.get(runtime);
  const gcpRuntime = runtimeEntry?.gcp ?? 'nodejs18';
  const memoryMb = (attrs['memory_size'] as number | undefined) ?? 128;
  const timeout = (attrs['timeout'] as number | undefined) ?? 3;
  const functionName = (attrs['function_name'] as string | undefined) ?? sourceName;
  const handler = (attrs['handler'] as string | undefined) ?? 'index.handler';

  const env = (attrs['environment'] as Record<string, unknown> | undefined);
  const envVars = (env?.['variables'] as Record<string, string> | undefined) ?? {};

  const trigger = detectTrigger(ctx);

  // Build event trigger or HTTP trigger based on detection
  const serviceConfig: Record<string, unknown> = {
    available_memory: `${memoryMb}M`,
    environment_variables: envVars,
    max_instance_count: 100,
    timeout_seconds: timeout,
  };

  // VPC config -> vpc_connector
  const vpcConfig = attrs['vpc_config'] as Record<string, unknown> | undefined;
  if (vpcConfig) {
    serviceConfig['vpc_connector'] = '${google_vpc_access_connector.main.id}';
  }

  const fnAttrs: Record<string, unknown> = {
    build_config: {
      entry_point: handler,
      runtime: gcpRuntime,
    },
    location: '${var.region}',
    name: functionName,
    service_config: serviceConfig,
  };

  // Set event trigger based on detected trigger type
  if (trigger === 'queue') {
    fnAttrs['event_trigger'] = {
      event_type: 'google.cloud.pubsub.topic.v1.messagePublished',
      pubsub_topic: '${google_pubsub_topic.main.id}',
      retry_policy: 'RETRY_POLICY_RETRY',
    };
  } else if (trigger === 'storage') {
    fnAttrs['event_trigger'] = {
      event_type: 'google.cloud.storage.object.v1.finalized',
      retry_policy: 'RETRY_POLICY_RETRY',
    };
  }
  // HTTP trigger is the default (no event_trigger block needed)

  if (tags) fnAttrs['labels'] = transformTags('gcp', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_cloudfunctions2_function',
      targetName: sourceName,
      attributes: fnAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_lambda_function -> 1 gcp resource (cloudfunctions2_function)`,
    ),
    createFinding(
      resource.id,
      'info',
      'TRIGGER_DETECTED',
      `Detected trigger type: ${trigger}`,
    ),
  ];

  if (!runtimeEntry) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'UNKNOWN_RUNTIME',
        `Runtime '${runtime}' has no known GCP mapping; defaulting to nodejs18`,
      ),
    );
  }

  if ((attrs['layers'] as unknown[] | undefined)?.length) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'LAYERS_NOT_SUPPORTED',
        'Lambda layers have no direct GCP equivalent; manual migration required',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Azure storage account names must be 3-24 chars, lowercase alphanumeric only.
 */
function sanitizeStorageName(name: string): string {
  const cleaned = name.replace(/[^a-z0-9]/gi, '').toLowerCase();
  // Must be 3-24 chars; prefix 'st' if too short, truncate if too long
  const padded = cleaned.length < 3 ? `st${cleaned}fn` : cleaned;
  return padded.slice(0, 24);
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_lambda_function to Azure Function App (3 resources)
 * or GCP Cloud Functions v2 (1 resource).
 */
export function translateLambda(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
