/**
 * AWS VPC Endpoint (PrivateLink) -> Azure Private Endpoint / GCP Private Service Connect.
 *
 * Dispatch by sourceType + vpc_endpoint_type:
 *   aws_vpc_endpoint + Interface -> consumer path (real resources)
 *   aws_vpc_endpoint + Gateway   -> advisory (S3/DynamoDB gateway, no equivalent)
 *   aws_vpc_endpoint_service      -> advisory (producer, no auto-equivalent)
 *
 * Consumer Azure:
 *   azurerm_private_endpoint with private_service_connection block
 *
 * Consumer GCP:
 *   google_compute_address (INTERNAL, purpose GCE_ENDPOINT)
 *   + google_compute_forwarding_rule (PSC, load_balancing_scheme="")
 *
 * Cross-account: blocker finding (translated:[]) when service_name contains
 * a 12-digit AWS account ID pattern.
 *
 * @module structural/privatelink-mapping
 * @generated by code-generator (TASK-NET-007)
 */

import type { TranslatedResource, TranslationFinding } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  transformRegion,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';
import { createAdvisoryStub } from '../advisory/advisory-helpers.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Regex to detect cross-account service names (exactly 12-digit AWS account ID). */
const CROSS_ACCOUNT_RE = /\b\d{12}\b/;

/** Keys explicitly handled for aws_vpc_endpoint. */
const ENDPOINT_MAPPED_KEYS: readonly string[] = [
  'auto_accept',
  'dns_entry',
  'private_dns_enabled',
  'route_table_ids',
  'security_group_ids',
  'service_name',
  'subnet_ids',
  'tags',
  'vpc_endpoint_type',
  'vpc_id',
];

// ---------------------------------------------------------------------------
// Confidence clamping
// ---------------------------------------------------------------------------

/**
 * Clamps traceability confidence to [0.45, 0.60] — PrivateLink translations
 * have significant behavioral gaps across providers.
 */
function clampConfidence(
  traceability: ReturnType<typeof makeTraceability>,
): ReturnType<typeof makeTraceability> {
  const raw = traceability.confidence;
  const safeRaw = typeof raw === 'number' && isFinite(raw) ? raw : 0.45;
  const clamped =
    Math.round(Math.min(0.60, Math.max(0.45, safeRaw)) * 100) / 100;
  return { ...traceability, confidence: clamped };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Extracts the VPC ID from the context resource, defaulting to 'main'.
 */
function extractVpcId(attrs: Record<string, unknown>): string {
  const vpcId = attrs['vpc_id'];
  return typeof vpcId === 'string' && vpcId.length > 0 ? vpcId : 'main';
}

/**
 * Extracts the first subnet ID, or returns undefined.
 */
function extractFirstSubnet(attrs: Record<string, unknown>): string | undefined {
  const ids = attrs['subnet_ids'];
  if (Array.isArray(ids) && ids.length > 0 && typeof ids[0] === 'string') {
    return ids[0];
  }
  return undefined;
}

/**
 * Detects whether the service_name references a cross-account endpoint
 * (contains a 12-digit AWS account ID).
 */
function isCrossAccount(attrs: Record<string, unknown>): boolean {
  const sn = attrs['service_name'];
  return typeof sn === 'string' && CROSS_ACCOUNT_RE.test(sn);
}

// ---------------------------------------------------------------------------
// Consumer: Azure — azurerm_private_endpoint
// ---------------------------------------------------------------------------

function translateConsumerAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const rawTrace = makeTraceability(ctx, 'structural/privatelink', 'structural');
  const traceability = clampConfidence(rawTrace);
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const translated: TranslatedResource[] = [];
  const findings: TranslationFinding[] = [];

  const vpcId = extractVpcId(attrs);
  const subnetId = extractFirstSubnet(attrs);
  const sourceRegion =
    typeof attrs['region'] === 'string' ? attrs['region'] : 'us-east-1';
  const serviceName = attrs['service_name'] as string | undefined;

  // Private Endpoint
  const peAttrs: Record<string, unknown> = {
    location: transformRegion('azure', sourceRegion),
    name: `${resource.sourceName}-pe`,
    resource_group_name: '${azurerm_resource_group.main.name}',
    subnet_id: subnetId
      ? `\${azurerm_subnet.${subnetId}.id}`
      : `\${azurerm_subnet.${vpcId}_default.id}`,
    private_service_connection: {
      is_manual_connection: false,
      name: `${resource.sourceName}-psc`,
      private_connection_resource_id: '${var.private_link_target_resource_id}',
    },
  };
  if (tags) {
    peAttrs['tags'] = transformTags('azure', tags);
  }

  translated.push({
    targetType: 'azurerm_private_endpoint',
    targetName: `${resource.sourceName}_pe`,
    attributes: peAttrs,
    sourceId: resource.id,
    traceability,
  });

  // Findings
  findings.push(
    ...collectUnmappedAttrs(resource.id, attrs, ENDPOINT_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_vpc_endpoint (Interface) -> 1 azurerm_private_endpoint',
    ),
  );

  // Service ID manual task — user must supply the target resource ID
  findings.push(
    createFinding(
      resource.id,
      'warning',
      'PRIVATELINK_SERVICE_ID_MANUAL',
      'private_connection_resource_id must be set to the Azure resource ID of the target service',
      JSON.stringify({
        currentPlaceholder: '${var.private_link_target_resource_id}',
        awsServiceName: serviceName ?? 'unknown',
      }),
    ),
  );

  // DNS zone advisory
  if (attrs['private_dns_enabled'] === true) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'PRIVATELINK_DNS_ZONE_MANUAL',
        'private_dns_enabled was true; Azure private DNS zone group must be configured manually',
        JSON.stringify({
          migrationSteps: [
            'Create azurerm_private_dns_zone for the target service',
            'Add azurerm_private_dns_zone_virtual_network_link to the VNet',
            'Add private_dns_zone_group block to the private endpoint',
          ],
        }),
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Consumer: GCP — compute_address + forwarding_rule (PSC)
// ---------------------------------------------------------------------------

function translateConsumerGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const rawTrace = makeTraceability(ctx, 'structural/privatelink', 'structural');
  const traceability = clampConfidence(rawTrace);
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const translated: TranslatedResource[] = [];
  const findings: TranslationFinding[] = [];

  const vpcId = extractVpcId(attrs);
  const subnetId = extractFirstSubnet(attrs);
  const sourceRegion =
    typeof attrs['region'] === 'string' ? attrs['region'] : 'us-east-1';
  const serviceName = attrs['service_name'] as string | undefined;

  const gcpRegion = transformRegion('gcp', sourceRegion);

  // 1. Internal IP address for PSC endpoint
  const addrAttrs: Record<string, unknown> = {
    address_type: 'INTERNAL',
    name: `${resource.sourceName}-psc-addr`,
    purpose: 'GCE_ENDPOINT',
    region: gcpRegion,
    subnetwork: subnetId
      ? `\${google_compute_subnetwork.${subnetId}.self_link}`
      : `\${google_compute_subnetwork.${vpcId}_default.self_link}`,
  };
  if (tags) {
    addrAttrs['labels'] = transformTags('gcp', tags);
  }

  translated.push({
    targetType: 'google_compute_address',
    targetName: `${resource.sourceName}_psc_addr`,
    attributes: addrAttrs,
    sourceId: resource.id,
    traceability,
  });

  // 2. Forwarding rule (PSC consumer)
  const fwdAttrs: Record<string, unknown> = {
    load_balancing_scheme: '',
    name: `${resource.sourceName}-psc-fwd`,
    network: `\${google_compute_network.${vpcId}.self_link}`,
    ip_address: `\${google_compute_address.${resource.sourceName}_psc_addr.address}`,
    region: gcpRegion,
    target: '${var.psc_target_service_attachment}',
  };

  translated.push({
    targetType: 'google_compute_forwarding_rule',
    targetName: `${resource.sourceName}_psc_fwd`,
    attributes: fwdAttrs,
    sourceId: resource.id,
    traceability,
  });

  // Findings
  findings.push(
    ...collectUnmappedAttrs(resource.id, attrs, ENDPOINT_MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_vpc_endpoint (Interface) -> 2 gcp resources (1 compute_address + 1 forwarding_rule)',
    ),
  );

  // PSC target manual task
  findings.push(
    createFinding(
      resource.id,
      'warning',
      'PRIVATELINK_PSC_TARGET_MANUAL',
      'target must be set to the GCP service attachment URI of the target service',
      JSON.stringify({
        currentPlaceholder: '${var.psc_target_service_attachment}',
        awsServiceName: serviceName ?? 'unknown',
      }),
    ),
  );

  // DNS advisory
  if (attrs['private_dns_enabled'] === true) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'PRIVATELINK_DNS_ZONE_MANUAL',
        'private_dns_enabled was true; GCP private DNS zone must be configured manually for PSC endpoint',
        JSON.stringify({
          migrationSteps: [
            'Create google_dns_managed_zone with private visibility',
            'Add google_dns_record_set pointing to the PSC endpoint IP',
            'Ensure the VPC network is linked to the DNS zone',
          ],
        }),
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Gateway advisory (S3/DynamoDB gateway endpoints — no equivalent)
// ---------------------------------------------------------------------------

function translateGatewayAdvisory(ctx: TranslationContext): EngineResult {
  const provider = ctx.targetProvider === 'azure' ? 'Azure' : 'GCP';
  const attrs = ctx.resource.attributes as Record<string, unknown>;
  const serviceName = attrs['service_name'] as string | undefined;

  const azureSteps: readonly string[] = [
    'Gateway VPC endpoints (S3/DynamoDB) have no Azure Private Endpoint equivalent',
    'For S3: use Azure Blob Storage with a service endpoint or private endpoint to the storage account',
    'For DynamoDB: use Cosmos DB with VNet service endpoint or private endpoint',
    'Review route table associations and update NSG rules accordingly',
  ];

  const gcpSteps: readonly string[] = [
    'Gateway VPC endpoints (S3/DynamoDB) have no GCP Private Service Connect equivalent',
    'For S3: use Cloud Storage with VPC Service Controls or Private Google Access',
    'For DynamoDB: use Firestore/Bigtable with Private Google Access',
    'Ensure Private Google Access is enabled on the relevant subnets',
  ];

  const steps = ctx.targetProvider === 'azure' ? azureSteps : gcpSteps;
  const alternatives = ctx.targetProvider === 'azure'
    ? ['Azure Service Endpoint', 'Azure Private Endpoint to storage/database']
    : ['Private Google Access', 'VPC Service Controls'];

  return createAdvisoryStub(
    ctx,
    'PRIVATELINK_GATEWAY_ADVISORY',
    `aws_vpc_endpoint (Gateway) for ${serviceName ?? 'unknown service'} has no direct ${provider} equivalent; ` +
      'gateway endpoints are advisory-only',
    steps,
    alternatives,
  );
}

// ---------------------------------------------------------------------------
// Producer advisory (aws_vpc_endpoint_service — no auto-equivalent)
// ---------------------------------------------------------------------------

function translateProducerAdvisory(ctx: TranslationContext): EngineResult {
  const provider = ctx.targetProvider === 'azure' ? 'Azure' : 'GCP';

  const azureSteps: readonly string[] = [
    'Create Azure Private Link Service attached to a Standard Load Balancer',
    'Configure NAT IP addresses on the Private Link Service',
    'Set up approval workflow (auto-approve or manual) for consumer connections',
    'Update DNS records for consumers to discover the service',
  ];

  const gcpSteps: readonly string[] = [
    'Create a GCP Service Attachment on an internal TCP/UDP load balancer',
    'Configure NAT subnets for Private Service Connect',
    'Set up connection acceptance policy (auto or manual)',
    'Publish the service attachment URI for consumers',
  ];

  const steps = ctx.targetProvider === 'azure' ? azureSteps : gcpSteps;
  const alternatives = ctx.targetProvider === 'azure'
    ? ['Azure Private Link Service']
    : ['GCP Private Service Connect (Service Attachment)'];

  return createAdvisoryStub(
    ctx,
    'PRIVATELINK_PRODUCER_ADVISORY',
    `aws_vpc_endpoint_service has no automated ${provider} translation; ` +
      'producer-side PrivateLink must be configured manually',
    steps,
    alternatives,
  );
}

// ---------------------------------------------------------------------------
// Cross-account blocker
// ---------------------------------------------------------------------------

function translateCrossAccountBlocker(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const serviceName = attrs['service_name'] as string | undefined;

  return {
    translated: [],
    findings: [
      createFinding(
        resource.id,
        'blocker',
        'PRIVATELINK_CROSS_ACCOUNT_BLOCKER',
        'Cross-account PrivateLink endpoint detected; automated translation blocked — ' +
          'target service owner must provision the equivalent in the target cloud',
        JSON.stringify({
          awsServiceName: serviceName ?? 'unknown',
          migrationSteps: [
            'Identify the service owner of the cross-account endpoint',
            'Coordinate with the service owner to provision the equivalent endpoint service in the target cloud',
            'Update this endpoint configuration to reference the new target-cloud service',
          ],
        }),
      ),
    ],
  };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates aws_vpc_endpoint or aws_vpc_endpoint_service to the target
 * provider's private connectivity primitives.
 *
 * - Interface endpoints -> real resources (Azure Private Endpoint / GCP PSC)
 * - Gateway endpoints -> advisory (no equivalent)
 * - Endpoint services (producer) -> advisory
 * - Cross-account endpoints -> blocker
 * - Unknown sourceType -> safe advisory fallback (no throw)
 */
export function translatePrivateLink(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;

  // Producer path: aws_vpc_endpoint_service
  if (resource.sourceType === 'aws_vpc_endpoint_service') {
    return translateProducerAdvisory(ctx);
  }

  // Safe fallback for any sourceType other than the two known ones.
  // This prevents silent misclassification when an unexpected type arrives.
  if (resource.sourceType !== 'aws_vpc_endpoint') {
    return {
      translated: [],
      findings: [
        createFinding(
          resource.id,
          'warning',
          'PRIVATELINK_UNKNOWN_SOURCE_TYPE',
          `Unknown sourceType '${String(resource.sourceType ?? '')}' for privatelink-mapping; ` +
            'no translation emitted — review resource type and rerun',
        ),
      ],
    };
  }

  // Consumer paths: aws_vpc_endpoint
  const endpointType = attrs['vpc_endpoint_type'];

  // Gateway endpoints (S3/DynamoDB) -> advisory
  if (endpointType === 'Gateway') {
    return translateGatewayAdvisory(ctx);
  }

  // Cross-account blocker check (Interface endpoints only)
  if (isCrossAccount(attrs)) {
    return translateCrossAccountBlocker(ctx);
  }

  // Interface endpoint -> real resources
  if (ctx.targetProvider === 'azure') {
    return translateConsumerAzure(ctx);
  }
  return translateConsumerGcp(ctx);
}
