/**
 * AWS Route Table -> Azure Route Table + Routes / GCP Compute Routes translation.
 * Azure: 1 azurerm_route_table + N azurerm_route (1:N expansion).
 * GCP: N google_compute_route (no parent route table concept).
 *
 * Next-hop mapping:
 *   gateway_id (igw-*) -> Azure: Internet / GCP: default-internet-gateway
 *   nat_gateway_id      -> Azure: VirtualAppliance + next_hop_ip / GCP: next_hop_ip
 *   local               -> Azure: VnetLocal / GCP: implicit (skipped)
 *
 * @module structural/route-table-mapping
 * @generated by code-generator (TASK-NET-001)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  transformRegion,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
  findSiblingVpc,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'propagating_vgws',
  'route',
  'tags',
  'vpc_id',
];

// ---------------------------------------------------------------------------
// Route type definition
// ---------------------------------------------------------------------------

interface AwsRoute {
  readonly cidr_block?: string;
  readonly ipv6_cidr_block?: string;
  readonly gateway_id?: string;
  readonly nat_gateway_id?: string;
  readonly network_interface_id?: string;
  readonly transit_gateway_id?: string;
  readonly vpc_peering_connection_id?: string;
  readonly egress_only_gateway_id?: string;
}

// ---------------------------------------------------------------------------
// Route conflict detection
// ---------------------------------------------------------------------------

/**
 * Detects duplicate CIDR blocks across routes and returns warning findings.
 */
function detectRouteConflicts(
  resourceId: string,
  routes: readonly AwsRoute[],
): ReturnType<typeof createFinding>[] {
  const seen = new Map<string, number>();
  const findings: ReturnType<typeof createFinding>[] = [];

  for (const route of routes) {
    const cidr = route.cidr_block ?? route.ipv6_cidr_block;
    if (!cidr) continue;
    const count = (seen.get(cidr) ?? 0) + 1;
    seen.set(cidr, count);
    if (count === 2) {
      findings.push(
        createFinding(
          resourceId,
          'warning',
          'ROUTE_CIDR_CONFLICT',
          `Duplicate CIDR '${cidr}' detected in route table; only one route per destination is valid`,
        ),
      );
    }
  }

  return findings;
}

// ---------------------------------------------------------------------------
// Azure next-hop mapping
// ---------------------------------------------------------------------------

interface AzureNextHop {
  readonly next_hop_type: string;
  readonly next_hop_in_ip_address?: string;
}

interface AzureNextHopResult {
  readonly hop: AzureNextHop;
  readonly unsupported?: string;
}

function mapAzureNextHop(route: AwsRoute): AzureNextHopResult {
  if (route.gateway_id) {
    // igw -> Internet
    return { hop: { next_hop_type: 'Internet' } };
  }
  if (route.nat_gateway_id) {
    // NAT -> VirtualAppliance with IP ref
    return {
      hop: {
        next_hop_type: 'VirtualAppliance',
        next_hop_in_ip_address: `\${azurerm_nat_gateway.${route.nat_gateway_id}.resource_guid}`,
      },
    };
  }
  if (route.network_interface_id) {
    return {
      hop: {
        next_hop_type: 'VirtualAppliance',
        next_hop_in_ip_address: `\${azurerm_network_interface.${route.network_interface_id}.private_ip_address}`,
      },
    };
  }
  if (route.transit_gateway_id) {
    return { hop: { next_hop_type: 'VirtualNetworkGateway' } };
  }
  if (route.vpc_peering_connection_id) {
    return { hop: { next_hop_type: 'VnetLocal' } };
  }
  if (route.egress_only_gateway_id) {
    // Egress-only IGW (IPv6) has no direct Azure equivalent; map to Internet with warning
    return {
      hop: { next_hop_type: 'Internet' },
      unsupported: 'egress_only_gateway_id',
    };
  }
  // Default: local route
  return { hop: { next_hop_type: 'VnetLocal' } };
}

// ---------------------------------------------------------------------------
// Azure translation (1 route table + N routes)
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/route-table', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const translated: TranslatedResource[] = [];
  const routes = (attrs['route'] as readonly AwsRoute[] | undefined) ?? [];

  // 1. Route table resource
  const rtAttrs: Record<string, unknown> = {
    location: transformRegion('azure', 'us-east-1'),
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
  };
  if (tags) {
    rtAttrs['tags'] = transformTags('azure', tags);
  }

  translated.push({
    targetType: 'azurerm_route_table',
    targetName: resource.sourceName,
    attributes: rtAttrs,
    sourceId: resource.id,
    traceability,
  });

  // 2. Individual route resources
  const unsupportedNextHops: string[] = [];
  for (let i = 0; i < routes.length; i++) {
    const route = routes[i]!;
    const cidr = route.cidr_block ?? route.ipv6_cidr_block;
    if (!cidr) continue;

    // Skip local routes — Azure handles them implicitly
    if (!route.gateway_id && !route.nat_gateway_id && !route.network_interface_id &&
        !route.transit_gateway_id && !route.vpc_peering_connection_id &&
        !route.egress_only_gateway_id) {
      continue;
    }

    const { hop: nextHop, unsupported } = mapAzureNextHop(route);
    if (unsupported) {
      unsupportedNextHops.push(unsupported);
    }
    const routeAttrs: Record<string, unknown> = {
      address_prefix: cidr,
      name: `${resource.sourceName}-route-${i}`,
      next_hop_type: nextHop.next_hop_type,
      resource_group_name: '${azurerm_resource_group.main.name}',
      route_table_name: `\${azurerm_route_table.${resource.sourceName}.name}`,
    };
    if (nextHop.next_hop_in_ip_address) {
      routeAttrs['next_hop_in_ip_address'] = nextHop.next_hop_in_ip_address;
    }

    translated.push({
      targetType: 'azurerm_route',
      targetName: `${resource.sourceName}_route_${i}`,
      attributes: routeAttrs,
      sourceId: resource.id,
      traceability,
    });
  }

  const routeCount = translated.length - 1; // subtract route table itself
  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    ...detectRouteConflicts(resource.id, routes),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_route_table -> ${translated.length} azure resources (1 route_table + ${routeCount} routes)`,
    ),
  ];

  // Empty route table advisory
  if (routes.length === 0) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'ROUTE_TABLE_EMPTY',
        'Route table has no routes defined; only an empty azurerm_route_table will be created',
      ),
    );
  }

  // Unsupported next-hop type advisories
  for (const nhType of unsupportedNextHops) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'ROUTE_NEXTHOP_UNSUPPORTED',
        `Next-hop type '${nhType}' has no direct Azure equivalent; mapped to best-effort fallback — manual review required`,
      ),
    );
  }

  // VGW propagation advisory
  const vgws = attrs['propagating_vgws'] as readonly string[] | undefined;
  if (Array.isArray(vgws) && vgws.length > 0) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'ROUTE_VGW_PROPAGATION',
        'propagating_vgws has no direct Azure equivalent; configure BGP route propagation on Azure VPN Gateway manually',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP next-hop mapping
// ---------------------------------------------------------------------------

interface GcpNextHop {
  readonly next_hop_gateway?: string;
  readonly next_hop_ip?: string;
  readonly next_hop_instance?: string;
  readonly next_hop_vpn_tunnel?: string;
  readonly skip?: boolean;
  readonly unsupported?: string;
}

function mapGcpNextHop(route: AwsRoute): GcpNextHop {
  if (route.gateway_id) {
    return { next_hop_gateway: 'default-internet-gateway' };
  }
  if (route.nat_gateway_id) {
    return {
      next_hop_ip: `\${google_compute_address.${route.nat_gateway_id}.address}`,
    };
  }
  if (route.network_interface_id) {
    return {
      next_hop_instance: `\${google_compute_instance.${route.network_interface_id}.self_link}`,
    };
  }
  if (route.transit_gateway_id) {
    return {
      next_hop_vpn_tunnel: `\${google_compute_vpn_tunnel.${route.transit_gateway_id}.self_link}`,
    };
  }
  if (route.vpc_peering_connection_id) {
    // GCP peering routes are auto-propagated; emit advisory
    return { skip: true, unsupported: 'vpc_peering_connection_id' };
  }
  if (route.egress_only_gateway_id) {
    // Egress-only IGW (IPv6) — best-effort map to internet gateway
    return {
      next_hop_gateway: 'default-internet-gateway',
      unsupported: 'egress_only_gateway_id',
    };
  }
  // Local route — implicit in GCP, skip
  return { skip: true };
}

// ---------------------------------------------------------------------------
// GCP translation (N compute routes, no parent table)
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/route-table', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const vpcRef = findSiblingVpc(ctx);
  const network = vpcRef
    ? `\${google_compute_network.${vpcRef.sourceName}.self_link}`
    : '${google_compute_network.main.self_link}';

  const translated: TranslatedResource[] = [];
  const routes = (attrs['route'] as readonly AwsRoute[] | undefined) ?? [];

  const unsupportedNextHops: string[] = [];
  for (let i = 0; i < routes.length; i++) {
    const route = routes[i]!;
    const cidr = route.cidr_block ?? route.ipv6_cidr_block;
    if (!cidr) continue;

    const nextHop = mapGcpNextHop(route);
    if (nextHop.unsupported) {
      unsupportedNextHops.push(nextHop.unsupported);
    }
    if (nextHop.skip) continue;

    const routeAttrs: Record<string, unknown> = {
      dest_range: cidr,
      name: `${resource.sourceName}-route-${i}`,
      network,
      priority: 1000,
    };

    if (nextHop.next_hop_gateway) routeAttrs['next_hop_gateway'] = nextHop.next_hop_gateway;
    if (nextHop.next_hop_ip) routeAttrs['next_hop_ip'] = nextHop.next_hop_ip;
    if (nextHop.next_hop_instance) routeAttrs['next_hop_instance'] = nextHop.next_hop_instance;
    if (nextHop.next_hop_vpn_tunnel) routeAttrs['next_hop_vpn_tunnel'] = nextHop.next_hop_vpn_tunnel;

    if (tags) {
      routeAttrs['labels'] = transformTags('gcp', tags);
    }

    translated.push({
      targetType: 'google_compute_route',
      targetName: `${resource.sourceName}_route_${i}`,
      attributes: routeAttrs,
      sourceId: resource.id,
      traceability,
    });
  }

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    ...detectRouteConflicts(resource.id, routes),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_route_table -> ${translated.length} google_compute_route(s) (no parent table in GCP)`,
    ),
  ];

  // Empty route table advisory
  if (routes.length === 0) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'ROUTE_TABLE_EMPTY',
        'Route table has no routes defined; no google_compute_route resources will be created',
      ),
    );
  }

  // Unsupported next-hop type advisories
  for (const nhType of unsupportedNextHops) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'ROUTE_NEXTHOP_UNSUPPORTED',
        `Next-hop type '${nhType}' has no direct GCP equivalent; route skipped or mapped to best-effort fallback — manual review required`,
      ),
    );
  }

  // VGW propagation advisory
  const vgws = attrs['propagating_vgws'] as readonly string[] | undefined;
  if (Array.isArray(vgws) && vgws.length > 0) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'ROUTE_VGW_PROPAGATION',
        'propagating_vgws has no direct GCP equivalent; configure Cloud Router BGP sessions manually',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_route_table to Azure (1 route_table + N routes) or
 * GCP (N compute routes with no parent table).
 */
export function translateRouteTable(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
