/**
 * AWS Security Group -> Azure NSG / GCP Firewall Rules translation.
 * Azure: 1 NSG + N security rules (one per ingress/egress rule).
 * GCP: N firewall rules (one per ingress/egress rule).
 *
 * BLOCKER GATE (ingress-only): If any ingress rule has cidr 0.0.0.0/0 or
 * ::/0 with protocol -1 OR port range 0-65535, the resource is flagged as
 * a security blocker. Overly permissive egress emits a warning instead.
 *
 * @module structural/security-group-mapping
 * @generated by code-generator (TASK-NET-003)
 */

import type { TranslatedResource, TranslationFinding } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
  findSiblingVpc,
} from '../direct/attribute-transformer.js';
import { resolveCidrs, isOpenCidr } from './sg-cidr-aggregator.js';
import { isIcmpProtocol, assignAzurePriority, assignGcpPriority } from './sg-rule-comparator.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'description',
  'egress',
  'ingress',
  'name',
  'tags',
  'vpc_id',
];

// ---------------------------------------------------------------------------
// Rule type definitions
// ---------------------------------------------------------------------------

export interface SgRule {
  readonly cidr_blocks?: readonly string[];
  readonly ipv6_cidr_blocks?: readonly string[];
  readonly description?: string;
  readonly from_port?: number;
  readonly to_port?: number;
  readonly protocol?: string;
  readonly self?: boolean;
  readonly source_security_group_id?: string;
  readonly prefix_list_ids?: readonly string[];
}

// ---------------------------------------------------------------------------
// Blocker gate: detect overly permissive rules
// ---------------------------------------------------------------------------

function hasOverlyPermissiveRule(rules: readonly SgRule[]): boolean {
  for (const rule of rules) {
    const resolved = resolveCidrs(rule);
    if (!isOpenCidr(resolved)) continue;

    // Protocol -1 means all traffic
    if (rule.protocol === '-1') return true;

    // Port range 0-65535 means all ports
    if (rule.from_port === 0 && rule.to_port === 65535) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Findings helpers for special CIDR fields
// ---------------------------------------------------------------------------

function emitCidrFindings(resourceId: string, rule: SgRule): TranslationFinding[] {
  const findings: TranslationFinding[] = [];
  const resolved = resolveCidrs(rule);

  if (resolved.hasSelf) {
    findings.push(
      createFinding(
        resourceId,
        'warning',
        'SG_SELF_REFERENCE',
        'Security group rule references "self"; manual review required to translate self-referencing rules',
      ),
    );
  }

  if (resolved.hasSourceSgRef !== null) {
    findings.push(
      createFinding(
        resourceId,
        'warning',
        'SG_CROSS_SG_REFERENCE',
        `Security group rule references another security group (${resolved.hasSourceSgRef}); cross-SG references require manual wiring`,
      ),
    );
  }

  return findings;
}

// ---------------------------------------------------------------------------
// Azure translation (NSG + N security rules)
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/security-group', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;
  const description = (attrs['description'] as string | undefined) ?? '';

  const translated: TranslatedResource[] = [];

  // 1. Network Security Group
  const nsgAttrs: Record<string, unknown> = {
    location: '${azurerm_resource_group.main.location}',
    name: sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
  };
  if (description) nsgAttrs['description'] = description;
  if (tags) nsgAttrs['tags'] = transformTags('azure', tags);

  translated.push({
    targetType: 'azurerm_network_security_group',
    targetName: sourceName,
    attributes: nsgAttrs,
    sourceId: resource.id,
    traceability,
  });

  const findings: TranslationFinding[] = [];

  // 2. Security rules from ingress
  const ingress = (attrs['ingress'] as readonly SgRule[] | undefined) ?? [];
  let azureIndex = 0;
  for (let i = 0; i < ingress.length; i++) {
    const rule = ingress[i]!;
    const resolved = resolveCidrs(rule);
    const prioResult = assignAzurePriority(azureIndex);
    if (prioResult.overflow) {
      findings.push(
        createFinding(
          resource.id,
          'warning',
          'SG_PRIORITY_OVERFLOW',
          `Azure NSG priority overflow at ingress rule index ${i}; capped at 4096`,
        ),
      );
    }

    const ruleAttrs: Record<string, unknown> = {
      access: 'Allow',
      direction: 'Inbound',
      name: `${sourceName}-ingress-${i}`,
      network_security_group_name: `\${azurerm_network_security_group.${sourceName}.name}`,
      priority: prioResult.priority,
      protocol: mapProtocolAzure(rule.protocol),
      resource_group_name: '${azurerm_resource_group.main.name}',
      source_port_range: '*',
      destination_address_prefix: '*',
    };

    // Azure multi-CIDR: 1 CIDR -> source_address_prefix, 2+ -> source_address_prefixes
    const allSourceCidrs = [...resolved.ipv4, ...resolved.ipv6];
    if (allSourceCidrs.length > 1) {
      ruleAttrs['source_address_prefixes'] = allSourceCidrs;
    } else {
      ruleAttrs['source_address_prefix'] = allSourceCidrs[0] ?? '*';
    }

    // ICMP port handling
    if (isIcmpProtocol(rule.protocol)) {
      ruleAttrs['destination_port_range'] = '*';
      findings.push(
        createFinding(
          resource.id,
          'info',
          'SG_ICMP_NORMALIZED',
          `Ingress rule ${i}: ICMP protocol normalised; port range set to '*'`,
        ),
      );
    } else {
      ruleAttrs['destination_port_range'] = formatPortRange(rule.from_port, rule.to_port);
    }

    if (rule.description) ruleAttrs['description'] = rule.description;

    findings.push(...emitCidrFindings(resource.id, rule));

    translated.push({
      targetType: 'azurerm_network_security_rule',
      targetName: `${sourceName}_ingress_${i}`,
      attributes: ruleAttrs,
      sourceId: resource.id,
      traceability,
    });
    azureIndex++;
  }

  // 3. Security rules from egress
  const egress = (attrs['egress'] as readonly SgRule[] | undefined) ?? [];
  for (let i = 0; i < egress.length; i++) {
    const rule = egress[i]!;
    const resolved = resolveCidrs(rule);
    const prioResult = assignAzurePriority(azureIndex);
    if (prioResult.overflow) {
      findings.push(
        createFinding(
          resource.id,
          'warning',
          'SG_PRIORITY_OVERFLOW',
          `Azure NSG priority overflow at egress rule index ${i}; capped at 4096`,
        ),
      );
    }

    const ruleAttrs: Record<string, unknown> = {
      access: 'Allow',
      direction: 'Outbound',
      name: `${sourceName}-egress-${i}`,
      network_security_group_name: `\${azurerm_network_security_group.${sourceName}.name}`,
      priority: prioResult.priority,
      protocol: mapProtocolAzure(rule.protocol),
      resource_group_name: '${azurerm_resource_group.main.name}',
      source_address_prefix: '*',
      source_port_range: '*',
    };

    // Azure multi-CIDR for destination
    const allDestCidrs = [...resolved.ipv4, ...resolved.ipv6];
    if (allDestCidrs.length > 1) {
      ruleAttrs['destination_address_prefixes'] = allDestCidrs;
    } else {
      ruleAttrs['destination_address_prefix'] = allDestCidrs[0] ?? '*';
    }

    // ICMP port handling
    if (isIcmpProtocol(rule.protocol)) {
      ruleAttrs['destination_port_range'] = '*';
      findings.push(
        createFinding(
          resource.id,
          'info',
          'SG_ICMP_NORMALIZED',
          `Egress rule ${i}: ICMP protocol normalised; port range set to '*'`,
        ),
      );
    } else {
      ruleAttrs['destination_port_range'] = formatPortRange(rule.from_port, rule.to_port);
    }

    if (rule.description) ruleAttrs['description'] = rule.description;

    findings.push(...emitCidrFindings(resource.id, rule));

    translated.push({
      targetType: 'azurerm_network_security_rule',
      targetName: `${sourceName}_egress_${i}`,
      attributes: ruleAttrs,
      sourceId: resource.id,
      traceability,
    });
    azureIndex++;
  }

  const count = translated.length;
  findings.push(
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_security_group -> ${count} azure resources (1 NSG + ${count - 1} rules)`,
    ),
  );

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation (N firewall rules)
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/security-group', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const vpcRef = findSiblingVpc(ctx);
  const network = vpcRef
    ? `\${google_compute_network.${vpcRef.sourceName}.self_link}`
    : '${google_compute_network.main.self_link}';

  const translated: TranslatedResource[] = [];
  const findings: TranslationFinding[] = [];

  // Ingress firewall rules
  const ingress = (attrs['ingress'] as readonly SgRule[] | undefined) ?? [];
  for (let i = 0; i < ingress.length; i++) {
    const rule = ingress[i]!;
    const resolved = resolveCidrs(rule);
    const prioResult = assignGcpPriority(i);

    // Build allow block -- skip ports for ICMP
    const allowBlock: Record<string, unknown> = {
      protocol: mapProtocolGcp(rule.protocol),
    };
    if (isIcmpProtocol(rule.protocol)) {
      findings.push(
        createFinding(
          resource.id,
          'info',
          'SG_ICMP_NORMALIZED',
          `Ingress rule ${i}: ICMP protocol; ports omitted in GCP firewall allow block`,
        ),
      );
    } else {
      allowBlock['ports'] = formatGcpPorts(rule.from_port, rule.to_port);
    }

    // Merge ipv4+ipv6 into source_ranges
    const sourceRanges = [...resolved.ipv4, ...resolved.ipv6];

    const fwAttrs: Record<string, unknown> = {
      allow: [allowBlock],
      direction: 'INGRESS',
      name: `${sourceName}-ingress-${i}`,
      network,
      priority: prioResult.priority,
      source_ranges: sourceRanges.length > 0 ? sourceRanges : ['0.0.0.0/0'],
    };
    if (rule.description) fwAttrs['description'] = rule.description;
    if (tags) fwAttrs['labels'] = transformTags('gcp', tags);

    if (prioResult.overflow) {
      findings.push(
        createFinding(
          resource.id,
          'warning',
          'SG_PRIORITY_OVERFLOW',
          `GCP firewall priority overflow at ingress rule index ${i}; capped at 65534`,
        ),
      );
    }

    findings.push(...emitCidrFindings(resource.id, rule));

    translated.push({
      targetType: 'google_compute_firewall',
      targetName: `${sourceName}_ingress_${i}`,
      attributes: fwAttrs,
      sourceId: resource.id,
      traceability,
    });
  }

  // Egress firewall rules
  const egress = (attrs['egress'] as readonly SgRule[] | undefined) ?? [];
  for (let i = 0; i < egress.length; i++) {
    const rule = egress[i]!;
    const resolved = resolveCidrs(rule);
    const prioResult = assignGcpPriority(ingress.length + i);

    // Build allow block -- skip ports for ICMP
    const allowBlock: Record<string, unknown> = {
      protocol: mapProtocolGcp(rule.protocol),
    };
    if (isIcmpProtocol(rule.protocol)) {
      findings.push(
        createFinding(
          resource.id,
          'info',
          'SG_ICMP_NORMALIZED',
          `Egress rule ${i}: ICMP protocol; ports omitted in GCP firewall allow block`,
        ),
      );
    } else {
      allowBlock['ports'] = formatGcpPorts(rule.from_port, rule.to_port);
    }

    // Merge ipv4+ipv6 into destination_ranges
    const destRanges = [...resolved.ipv4, ...resolved.ipv6];

    const fwAttrs: Record<string, unknown> = {
      allow: [allowBlock],
      direction: 'EGRESS',
      destination_ranges: destRanges.length > 0 ? destRanges : ['0.0.0.0/0'],
      name: `${sourceName}-egress-${i}`,
      network,
      priority: prioResult.priority,
    };
    if (rule.description) fwAttrs['description'] = rule.description;
    if (tags) fwAttrs['labels'] = transformTags('gcp', tags);

    if (prioResult.overflow) {
      findings.push(
        createFinding(
          resource.id,
          'warning',
          'SG_PRIORITY_OVERFLOW',
          `GCP firewall priority overflow at egress rule index ${i}; capped at 65534`,
        ),
      );
    }

    findings.push(...emitCidrFindings(resource.id, rule));

    translated.push({
      targetType: 'google_compute_firewall',
      targetName: `${sourceName}_egress_${i}`,
      attributes: fwAttrs,
      sourceId: resource.id,
      traceability,
    });
  }

  const count = translated.length;
  findings.push(
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_security_group -> ${count} gcp firewall rules`,
    ),
  );

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Protocol / port helpers
// ---------------------------------------------------------------------------

function mapProtocolAzure(protocol: string | undefined): string {
  if (!protocol || protocol === '-1') return '*';
  const upper = protocol.toUpperCase();
  if (upper === 'TCP') return 'Tcp';
  if (upper === 'UDP') return 'Udp';
  if (upper === 'ICMP') return 'Icmp';
  return '*';
}

function mapProtocolGcp(protocol: string | undefined): string {
  if (!protocol || protocol === '-1') return 'all';
  return protocol.toLowerCase();
}

function formatPortRange(from: number | undefined, to: number | undefined): string {
  if (from === undefined && to === undefined) return '*';
  if (from === to) return String(from ?? 0);
  return `${from ?? 0}-${to ?? 65535}`;
}

function formatGcpPorts(from: number | undefined, to: number | undefined): string[] {
  if (from === undefined && to === undefined) return [];
  if (from === to) return [String(from ?? 0)];
  return [`${from ?? 0}-${to ?? 65535}`];
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_security_group to Azure NSG+rules or GCP firewall rules.
 * Applies the BLOCKER GATE for overly permissive rules before translation.
 */
export function translateSecurityGroup(ctx: TranslationContext): EngineResult {
  const attrs = ctx.resource.attributes as Record<string, unknown>;

  // BLOCKER GATE: ingress-only check for overly permissive rules
  const ingress = (attrs['ingress'] as readonly SgRule[] | undefined) ?? [];
  const egress = (attrs['egress'] as readonly SgRule[] | undefined) ?? [];

  if (hasOverlyPermissiveRule(ingress)) {
    return {
      translated: [],
      findings: [
        createFinding(
          ctx.resource.id,
          'blocker',
          'SECURITY_GROUP_RULE_BROADENING',
          'Security group contains an overly permissive ingress rule (0.0.0.0/0 or ::/0 with all protocols or all ports); manual review required',
        ),
      ],
    };
  }

  // Egress warning (not blocker) for overly permissive egress
  const egressWarnings: TranslationFinding[] = [];
  if (hasOverlyPermissiveRule(egress)) {
    egressWarnings.push(
      createFinding(
        ctx.resource.id,
        'warning',
        'SG_EGRESS_OPEN',
        'Security group contains an overly permissive egress rule (0.0.0.0/0 or ::/0 with all protocols or all ports); review recommended',
      ),
    );
  }

  const result = ctx.targetProvider === 'azure'
    ? translateToAzure(ctx)
    : translateToGcp(ctx);

  // Merge egress warnings into findings
  if (egressWarnings.length > 0) {
    return {
      translated: result.translated,
      findings: [...egressWarnings, ...result.findings],
    };
  }

  return result;
}
