/**
 * Pure CIDR resolution utilities for security group rule translation.
 * Extracts and normalises all CIDR-like fields from an SgRule into a
 * single ResolvedCidrs struct for downstream consumption.
 *
 * @module structural/sg-cidr-aggregator
 * @generated by code-generator (TASK-NET-003)
 */

import type { SgRule } from './security-group-mapping.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ResolvedCidrs {
  readonly ipv4: readonly string[];
  readonly ipv6: readonly string[];
  readonly hasIpv6: boolean;
  readonly hasSelf: boolean;
  readonly hasSourceSgRef: string | null;
  readonly prefixListIds: readonly string[];
}

// ---------------------------------------------------------------------------
// Resolution
// ---------------------------------------------------------------------------

/**
 * Extracts every CIDR-like field from a security group rule into a
 * normalised ResolvedCidrs struct.
 *
 * Fields inspected:
 *  - cidr_blocks       -> ipv4
 *  - ipv6_cidr_blocks  -> ipv6
 *  - self              -> hasSelf
 *  - source_security_group_id -> hasSourceSgRef
 *  - prefix_list_ids   -> prefixListIds
 */
export function resolveCidrs(rule: SgRule): ResolvedCidrs {
  const ipv4 = rule.cidr_blocks ?? [];
  const ipv6 = rule.ipv6_cidr_blocks ?? [];
  const hasSelf = rule.self === true;
  const hasSourceSgRef = rule.source_security_group_id ?? null;
  const prefixListIds = rule.prefix_list_ids ?? [];

  return {
    ipv4,
    ipv6,
    hasIpv6: ipv6.length > 0,
    hasSelf,
    hasSourceSgRef,
    prefixListIds,
  };
}

// ---------------------------------------------------------------------------
// Predicates
// ---------------------------------------------------------------------------

/**
 * Returns true if the resolved CIDRs contain any addressable target
 * (IPv4, IPv6, self, cross-SG reference, or prefix list).
 */
export function hasAnyCidr(resolved: ResolvedCidrs): boolean {
  return (
    resolved.ipv4.length > 0 ||
    resolved.ipv6.length > 0 ||
    resolved.hasSelf ||
    resolved.hasSourceSgRef !== null ||
    resolved.prefixListIds.length > 0
  );
}

/**
 * Returns true if the resolved CIDRs include a fully-open wildcard
 * (0.0.0.0/0 for IPv4 or ::/0 for IPv6).
 */
export function isOpenCidr(resolved: ResolvedCidrs): boolean {
  return resolved.ipv4.includes('0.0.0.0/0') || resolved.ipv6.includes('::/0');
}
