/**
 * Priority assignment, ICMP normalisation, and rule deduplication
 * utilities for security group translation.
 *
 * All functions are pure -- no mutation of inputs, no throws.
 *
 * @module structural/sg-rule-comparator
 * @generated by code-generator (TASK-NET-003)
 */

import type { SgRule } from './security-group-mapping.js';
import type { ResolvedCidrs } from './sg-cidr-aggregator.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PriorityResult {
  readonly priority: number;
  readonly overflow: boolean;
}

export interface NormalizedPort {
  readonly from: number;
  readonly to: number;
}

// ---------------------------------------------------------------------------
// ICMP detection
// ---------------------------------------------------------------------------

const ICMP_PROTOCOLS = new Set(['icmp', 'icmpv6', '1', '58']);

/**
 * Returns true if the protocol string represents an ICMP variant.
 */
export function isIcmpProtocol(protocol: string | undefined): boolean {
  if (protocol === undefined) return false;
  return ICMP_PROTOCOLS.has(protocol.toLowerCase());
}

// ---------------------------------------------------------------------------
// Port normalisation
// ---------------------------------------------------------------------------

/**
 * Normalises a from/to port pair according to protocol semantics:
 *  - ICMP -> { from: -1, to: -1 }
 *  - protocol "-1" (all) -> { from: 0, to: 65535 }
 *  - clamp to 0-65535
 *  - swap if from > to
 */
export function normalizePortRange(
  from: number | undefined,
  to: number | undefined,
  protocol: string | undefined,
): NormalizedPort {
  if (isIcmpProtocol(protocol)) {
    return { from: -1, to: -1 };
  }

  if (protocol === '-1') {
    return { from: 0, to: 65535 };
  }

  let f = from ?? 0;
  let t = to ?? 65535;

  // Clamp
  f = Math.max(0, Math.min(65535, f));
  t = Math.max(0, Math.min(65535, t));

  // Swap if inverted
  if (f > t) {
    const tmp = f;
    f = t;
    t = tmp;
  }

  return { from: f, to: t };
}

// ---------------------------------------------------------------------------
// Priority assignment
// ---------------------------------------------------------------------------

/**
 * Assigns an Azure NSG rule priority: 100 + index * 10, capped at 4096.
 * Returns an overflow flag if the computed priority exceeds the cap.
 */
export function assignAzurePriority(index: number): PriorityResult {
  const priority = 100 + index * 10;
  if (priority > 4096) {
    return { priority: 4096, overflow: true };
  }
  return { priority, overflow: false };
}

/**
 * Assigns a GCP firewall rule priority: 1000 + index * 10, capped at 65534.
 * Returns an overflow flag if the computed priority exceeds the cap.
 */
export function assignGcpPriority(index: number): PriorityResult {
  const priority = 1000 + index * 10;
  if (priority > 65534) {
    return { priority: 65534, overflow: true };
  }
  return { priority, overflow: false };
}

// ---------------------------------------------------------------------------
// Deduplication
// ---------------------------------------------------------------------------

/**
 * Builds a deterministic string key for a rule, used for deduplication.
 * Format: `${direction}|${protocol}|${from}-${to}|${sortedCidrs}`
 */
export function makeRuleKey(
  direction: string,
  protocol: string | undefined,
  from: number | undefined,
  to: number | undefined,
  resolved: ResolvedCidrs,
): string {
  const proto = (protocol ?? '-1').toLowerCase();
  const norm = normalizePortRange(from, to, protocol);
  const allCidrs = [
    ...resolved.ipv4,
    ...resolved.ipv6,
    ...(resolved.hasSelf ? ['self'] : []),
    ...(resolved.hasSourceSgRef ? [`sg:${resolved.hasSourceSgRef}`] : []),
    ...resolved.prefixListIds.map((id) => `pl:${id}`),
  ].sort();

  return `${direction}|${proto}|${norm.from}-${norm.to}|${allCidrs.join(',')}`;
}

/**
 * Deduplicates an array of rules using first-occurrence-wins semantics.
 * Returns the deduplicated indices (into the original array).
 */
export function deduplicateRules(
  rules: readonly SgRule[],
  direction: string,
  resolve: (rule: SgRule) => ResolvedCidrs,
): number[] {
  const seen = new Set<string>();
  const indices: number[] = [];

  for (let i = 0; i < rules.length; i++) {
    const rule = rules[i]!;
    const resolved = resolve(rule);
    const key = makeRuleKey(direction, rule.protocol, rule.from_port, rule.to_port, resolved);
    if (!seen.has(key)) {
      seen.add(key);
      indices.push(i);
    }
  }

  return indices;
}
