/**
 * AWS SNS Topic -> Azure Event Grid / GCP Pub/Sub translation.
 *
 * Standard topics: Azure eventgrid_topic / GCP pubsub_topic.
 * FIFO topics:     Azure servicebus_topic / GCP pubsub_topic (ordered).
 *
 * @module structural/sns-mapping
 * @generated by code-generator (TASK-TRANS-005)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'content_based_deduplication',
  'display_name',
  'fifo_topic',
  'kms_master_key_id',
  'name',
  'tags',
];

// ---------------------------------------------------------------------------
// FIFO detection
// ---------------------------------------------------------------------------

function isFifo(attrs: Record<string, unknown>): boolean {
  if (attrs['fifo_topic'] === true) return true;
  const name = attrs['name'] as string | undefined;
  return name?.endsWith('.fifo') ?? false;
}

// ---------------------------------------------------------------------------
// Azure: Standard -> eventgrid_topic, FIFO -> servicebus_topic
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/sns', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const fifo = isFifo(attrs);
  const translated: TranslatedResource[] = [];

  if (fifo) {
    // Service Bus Topic (FIFO-capable)
    const sbAttrs: Record<string, unknown> = {
      enable_partitioning: false,
      name: sourceName,
      namespace_id: '${azurerm_servicebus_namespace.main.id}',
      requires_duplicate_detection: attrs['content_based_deduplication'] === true,
      support_ordering: true,
    };

    translated.push({
      targetType: 'azurerm_servicebus_topic',
      targetName: sourceName,
      attributes: sbAttrs,
      sourceId: resource.id,
      traceability,
    });
  } else {
    // Event Grid Topic (standard pub/sub)
    const egAttrs: Record<string, unknown> = {
      location: '${azurerm_resource_group.main.location}',
      name: sourceName,
      resource_group_name: '${azurerm_resource_group.main.name}',
    };
    if (tags) egAttrs['tags'] = transformTags('azure', tags);

    translated.push({
      targetType: 'azurerm_eventgrid_topic',
      targetName: sourceName,
      attributes: egAttrs,
      sourceId: resource.id,
      traceability,
    });
  }

  const targetDesc = fifo ? 'servicebus_topic' : 'eventgrid_topic';
  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_sns_topic (${fifo ? 'FIFO' : 'Standard'}) -> 1 azure resource (${targetDesc})`,
    ),
  ];

  if (attrs['kms_master_key_id']) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'KMS_KEY_REFERENCE',
        'SNS KMS encryption key reference requires manual mapping to Azure key vault',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP: pubsub_topic (with ordering for FIFO)
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/sns', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const fifo = isFifo(attrs);

  const topicAttrs: Record<string, unknown> = {
    name: sourceName,
  };

  if (fifo) {
    // GCP Pub/Sub doesn't have native FIFO topics, but enabling
    // message_ordering on subscriptions achieves similar semantics.
    // We annotate the topic so downstream subscription creation knows.
    topicAttrs['message_ordering_enabled'] = true;
  }

  if (tags) topicAttrs['labels'] = transformTags('gcp', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_pubsub_topic',
      targetName: sourceName,
      attributes: topicAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_sns_topic (${fifo ? 'FIFO' : 'Standard'}) -> 1 gcp resource (pubsub_topic${fifo ? ', ordered' : ''})`,
    ),
  ];

  if (attrs['kms_master_key_id']) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'KMS_KEY_REFERENCE',
        'SNS KMS encryption key reference requires manual mapping to GCP KMS',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_sns_topic to Azure Event Grid / Service Bus or GCP Pub/Sub.
 * FIFO topics use Service Bus / ordered Pub/Sub; standard topics use
 * Event Grid / plain Pub/Sub.
 */
export function translateSns(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
