/**
 * AWS SQS Queue -> Azure Service Bus/Storage Queue / GCP Pub/Sub translation.
 *
 * FIFO queues:    Azure servicebus_queue / GCP pubsub_topic + subscription (ordered).
 * Standard queues: Azure storage_queue / GCP pubsub_topic + subscription.
 *
 * @module structural/sqs-mapping
 * @generated by code-generator (TASK-TRANS-005)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'content_based_deduplication',
  'delay_seconds',
  'fifo_queue',
  'max_message_size',
  'message_retention_seconds',
  'name',
  'receive_wait_time_seconds',
  'tags',
  'visibility_timeout_seconds',
];

// ---------------------------------------------------------------------------
// FIFO detection
// ---------------------------------------------------------------------------

function isFifo(attrs: Record<string, unknown>): boolean {
  if (attrs['fifo_queue'] === true) return true;
  const name = attrs['name'] as string | undefined;
  return name?.endsWith('.fifo') ?? false;
}

// ---------------------------------------------------------------------------
// Azure: FIFO -> servicebus_queue, Standard -> storage_queue
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/sqs', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const fifo = isFifo(attrs);
  const retentionSeconds = (attrs['message_retention_seconds'] as number | undefined) ?? 345600;
  const retentionIso = secondsToIsoDuration(retentionSeconds);

  const translated: TranslatedResource[] = [];

  if (fifo) {
    // Service Bus Queue (FIFO-capable)
    const sbAttrs: Record<string, unknown> = {
      default_message_ttl: retentionIso,
      enable_partitioning: false,
      name: sourceName,
      namespace_id: '${azurerm_servicebus_namespace.main.id}',
      requires_duplicate_detection: attrs['content_based_deduplication'] === true,
      requires_session: true, // Enforces ordering
    };

    const delay = attrs['delay_seconds'] as number | undefined;
    if (delay && delay > 0) {
      sbAttrs['lock_duration'] = `PT${delay}S`;
    }

    translated.push({
      targetType: 'azurerm_servicebus_queue',
      targetName: sourceName,
      attributes: sbAttrs,
      sourceId: resource.id,
      traceability,
    });
  } else {
    // Storage Queue (standard)
    const sqAttrs: Record<string, unknown> = {
      name: sourceName.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
      storage_account_name: '${azurerm_storage_account.main.name}',
    };
    if (tags) sqAttrs['metadata'] = transformTags('azure', tags);

    translated.push({
      targetType: 'azurerm_storage_queue',
      targetName: sourceName,
      attributes: sqAttrs,
      sourceId: resource.id,
      traceability,
    });
  }

  const targetDesc = fifo ? 'servicebus_queue' : 'storage_queue';
  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_sqs_queue (${fifo ? 'FIFO' : 'Standard'}) -> 1 azure resource (${targetDesc})`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP: topic + subscription (ordered flag for FIFO)
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/sqs', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const fifo = isFifo(attrs);
  const retentionSeconds = (attrs['message_retention_seconds'] as number | undefined) ?? 345600;

  const translated: TranslatedResource[] = [];

  // 1. Pub/Sub Topic
  const topicAttrs: Record<string, unknown> = {
    name: sourceName,
  };
  if (tags) topicAttrs['labels'] = transformTags('gcp', tags);

  translated.push({
    targetType: 'google_pubsub_topic',
    targetName: sourceName,
    attributes: topicAttrs,
    sourceId: resource.id,
    traceability,
  });

  // 2. Pub/Sub Subscription
  const subAttrs: Record<string, unknown> = {
    ack_deadline_seconds: (attrs['visibility_timeout_seconds'] as number | undefined) ?? 30,
    message_retention_duration: `${retentionSeconds}s`,
    name: `${sourceName}-sub`,
    topic: `\${google_pubsub_topic.${sourceName}.id}`,
  };

  if (fifo) {
    subAttrs['enable_message_ordering'] = true;
  }

  if (tags) subAttrs['labels'] = transformTags('gcp', tags);

  translated.push({
    targetType: 'google_pubsub_subscription',
    targetName: `${sourceName}_sub`,
    attributes: subAttrs,
    sourceId: resource.id,
    traceability,
  });

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_sqs_queue (${fifo ? 'FIFO' : 'Standard'}) -> 2 gcp resources (topic + subscription${fifo ? ', ordered' : ''})`,
    ),
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function secondsToIsoDuration(seconds: number): string {
  const days = Math.floor(seconds / 86400);
  const hours = Math.floor((seconds % 86400) / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = seconds % 60;

  let iso = 'P';
  if (days > 0) iso += `${days}D`;
  if (hours > 0 || mins > 0 || secs > 0) {
    iso += 'T';
    if (hours > 0) iso += `${hours}H`;
    if (mins > 0) iso += `${mins}M`;
    if (secs > 0) iso += `${secs}S`;
  }
  return iso === 'P' ? 'PT0S' : iso;
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_sqs_queue to Azure or GCP equivalents.
 * FIFO queues use Service Bus / ordered Pub/Sub; standard queues use
 * Storage Queue / plain Pub/Sub.
 */
export function translateSqs(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
