/**
 * AWS Step Functions -> Azure Logic App / GCP Workflows translation.
 *
 * aws_sfn_state_machine -> Azure: azurerm_logic_app_workflow
 *                          GCP:   google_workflows_workflow
 *
 * ASL (Amazon States Language) definition content is NEVER included in
 * translated output; an advisory finding prompts manual translation.
 *
 * role_arn -> managed identity (Azure) / service account ref (GCP).
 * Logging/tracing config is mapped to target equivalents where possible.
 *
 * @module structural/stepfunctions-mapping
 * @generated by code-generator (TASK-GAP-010)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Mapped attribute keys
// ---------------------------------------------------------------------------

const MAPPED_KEYS: readonly string[] = [
  'name',
  'definition',
  'role_arn',
  'type',
  'logging_configuration',
  'tracing_configuration',
  'tags',
];

// ---------------------------------------------------------------------------
// Azure translation: azurerm_logic_app_workflow
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/stepfunctions', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const name = (attrs['name'] as string | undefined) ?? resource.sourceName;
  const sfnType = (attrs['type'] as string | undefined) ?? 'STANDARD';

  const azureAttrs: Record<string, unknown> = {
    location: '${azurerm_resource_group.main.location}',
    name,
    resource_group_name: '${azurerm_resource_group.main.name}',
  };

  // role_arn -> system-assigned managed identity
  if (attrs['role_arn'] !== undefined) {
    azureAttrs['identity'] = {
      type: 'SystemAssigned',
    };
  }

  // Logging configuration: enable diagnostics if logging was configured
  const loggingConfig = attrs['logging_configuration'] as Record<string, unknown> | undefined;
  if (loggingConfig) {
    azureAttrs['workflow_parameters'] = {
      '$connections': {},
    };
  }

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_logic_app_workflow',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'SFN_DEFINITION_MANUAL',
      'State machine definition (ASL) requires manual translation to Azure Logic App workflow definition; ' +
        'ASL is not included in translated output',
    ),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_sfn_state_machine -> 1 Azure resource (azurerm_logic_app_workflow)',
    ),
  ];

  if (sfnType === 'EXPRESS') {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'SFN_EXPRESS_TYPE',
        'AWS Step Functions EXPRESS type has shorter execution duration limits; ' +
          'Azure Logic App Consumption plan has similar limitations — verify workflow duration requirements',
      ),
    );
  }

  if (attrs['role_arn'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SFN_ROLE_ARN',
        'AWS role_arn mapped to Azure SystemAssigned managed identity; ' +
          'assign required RBAC roles to the Logic App managed identity after deployment',
      ),
    );
  }

  const tracingConfig = attrs['tracing_configuration'] as Record<string, unknown> | undefined;
  if (tracingConfig?.['enabled'] === true) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SFN_TRACING',
        'AWS X-Ray tracing has no direct Azure Logic App equivalent; ' +
          'enable Azure Monitor diagnostics on the Logic App for observability',
      ),
    );
  }

  if (loggingConfig) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SFN_LOGGING',
        'AWS Step Functions logging_configuration mapped to Azure Monitor diagnostics settings; ' +
          'configure azurerm_monitor_diagnostic_setting on the Logic App',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation: google_workflows_workflow
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/stepfunctions', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const name = (attrs['name'] as string | undefined) ?? resource.sourceName;

  const gcpAttrs: Record<string, unknown> = {
    description: `Migrated from aws_sfn_state_machine.${resource.sourceName}`,
    name,
    region: '${var.region}',
    // role_arn -> service account reference
    service_account: '${google_service_account.workflows_sa.email}',
    // ASL definition is NOT translated; placeholder source_contents is required
    source_contents: '# TODO: manually translate ASL definition to GCP Workflows YAML syntax',
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_workflows_workflow',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'warning',
      'SFN_DEFINITION_MANUAL',
      'State machine definition (ASL) requires manual translation to GCP Workflows YAML syntax; ' +
        'a TODO placeholder is included in source_contents',
    ),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_sfn_state_machine -> 1 GCP resource (google_workflows_workflow)',
    ),
  ];

  if (attrs['role_arn'] !== undefined) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SFN_ROLE_ARN',
        'AWS role_arn mapped to GCP service_account; ensure the Workflows service account has the required IAM bindings',
      ),
    );
  }

  const tracingConfig = attrs['tracing_configuration'] as Record<string, unknown> | undefined;
  if (tracingConfig?.['enabled'] === true) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SFN_TRACING',
        'AWS X-Ray tracing has no direct GCP Workflows equivalent; ' +
          'enable Cloud Trace integration via workflow steps or Cloud Logging',
      ),
    );
  }

  const loggingConfig = attrs['logging_configuration'] as Record<string, unknown> | undefined;
  if (loggingConfig) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'SFN_LOGGING',
        'AWS Step Functions logging_configuration mapped to GCP Cloud Logging; ' +
          'GCP Workflows emits execution logs automatically — configure log level in workflow execution settings',
      ),
    );
  }

  const sfnType = attrs['type'] as string | undefined;
  if (sfnType === 'EXPRESS') {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'SFN_EXPRESS_TYPE',
        'AWS Step Functions EXPRESS type targets high-throughput short-lived executions; ' +
          'GCP Workflows supports up to 1 year execution duration — verify workflow timeout requirements',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_sfn_state_machine to Azure Logic App Workflow
 * or GCP Workflows Workflow.
 *
 * The ASL definition is NEVER included in translated output; an advisory
 * finding (SFN_DEFINITION_MANUAL) is always emitted to prompt manual translation.
 */
export function translateStepFunctions(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
