/**
 * Pure IPv4 bitwise CIDR utilities for subnet validation.
 * Zero external imports -- all logic is self-contained.
 *
 * @module structural/subnet-cidr-validator
 * @generated by code-generator (TASK-NET-002)
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ParsedCidr {
  readonly network: number;
  readonly mask: number;
  readonly prefix: number;
}

// ---------------------------------------------------------------------------
// IPv6 detection
// ---------------------------------------------------------------------------

/**
 * Returns true if the CIDR string appears to be IPv6 (contains ':').
 */
export function isIpv6Cidr(cidr: string): boolean {
  if (typeof cidr !== 'string') return false;
  return cidr.includes(':');
}

// ---------------------------------------------------------------------------
// CIDR parsing
// ---------------------------------------------------------------------------

/**
 * Parses an IPv4 CIDR string (e.g. "10.0.1.0/24") into its numeric
 * network address, mask, and prefix length.
 *
 * Returns null for invalid input or IPv6 CIDRs.
 */
export function parseCidr(cidr: string): ParsedCidr | null {
  if (typeof cidr !== 'string' || cidr.length === 0) return null;
  if (isIpv6Cidr(cidr)) return null;

  const slashIdx = cidr.indexOf('/');
  if (slashIdx < 0) return null;

  const ipPart = cidr.slice(0, slashIdx);
  const prefixStr = cidr.slice(slashIdx + 1);

  // Validate prefix
  if (!/^\d{1,2}$/.test(prefixStr)) return null;
  const prefix = Number(prefixStr);
  if (prefix < 0 || prefix > 32) return null;

  // Parse octets
  const octets = ipPart.split('.');
  if (octets.length !== 4) return null;

  let ipNum = 0;
  for (const octet of octets) {
    if (!/^\d{1,3}$/.test(octet)) return null;
    const val = Number(octet);
    if (val < 0 || val > 255) return null;
    ipNum = ((ipNum << 8) | val) >>> 0;
  }

  const mask = prefix === 0 ? 0 : (~0 << (32 - prefix)) >>> 0;
  const network = (ipNum & mask) >>> 0;

  return { network, mask, prefix };
}

// ---------------------------------------------------------------------------
// Containment check
// ---------------------------------------------------------------------------

/**
 * Returns true if `inner` CIDR is fully contained within `outer` CIDR.
 * Returns null if either CIDR fails to parse.
 */
export function isCidrContained(inner: string, outer: string): boolean | null {
  const a = parseCidr(inner);
  const b = parseCidr(outer);
  if (!a || !b) return null;

  return ((a.network & b.mask) >>> 0) === b.network && a.prefix >= b.prefix;
}

// ---------------------------------------------------------------------------
// Overlap detection
// ---------------------------------------------------------------------------

/**
 * Returns true if two CIDRs overlap (share any addresses).
 * Returns null if either CIDR fails to parse.
 */
export function detectCidrOverlap(a: string, b: string): boolean | null {
  const pa = parseCidr(a);
  const pb = parseCidr(b);
  if (!pa || !pb) return null;

  // Use the shorter prefix (wider network) mask
  const shorterMask = pa.prefix <= pb.prefix ? pa.mask : pb.mask;
  return ((pa.network & shorterMask) >>> 0) === ((pb.network & shorterMask) >>> 0);
}
