/**
 * AWS Subnet -> Azure Subnet / GCP Subnetwork translation.
 * Structural mapper: handles CIDR containment validation, overlap detection,
 * AZ-to-zone mapping, and IPv6 advisory findings.
 *
 * Migrated from parametric/subnet-mapping with structural enhancements:
 * - CIDR containment check against parent VPC
 * - CIDR overlap detection across sibling subnets
 * - AZ -> Azure zone number / GCP zone string mapping
 * - IPv6 CIDR advisory
 * - STRUCTURAL_TOPOLOGY info finding
 *
 * @module structural/subnet-mapping
 * @generated by code-generator (TASK-NET-002)
 */

import type { TranslatedResource, TranslationFinding } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  transformRegion,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
  findSiblingVpc,
} from '../direct/attribute-transformer.js';
import { isCidrContained, detectCidrOverlap, isIpv6Cidr } from './subnet-cidr-validator.js';
import { mapAzToAzureZone, mapAzToGcpZone } from './subnet-az-mapper.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'cidr_block',
  'availability_zone',
  'vpc_id',
  'map_public_ip_on_launch',
  'ipv6_cidr_block',
  'tags',
];

// ---------------------------------------------------------------------------
// Shared finding helpers
// ---------------------------------------------------------------------------

/**
 * Validates subnet CIDR against parent VPC CIDR (containment) and scans
 * sibling subnets for overlap. Returns relevant findings.
 */
function validateCidr(
  ctx: TranslationContext,
  cidr: string,
): TranslationFinding[] {
  const findings: TranslationFinding[] = [];
  const { resource } = ctx;

  // --- Containment check against VPC ---
  const vpcRef = findSiblingVpc(ctx);
  const vpc = vpcRef
    ? ctx.siblingResources.find((r) => r.id === vpcRef.id)
    : undefined;
  if (vpc) {
    const vpcCidr = (vpc.attributes as Record<string, unknown>)['cidr_block'];
    if (typeof vpcCidr === 'string') {
      const contained = isCidrContained(cidr, vpcCidr);
      if (contained === false) {
        findings.push(
          createFinding(
            resource.id,
            'warning',
            'SUBNET_CIDR_NOT_IN_VPC',
            `Subnet CIDR ${cidr} is not contained within VPC CIDR ${vpcCidr}`,
          ),
        );
      }
    }
  }

  // --- Overlap check against sibling subnets ---
  for (const sibling of ctx.siblingResources) {
    if (sibling.sourceType !== 'aws_subnet') continue;
    if (sibling.id === resource.id) continue;
    const siblingCidr = (sibling.attributes as Record<string, unknown>)['cidr_block'];
    if (typeof siblingCidr !== 'string') continue;
    const overlaps = detectCidrOverlap(cidr, siblingCidr);
    if (overlaps === true) {
      findings.push(
        createFinding(
          resource.id,
          'warning',
          'SUBNET_CIDR_OVERLAP',
          `Subnet CIDR ${cidr} overlaps with sibling subnet ${sibling.sourceName} (${siblingCidr})`,
        ),
      );
    }
  }

  return findings;
}

/**
 * Checks for IPv6 CIDR block and emits an advisory finding.
 */
function checkIpv6(
  resourceId: string,
  attrs: Record<string, unknown>,
): TranslationFinding[] {
  const ipv6Cidr = attrs['ipv6_cidr_block'];
  if (typeof ipv6Cidr === 'string' && isIpv6Cidr(ipv6Cidr)) {
    return [
      createFinding(
        resourceId,
        'info',
        'SUBNET_IPV6_UNSUPPORTED',
        `IPv6 CIDR block (${ipv6Cidr}) requires manual configuration on the target provider`,
      ),
    ];
  }
  return [];
}

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/subnet', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const cidr = typeof attrs['cidr_block'] === 'string' ? attrs['cidr_block'] : '10.0.1.0/24';
  const az = typeof attrs['availability_zone'] === 'string' ? attrs['availability_zone'] : undefined;
  const vpc = findSiblingVpc(ctx);

  const azureAttrs: Record<string, unknown> = {
    address_prefixes: [cidr],
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    virtual_network_name: vpc
      ? `\${azurerm_virtual_network.${vpc.sourceName}.name}`
      : (attrs['vpc_id'] as string) ?? '',
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const findings: TranslationFinding[] = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    ...validateCidr(ctx, cidr),
    ...checkIpv6(resource.id, attrs),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_subnet -> 1 azurerm_subnet',
    ),
  ];

  // map_public_ip_on_launch has no direct Azure equivalent
  if (attrs['map_public_ip_on_launch'] === true) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'PUBLIC_IP_LAUNCH',
        'map_public_ip_on_launch requires a separate Azure Public IP association',
      ),
    );
  }

  // AZ mapping
  if (az) {
    const azureZone = mapAzToAzureZone(az);
    if (azureZone !== undefined) {
      findings.push(
        createFinding(
          resource.id,
          'info',
          'SUBNET_AZ_MAPPED',
          `AWS AZ ${az} mapped to Azure availability zone ${azureZone}`,
        ),
      );
    }
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_subnet',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/subnet', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const cidr = typeof attrs['cidr_block'] === 'string' ? attrs['cidr_block'] : '10.0.1.0/24';
  const az = typeof attrs['availability_zone'] === 'string' ? attrs['availability_zone'] : undefined;
  const vpc = findSiblingVpc(ctx);

  // Derive GCP region: strip the trailing AZ letter to recover the AWS region,
  // then map to GCP. AWS AZs append the letter without a hyphen (e.g. "us-east-1a").
  const awsRegion = az ? az.slice(0, -1) : 'us-east-1';
  const gcpRegion = transformRegion('gcp', awsRegion);

  const gcpAttrs: Record<string, unknown> = {
    ip_cidr_range: cidr,
    name: resource.sourceName,
    network: vpc
      ? `\${google_compute_network.${vpc.sourceName}.id}`
      : (attrs['vpc_id'] as string) ?? '',
    region: gcpRegion,
  };

  // private_ip_google_access: inverse of map_public_ip_on_launch
  if (attrs['map_public_ip_on_launch'] === false) {
    gcpAttrs['private_ip_google_access'] = true;
  }

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const findings: TranslationFinding[] = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    ...validateCidr(ctx, cidr),
    ...checkIpv6(resource.id, attrs),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_subnet -> 1 google_compute_subnetwork',
    ),
  ];

  // AZ mapping
  if (az) {
    const gcpZone = mapAzToGcpZone(az);
    if (gcpZone !== undefined) {
      findings.push(
        createFinding(
          resource.id,
          'info',
          'SUBNET_AZ_MAPPED',
          `AWS AZ ${az} mapped to GCP zone ${gcpZone}`,
        ),
      );
    }
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_subnetwork',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_subnet resource to Azure or GCP equivalents.
 * Enhanced from parametric mapper: CIDR validation, overlap detection,
 * AZ mapping, IPv6 advisory, structural topology.
 */
export function translateSubnet(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
