/**
 * AWS VPC -> Azure Virtual Network / GCP Compute Network translation.
 * Structural mapper: handles multi-CIDR address spaces and topology reshaping.
 *
 * Migrated from parametric/vpc-mapping with enhancements:
 * - Multi-CIDR: secondary_cidr_blocks -> address_space array
 * - Azure: azurerm_virtual_network with multi-element address_space
 * - GCP: google_compute_network, auto_create_subnetworks: false
 *
 * @module structural/vpc-mapping
 * @generated by code-generator (TASK-NET-001)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  transformRegion,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'cidr_block',
  'enable_dns_hostnames',
  'enable_dns_support',
  'instance_tenancy',
  'secondary_cidr_blocks',
  'tags',
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Builds the full list of CIDR blocks: primary + any secondary.
 */
interface CidrListResult {
  readonly cidrs: string[];
  readonly primaryMissing: boolean;
}

function buildCidrList(attrs: Record<string, unknown>): CidrListResult {
  const rawPrimary = attrs['cidr_block'];
  const primaryMissing = typeof rawPrimary !== 'string' || rawPrimary.length === 0;
  const primary = primaryMissing ? '10.0.0.0/16' : (rawPrimary as string);
  const secondary = attrs['secondary_cidr_blocks'] as readonly string[] | undefined;
  const cidrs = [primary];
  if (Array.isArray(secondary)) {
    for (const s of secondary) {
      if (typeof s === 'string' && s.length > 0) {
        cidrs.push(s);
      }
    }
  }
  return { cidrs, primaryMissing };
}

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/vpc', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const { cidrs, primaryMissing } = buildCidrList(attrs);

  const azureAttrs: Record<string, unknown> = {
    address_space: cidrs,
    location: transformRegion('azure', 'us-east-1'),
    name: resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
  };

  // DNS settings: Azure VNet has dns_servers attribute (empty = Azure-provided)
  const dnsSupport = attrs['enable_dns_support'];
  const dnsHostnames = attrs['enable_dns_hostnames'];
  if (dnsSupport === false || dnsHostnames === false) {
    azureAttrs['dns_servers'] = [];
  }

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_virtual_network',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_vpc -> 1 azurerm_virtual_network (${cidrs.length} CIDR block(s) in address_space)`,
    ),
  ];

  // Missing primary CIDR advisory
  if (primaryMissing) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'VPC_CIDR_MISSING',
        'cidr_block is missing or empty; defaulting to 10.0.0.0/16',
      ),
    );
  }

  // Tenancy advisory
  const tenancy = attrs['instance_tenancy'] as string | undefined;
  if (tenancy && tenancy !== 'default') {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'VPC_TENANCY_UNSUPPORTED',
        `instance_tenancy '${tenancy}' has no direct Azure equivalent; defaults to shared hosting`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/vpc', 'structural');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const gcpAttrs: Record<string, unknown> = {
    auto_create_subnetworks: false,
    name: resource.sourceName,
    routing_mode: 'REGIONAL',
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_network',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const { cidrs, primaryMissing } = buildCidrList(attrs);

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      `1 aws_vpc -> 1 google_compute_network (CIDR applied at subnet level in GCP)`,
    ),
  ];

  // Missing primary CIDR advisory
  if (primaryMissing) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'VPC_CIDR_MISSING',
        'cidr_block is missing or empty; defaulting to 10.0.0.0/16',
      ),
    );
  }

  // GCP VPC has no CIDR — CIDRs are applied at subnet level
  if (cidrs.length > 1) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'VPC_MULTI_CIDR_GCP',
        `${cidrs.length} CIDR blocks detected; GCP VPC is CIDR-less — CIDRs must be assigned to subnets`,
      ),
    );
  }

  // Tenancy advisory
  const tenancy = attrs['instance_tenancy'] as string | undefined;
  if (tenancy && tenancy !== 'default') {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'VPC_TENANCY_UNSUPPORTED',
        `instance_tenancy '${tenancy}' has no direct GCP equivalent; defaults to shared hosting`,
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_vpc to Azure Virtual Network or GCP Compute Network.
 * Enhanced from parametric mapper: handles multi-CIDR, tenancy advisories.
 */
export function translateVpc(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
