/**
 * AWS WAFv2 WebACL / Rule Group -> Azure WAF Policy / GCP Cloud Armor translation.
 *
 * Azure: 1 resource (azurerm_web_application_firewall_policy).
 * GCP:   1 resource (google_compute_security_policy).
 *
 * Mapping:
 * - default_action (allow / block) -> target default action
 * - name -> target resource name
 * - Custom rules -> translated to rule objects within the policy
 * - Managed rule groups -> advisory finding WAF_MANAGED_RULES_ADVISORY
 *   (vendor-specific rule sets cannot be auto-translated)
 *
 * @module structural/waf-mapping
 * @generated by code-generator (TASK-GAP-009)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
  emitBehavioralGapFindings,
} from '../direct/attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'default_action',
  'description',
  'name',
  'rule',
  'tags',
  'visibility_config',
];

// ---------------------------------------------------------------------------
// Rule type definitions (mirrors AWS WAFv2 rule shape)
// ---------------------------------------------------------------------------

interface WafRule {
  readonly name?: string;
  readonly priority?: number;
  readonly action?: { allow?: unknown; block?: unknown; count?: unknown };
  readonly statement?: {
    managed_rule_group_statement?: { vendor_name?: string; name?: string };
    [key: string]: unknown;
  };
  readonly visibility_config?: unknown;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Returns true if any rule uses a managed_rule_group_statement, meaning
 * vendor-specific (AWS-managed) rules are in play.
 */
function hasManagedRuleGroups(rules: readonly WafRule[]): boolean {
  return rules.some(r => r.statement?.managed_rule_group_statement !== undefined);
}

/**
 * Determine default action string from the AWS default_action attribute.
 * AWS shape: { allow: {} } or { block: {} }
 */
function resolveDefaultAction(defaultAction: unknown): 'allow' | 'block' {
  if (defaultAction && typeof defaultAction === 'object') {
    const action = defaultAction as Record<string, unknown>;
    if ('block' in action) return 'block';
  }
  return 'allow';
}

/**
 * Map rule action to a simple allow/block/count string.
 */
function resolveRuleAction(action: WafRule['action']): 'allow' | 'block' | 'count' {
  if (!action) return 'allow';
  if ('block' in action) return 'block';
  if ('count' in action) return 'count';
  return 'allow';
}

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/waf', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const defaultAction = resolveDefaultAction(attrs['default_action']);
  const rules = (attrs['rule'] as WafRule[] | undefined) ?? [];

  // Build Azure custom rules from non-managed-rule-group rules
  const customRules: Record<string, unknown>[] = [];
  let azurePriority = 1;
  for (const rule of rules) {
    if (rule.statement?.managed_rule_group_statement) continue; // advisory only

    const action = resolveRuleAction(rule.action);
    if (action === 'count') continue; // count mode has no Azure equivalent in policy rules

    customRules.push({
      action: action === 'block' ? 'Block' : 'Allow',
      match_conditions: [],
      name: rule.name ?? `rule-${azurePriority}`,
      priority: rule.priority ?? azurePriority,
      rule_type: 'MatchRule',
    });
    azurePriority++;
  }

  const policyAttrs: Record<string, unknown> = {
    location: '${azurerm_resource_group.main.location}',
    name: sourceName,
    policy_settings: {
      enabled: true,
      mode: defaultAction === 'block' ? 'Prevention' : 'Detection',
    },
    resource_group_name: '${azurerm_resource_group.main.name}',
  };

  if (customRules.length > 0) {
    policyAttrs['custom_rules'] = customRules;
  }
  if (tags) policyAttrs['tags'] = transformTags('azure', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_web_application_firewall_policy',
      targetName: sourceName,
      attributes: policyAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = buildCommonFindings(ctx, rules);
  findings.push(
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_wafv2_web_acl -> 1 azurerm_web_application_firewall_policy',
    ),
  );

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'structural/waf', 'structural');
  const sourceName = resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const defaultAction = resolveDefaultAction(attrs['default_action']);
  const rules = (attrs['rule'] as WafRule[] | undefined) ?? [];

  // Build GCP security policy rules from non-managed-rule-group rules
  const gcpRules: Record<string, unknown>[] = [];
  for (const rule of rules) {
    if (rule.statement?.managed_rule_group_statement) continue; // advisory only

    const action = resolveRuleAction(rule.action);
    gcpRules.push({
      action: action === 'block' ? 'deny(403)' : 'allow',
      description: rule.name ?? '',
      match: {
        config: { src_ip_ranges: ['*'] },
        versioned_expr: 'SRC_IPS_V1',
      },
      priority: rule.priority ?? 1000,
    });
  }

  // Default rule (lowest priority = 2147483647 in GCP)
  gcpRules.push({
    action: defaultAction === 'block' ? 'deny(403)' : 'allow',
    description: 'default rule',
    match: {
      config: { src_ip_ranges: ['*'] },
      versioned_expr: 'SRC_IPS_V1',
    },
    priority: 2147483647,
  });

  const policyAttrs: Record<string, unknown> = {
    name: sourceName,
    project: '${var.project_id}',
    rule: gcpRules,
  };
  if (tags) policyAttrs['labels'] = transformTags('gcp', tags);

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_compute_security_policy',
      targetName: sourceName,
      attributes: policyAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = buildCommonFindings(ctx, rules);
  findings.push(
    createFinding(
      resource.id,
      'info',
      'STRUCTURAL_TOPOLOGY',
      '1 aws_wafv2_web_acl -> 1 google_compute_security_policy',
    ),
  );

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Shared advisory findings builder
// ---------------------------------------------------------------------------

function buildCommonFindings(ctx: TranslationContext, rules: readonly WafRule[]) {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;

  const findings = [
    ...collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS),
    ...emitBehavioralGapFindings(ctx),
  ];

  if (hasManagedRuleGroups(rules)) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'WAF_MANAGED_RULES_ADVISORY',
        'WAF managed rule groups (vendor-specific rulesets) cannot be auto-translated; review and configure equivalent managed rules on the target provider manually',
      ),
    );
  }

  return findings;
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates aws_wafv2_web_acl or aws_wafv2_rule_group to the target
 * provider's WAF/security-policy resource.
 */
export function translateWaf(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}

/**
 * Structural mapper export — consumed by structural-engine dispatch table.
 */
export const wafMapper = translateWaf;
