/**
 * Route53 Zone / Record -> Azure DNS / GCP Cloud DNS translation.
 *
 * @module direct/dns-mapping
 * @generated by code-generator (TASK-TRANS-002)
 */

import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
} from './attribute-transformer.js';

// ---------------------------------------------------------------------------
// Mapped keys
// ---------------------------------------------------------------------------

const ZONE_MAPPED_KEYS: readonly string[] = [
  'name',
  'comment',
  'force_destroy',
  'tags',
  'vpc',
];

const RECORD_MAPPED_KEYS: readonly string[] = [
  'zone_id',
  'name',
  'type',
  'ttl',
  'records',
  'alias',
  'weighted_routing_policy',
  'failover_routing_policy',
  'health_check_id',
  'set_identifier',
];

// ---------------------------------------------------------------------------
// Azure record type mapping
// ---------------------------------------------------------------------------

const AZURE_RECORD_TYPE_MAP: ReadonlyMap<string, string> = new Map([
  ['A', 'azurerm_dns_a_record'],
  ['AAAA', 'azurerm_dns_aaaa_record'],
  ['CNAME', 'azurerm_dns_cname_record'],
  ['MX', 'azurerm_dns_mx_record'],
  ['TXT', 'azurerm_dns_txt_record'],
  ['NS', 'azurerm_dns_ns_record'],
  ['SRV', 'azurerm_dns_srv_record'],
  ['PTR', 'azurerm_dns_ptr_record'],
  ['CAA', 'azurerm_dns_caa_record'],
]);

// ---------------------------------------------------------------------------
// Zone translation
// ---------------------------------------------------------------------------

function translateZoneToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/dns');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const azureAttrs: Record<string, unknown> = {
    name: attrs['name'] ?? resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const findings = collectUnmappedAttrs(resource.id, attrs, ZONE_MAPPED_KEYS);

  return {
    translated: [
      {
        targetType: 'azurerm_dns_zone',
        targetName: resource.sourceName,
        attributes: azureAttrs,
        sourceId: resource.id,
        traceability,
      },
    ],
    findings,
  };
}

function translateZoneToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/dns');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const zoneName = (attrs['name'] as string | undefined) ?? resource.sourceName;
  const gcpAttrs: Record<string, unknown> = {
    description: (attrs['comment'] as string | undefined) ?? '',
    dns_name: zoneName.endsWith('.') ? zoneName : `${zoneName}.`,
    name: resource.sourceName.replace(/[^a-z0-9-]/gi, '-').toLowerCase(),
  };

  // Private zone detection
  const vpc = attrs['vpc'] as unknown;
  if (vpc !== undefined) {
    gcpAttrs['visibility'] = 'private';
  }

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const findings = collectUnmappedAttrs(resource.id, attrs, ZONE_MAPPED_KEYS);

  return {
    translated: [
      {
        targetType: 'google_dns_managed_zone',
        targetName: resource.sourceName,
        attributes: gcpAttrs,
        sourceId: resource.id,
        traceability,
      },
    ],
    findings,
  };
}

// ---------------------------------------------------------------------------
// Record translation
// ---------------------------------------------------------------------------

function translateRecordToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/dns');
  const findings = collectUnmappedAttrs(resource.id, attrs, RECORD_MAPPED_KEYS);

  const recordType = (attrs['type'] as string | undefined) ?? 'A';
  const alias = attrs['alias'] as Record<string, unknown> | undefined;

  // Alias records are not directly portable
  if (alias) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DNS_ALIAS_NOT_PORTABLE',
        'Route53 alias records have no direct equivalent in Azure DNS; translated as CNAME',
      ),
    );
  }

  const azureType = alias
    ? 'azurerm_dns_cname_record'
    : AZURE_RECORD_TYPE_MAP.get(recordType) ?? 'azurerm_dns_a_record';

  const azureAttrs: Record<string, unknown> = {
    name: attrs['name'] ?? resource.sourceName,
    resource_group_name: '${azurerm_resource_group.main.name}',
    ttl: attrs['ttl'] ?? 300,
    zone_name: '${azurerm_dns_zone.main.name}',
  };

  if (alias) {
    azureAttrs['record'] = alias['name'] ?? '';
  } else {
    const records = attrs['records'] as string[] | undefined;
    if (records) {
      azureAttrs['records'] = [...records].sort();
    }
  }

  return {
    translated: [
      {
        targetType: azureType,
        targetName: resource.sourceName,
        attributes: azureAttrs,
        sourceId: resource.id,
        traceability,
      },
    ],
    findings,
  };
}

function translateRecordToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/dns');
  const findings = collectUnmappedAttrs(resource.id, attrs, RECORD_MAPPED_KEYS);

  const recordType = (attrs['type'] as string | undefined) ?? 'A';
  const alias = attrs['alias'] as Record<string, unknown> | undefined;

  if (alias) {
    findings.push(
      createFinding(
        resource.id,
        'warning',
        'DNS_ALIAS_NOT_PORTABLE',
        'Route53 alias records have no direct equivalent in GCP Cloud DNS; translated as CNAME',
      ),
    );
  }

  const gcpAttrs: Record<string, unknown> = {
    managed_zone: '${google_dns_managed_zone.main.name}',
    name: attrs['name'] ?? resource.sourceName,
    ttl: attrs['ttl'] ?? 300,
    type: alias ? 'CNAME' : recordType,
  };

  if (alias) {
    const aliasName = (alias['name'] as string) ?? '';
    gcpAttrs['rrdatas'] = [aliasName.endsWith('.') ? aliasName : `${aliasName}.`];
  } else {
    const records = attrs['records'] as string[] | undefined;
    if (records) {
      gcpAttrs['rrdatas'] = [...records].sort();
    }
  }

  return {
    translated: [
      {
        targetType: 'google_dns_record_set',
        targetName: resource.sourceName,
        attributes: gcpAttrs,
        sourceId: resource.id,
        traceability,
      },
    ],
    findings,
  };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates aws_route53_zone or aws_route53_record to Azure or GCP equivalents.
 */
export function translateDns(ctx: TranslationContext): EngineResult {
  const isZone = ctx.resource.sourceType === 'aws_route53_zone';

  if (ctx.targetProvider === 'azure') {
    return isZone ? translateZoneToAzure(ctx) : translateRecordToAzure(ctx);
  }
  return isZone ? translateZoneToGcp(ctx) : translateRecordToGcp(ctx);
}
