/**
 * ECR repository -> Azure Container Registry / GCP Artifact Registry translation.
 *
 * @module direct/ecr-mapping
 * @generated by code-generator (TASK-TRANS-002)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
} from './attribute-transformer.js';

const MAPPED_KEYS: readonly string[] = [
  'name',
  'image_tag_mutability',
  'encryption_configuration',
  'image_scanning_configuration',
  'tags',
  'force_delete',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/ecr');

  const repoName = (attrs['name'] as string | undefined) ?? resource.sourceName;
  const tagMutability = attrs['image_tag_mutability'] as string | undefined;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const azureAttrs: Record<string, unknown> = {
    admin_enabled: tagMutability === 'IMMUTABLE' ? false : true,
    name: repoName.replace(/[^a-zA-Z0-9]/g, ''),
    sku: 'Basic',
  };

  // Encryption -> premium SKU with CMK
  const encryption = attrs['encryption_configuration'] as
    | Record<string, unknown>
    | undefined;
  if (encryption?.['kms_key'] !== undefined) {
    azureAttrs['sku'] = 'Premium';
    azureAttrs['encryption'] = {
      key_vault_key_id: encryption['kms_key'],
    };
  }

  // Image scanning -> trust policy
  const scanning = attrs['image_scanning_configuration'] as
    | Record<string, unknown>
    | undefined;
  if (scanning?.['scan_on_push'] === true) {
    azureAttrs['trust_policy'] = { enabled: true };
  }

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_container_registry',
      targetName: resource.sourceName,
      attributes: azureAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS);

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/ecr');

  const repoName = (attrs['name'] as string | undefined) ?? resource.sourceName;
  const tagMutability = attrs['image_tag_mutability'] as string | undefined;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const gcpAttrs: Record<string, unknown> = {
    format: 'DOCKER',
    mode: tagMutability === 'IMMUTABLE' ? 'STANDARD_REPOSITORY' : 'STANDARD_REPOSITORY',
    repository_id: repoName,
  };

  // Encryption
  const encryption = attrs['encryption_configuration'] as
    | Record<string, unknown>
    | undefined;
  if (encryption?.['kms_key'] !== undefined) {
    gcpAttrs['kms_key_name'] = encryption['kms_key'];
  }

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_artifact_registry_repository',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS);

  // Image scanning not directly supported in Artifact Registry
  const scanning = attrs['image_scanning_configuration'] as
    | Record<string, unknown>
    | undefined;
  if (scanning?.['scan_on_push'] === true) {
    findings.push(
      createFinding(
        resource.id,
        'info',
        'ECR_SCAN_ON_PUSH',
        'GCP Artifact Registry uses Container Analysis for vulnerability scanning (separate resource)',
      ),
    );
  }

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_ecr_repository resource to Azure or GCP equivalents.
 */
export function translateEcr(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
