/**
 * VPC Peering -> Azure VNet Peering / GCP Network Peering translation.
 *
 * @module direct/peering-mapping
 * @generated by code-generator (TASK-TRANS-002)
 */

import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  collectUnmappedAttrs,
  createFinding,
  makeTraceability,
} from './attribute-transformer.js';

const MAPPED_KEYS: readonly string[] = [
  'peer_vpc_id',
  'vpc_id',
  'peer_owner_id',
  'peer_region',
  'auto_accept',
  'tags',
  'accepter',
  'requester',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/peering');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const azureAttrs: Record<string, unknown> = {
    allow_forwarded_traffic: true,
    allow_virtual_network_access: true,
    name: resource.sourceName,
    remote_virtual_network_id: attrs['peer_vpc_id'] ?? '',
    resource_group_name: '${azurerm_resource_group.main.name}',
    virtual_network_name: attrs['vpc_id'] ?? '',
  };

  if (tags) {
    azureAttrs['tags'] = transformTags('azure', tags);
  }

  const findings = collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS);
  findings.push(
    createFinding(
      resource.id,
      'warning',
      'PEERING_NON_TRANSITIVE',
      'VNet/VPC peering is non-transitive in all providers; verify hub-spoke topology is replicated',
    ),
  );

  return {
    translated: [
      {
        targetType: 'azurerm_virtual_network_peering',
        targetName: resource.sourceName,
        attributes: azureAttrs,
        sourceId: resource.id,
        traceability,
      },
    ],
    findings,
  };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/peering');
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const gcpAttrs: Record<string, unknown> = {
    export_custom_routes: true,
    import_custom_routes: true,
    name: resource.sourceName,
    network: attrs['vpc_id'] ?? '',
    peer_network: attrs['peer_vpc_id'] ?? '',
  };

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const findings = collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS);
  findings.push(
    createFinding(
      resource.id,
      'warning',
      'PEERING_NON_TRANSITIVE',
      'VPC peering is non-transitive in all providers; verify hub-spoke topology is replicated',
    ),
  );

  return {
    translated: [
      {
        targetType: 'google_compute_network_peering',
        targetName: resource.sourceName,
        attributes: gcpAttrs,
        sourceId: resource.id,
        traceability,
      },
    ],
    findings,
  };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_vpc_peering_connection to Azure or GCP equivalents.
 */
export function translatePeering(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
