/**
 * S3 bucket -> Azure Storage / GCP Storage Bucket translation.
 * Azure emits 2 resources (storage_account + storage_container).
 * GCP emits 1 resource (google_storage_bucket).
 *
 * @module direct/s3-mapping
 * @generated by code-generator (TASK-TRANS-002)
 */

import type { TranslatedResource } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  transformRegion,
  collectUnmappedAttrs,
  makeTraceability,
} from './attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'bucket',
  'region',
  'acl',
  'versioning',
  'lifecycle_rule',
  'cors_rule',
  'server_side_encryption_configuration',
  'logging',
  'tags',
  'replication_configuration',
  'force_destroy',
  'acceleration_status',
  'request_payer',
  'object_lock_configuration',
  'website',
];

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/s3');

  const bucketName = (attrs['bucket'] as string | undefined) ?? resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  // Derive replication type from replication config
  const replicationConfig = attrs['replication_configuration'] as
    | Record<string, unknown>
    | undefined;
  const accountReplicationType = replicationConfig ? 'GRS' : 'LRS';

  // Versioning
  const versioning = attrs['versioning'] as
    | Record<string, unknown>
    | undefined;
  const versioningEnabled = versioning?.['enabled'] === true;

  // Storage account attributes
  const accountAttrs: Record<string, unknown> = {
    account_kind: 'StorageV2',
    account_replication_type: accountReplicationType,
    account_tier: 'Standard',
    location: transformRegion('azure', (attrs['region'] as string) ?? 'us-east-1'),
    name: bucketName.replace(/[^a-z0-9]/g, '').slice(0, 24),
  };

  if (versioningEnabled) {
    accountAttrs['blob_properties'] = {
      versioning_enabled: true,
    };
  }

  if (tags) {
    accountAttrs['tags'] = transformTags('azure', tags);
  }

  // Container attributes
  const containerAttrs: Record<string, unknown> = {
    container_access_type: 'private',
    name: bucketName,
    storage_account_name: accountAttrs['name'],
  };

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_storage_account',
      targetName: `${resource.sourceName}_account`,
      attributes: accountAttrs,
      sourceId: resource.id,
      traceability,
    },
    {
      targetType: 'azurerm_storage_container',
      targetName: `${resource.sourceName}_container`,
      attributes: containerAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS);

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/s3');

  const bucketName = (attrs['bucket'] as string | undefined) ?? resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;
  const region = (attrs['region'] as string | undefined) ?? 'us-east-1';

  const gcpAttrs: Record<string, unknown> = {
    location: transformRegion('gcp', region),
    name: bucketName,
    storage_class: 'STANDARD',
  };

  // Versioning
  const versioning = attrs['versioning'] as
    | Record<string, unknown>
    | undefined;
  if (versioning?.['enabled'] === true) {
    gcpAttrs['versioning'] = { enabled: true };
  }

  // Lifecycle rules
  const lifecycleRules = attrs['lifecycle_rule'] as unknown[] | undefined;
  if (Array.isArray(lifecycleRules) && lifecycleRules.length > 0) {
    gcpAttrs['lifecycle_rule'] = lifecycleRules.map((rule) => {
      const r = rule as Record<string, unknown>;
      const condition: Record<string, unknown> = {};
      const action: Record<string, unknown> = {};

      const expiration = r['expiration'] as Record<string, unknown> | undefined;
      if (expiration?.['days'] !== undefined) {
        condition['age'] = expiration['days'];
      }
      const transition = r['transition'] as Record<string, unknown> | undefined;
      if (transition?.['storage_class']) {
        action['type'] = 'SetStorageClass';
        action['storage_class'] = transition['storage_class'];
      } else {
        action['type'] = 'Delete';
      }

      return { action, condition };
    });
  }

  // CORS
  const corsRules = attrs['cors_rule'] as unknown[] | undefined;
  if (Array.isArray(corsRules) && corsRules.length > 0) {
    gcpAttrs['cors'] = corsRules.map((rule) => {
      const r = rule as Record<string, unknown>;
      return {
        max_age_seconds: r['max_age_seconds'] ?? 3600,
        method: r['allowed_methods'] ?? [],
        origin: r['allowed_origins'] ?? [],
        response_header: r['allowed_headers'] ?? [],
      };
    });
  }

  // Encryption
  const encryption = attrs['server_side_encryption_configuration'] as
    | Record<string, unknown>
    | undefined;
  if (encryption) {
    const rule = encryption['rule'] as Record<string, unknown> | undefined;
    const kmsKeyId = (
      rule?.['apply_server_side_encryption_by_default'] as
        | Record<string, unknown>
        | undefined
    )?.['kms_master_key_id'];
    if (typeof kmsKeyId === 'string') {
      gcpAttrs['encryption'] = { default_kms_key_name: kmsKeyId };
    }
  }

  // Logging
  const logging = attrs['logging'] as Record<string, unknown> | undefined;
  if (logging) {
    gcpAttrs['logging'] = {
      log_bucket: logging['target_bucket'] ?? '',
      log_object_prefix: logging['target_prefix'] ?? '',
    };
  }

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_storage_bucket',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS);

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_s3_bucket resource to Azure or GCP equivalents.
 */
export function translateS3(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
