/**
 * S3 bucket -> Azure Storage / GCP Storage Bucket translation.
 * Azure emits 2 resources (storage_account + storage_container).
 * GCP emits 1 resource (google_storage_bucket).
 *
 * @module direct/s3-mapping
 * @generated by code-generator (TASK-TRANS-002)
 */

import type { TranslatedResource, TranslationContract } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import {
  transformTags,
  transformRegion,
  collectUnmappedAttrs,
  makeTraceability,
  createFinding,
} from './attribute-transformer.js';

// Keys we explicitly handle during mapping
const MAPPED_KEYS: readonly string[] = [
  'bucket',
  'region',
  'acl',
  'versioning',
  'lifecycle_rule',
  'cors_rule',
  'server_side_encryption_configuration',
  'logging',
  'tags',
  'replication_configuration',
  'force_destroy',
  'acceleration_status',
  'request_payer',
  'object_lock_configuration',
  'website',
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sanitizeAzureName(raw: string, resourceId: string): { name: string; sanitized: boolean } {
  let name = raw.replace(/[^a-z0-9]/g, '').slice(0, 24);
  if (name.length < 3) {
    const hash = resourceId.replace(/[^a-z0-9]/g, '').slice(0, 4);
    name = (name + hash).slice(0, 24).padEnd(3, '0');
  }
  return { name, sanitized: name !== raw };
}

function mapAclToContainerAccess(acl: string | undefined): { access: string; findings: Array<ReturnType<typeof createFinding>> } {
  const findings: Array<ReturnType<typeof createFinding>> = [];
  if (!acl || acl === 'private') return { access: 'private', findings };
  if (acl === 'public-read') return { access: 'blob', findings };
  if (acl === 'public-read-write') {
    findings.push(createFinding('', 'warning', 'S3_PUBLIC_ACCESS', 'public-read-write ACL detected — container has full public access'));
    return { access: 'container', findings };
  }
  findings.push(createFinding('', 'info', 'S3_ACL_UNSUPPORTED', `ACL '${acl}' has no direct Azure mapping — defaulting to private`));
  return { access: 'private', findings };
}

function buildS3Contract(
  resourceId: string,
  attrs: Record<string, unknown>,
  translated: readonly TranslatedResource[],
  findings: readonly ReturnType<typeof createFinding>[],
): TranslationContract {
  const preserved: string[] = ['bucket/container storage intent preserved'];
  const transformed: string[] = [];
  const degraded: string[] = [];
  const reviewRequired: string[] = [];
  const blockers: string[] = findings.filter((f) => f.severity === 'blocker').map((f) => f.message);
  const confidenceFactors: string[] = [];

  if ((attrs['versioning'] as Record<string, unknown> | undefined)?.['enabled'] === true) {
    preserved.push('object versioning intent preserved');
  }

  if (attrs['logging']) {
    preserved.push('access logging intent carried into target bucket/account logging configuration');
  }

  if (attrs['lifecycle_rule']) {
    transformed.push('lifecycle rules translated into target lifecycle constructs');
    confidenceFactors.push('complex lifecycle semantics should be validated after translation');
  }

  if (attrs['website']) {
    degraded.push('static website hosting requires manual target-side verification');
    reviewRequired.push('verify website hosting endpoint and index/error document behaviour');
    confidenceFactors.push('website hosting semantics differ by provider');
  }

  if (attrs['server_side_encryption_configuration']) {
    transformed.push('bucket encryption intent carried forward');
    reviewRequired.push('verify customer-managed KMS key mapping');
    confidenceFactors.push('customer-managed key semantics require review');
  }

  if (attrs['replication_configuration']) {
    degraded.push('replication rules are only partially preserved');
    reviewRequired.push('validate cross-region replication requirements');
    confidenceFactors.push('replication behaviour is provider-specific');
  }

  if (attrs['object_lock_configuration']) {
    degraded.push('object lock / immutability semantics are not directly preserved');
    reviewRequired.push('confirm immutable storage or retention policy equivalent');
    confidenceFactors.push('object lock has no exact cross-cloud equivalent');
  }

  const acl = attrs['acl'] as string | undefined;
  if (acl && acl !== 'private') {
    transformed.push(`ACL posture '${acl}' translated into provider-specific access semantics`);
    reviewRequired.push('review public or IAM access posture after translation');
    confidenceFactors.push('ACL semantics differ from target access-control model');
  }

  return {
    sourceId: resourceId,
    targetIds: translated.map((r) => r.targetName),
    preserved,
    transformed,
    degraded,
    blockers,
    reviewRequired,
    confidenceFactors,
  };
}

// ---------------------------------------------------------------------------
// Azure translation
// ---------------------------------------------------------------------------

function translateToAzure(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/s3');

  const bucketName = (attrs['bucket'] as string | undefined) ?? resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;

  const replicationConfig = attrs['replication_configuration'] as Record<string, unknown> | undefined;
  const accountReplicationType = replicationConfig ? 'GRS' : 'LRS';

  const versioning = attrs['versioning'] as Record<string, unknown> | undefined;
  const versioningEnabled = versioning?.['enabled'] === true;

  const { name: accountName, sanitized } = sanitizeAzureName(bucketName, resource.id);
  const encryption = attrs['server_side_encryption_configuration'] as Record<string, unknown> | undefined;

  const accountAttrs: Record<string, unknown> = {
    account_kind: 'StorageV2',
    account_replication_type: accountReplicationType,
    account_tier: 'Standard',
    location: transformRegion('azure', (attrs['region'] as string) ?? 'us-east-1'),
    name: accountName,
  };

  if (versioningEnabled) {
    accountAttrs['blob_properties'] = {
      versioning_enabled: true,
    };
  }

  if (tags) {
    accountAttrs['tags'] = transformTags('azure', tags);
  }

  const acl = attrs['acl'] as string | undefined;
  const { access: containerAccess, findings: aclFindings } = mapAclToContainerAccess(acl);
  for (const f of aclFindings) f.resourceId = resource.id;

  const containerAttrs: Record<string, unknown> = {
    container_access_type: containerAccess,
    name: bucketName,
    storage_account_name: accountAttrs['name'],
  };

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_storage_account',
      targetName: `${resource.sourceName}_account`,
      attributes: accountAttrs,
      sourceId: resource.id,
      traceability,
    },
    {
      targetType: 'azurerm_storage_container',
      targetName: `${resource.sourceName}_container`,
      attributes: containerAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS);

  if (sanitized) findings.push(createFinding(resource.id, 'info', 'S3_NAME_SANITIZED', `Storage account name sanitized from '${bucketName}' to '${accountName}'`));
  findings.push(...aclFindings);
  if (attrs['website']) findings.push(createFinding(resource.id, 'warning', 'S3_WEBSITE_HOSTING', 'S3 static website hosting maps to Azure Static Web Apps or blob $web container — manual configuration required'));
  if (attrs['object_lock_configuration']) findings.push(createFinding(resource.id, 'warning', 'S3_OBJECT_LOCK_UNSUPPORTED', 'S3 Object Lock has no direct Azure equivalent — use Azure Immutable Blob Storage'));
  if (attrs['request_payer'] === 'Requester') findings.push(createFinding(resource.id, 'info', 'S3_REQUESTER_PAYS', 'Requester Pays has no equivalent on Azure'));
  if (replicationConfig) findings.push(createFinding(resource.id, 'info', 'S3_REPLICATION_PARTIAL', 'S3 replication mapped to GRS — cross-region rules not individually translated'));
  if (encryption) findings.push(createFinding(resource.id, 'warning', 'S3_ENCRYPTION_KMS', 'Customer-managed KMS key detected — verify Azure Key Vault mapping'));

  return {
    translated,
    findings,
    contracts: [buildS3Contract(resource.id, attrs, translated, findings)],
  };
}

// ---------------------------------------------------------------------------
// GCP translation
// ---------------------------------------------------------------------------

function translateToGcp(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  const attrs = resource.attributes as Record<string, unknown>;
  const traceability = makeTraceability(ctx, 'direct/s3');

  const bucketName = (attrs['bucket'] as string | undefined) ?? resource.sourceName;
  const tags = attrs['tags'] as Record<string, string> | undefined;
  const region = (attrs['region'] as string | undefined) ?? 'us-east-1';

  const gcpAttrs: Record<string, unknown> = {
    location: transformRegion('gcp', region),
    name: bucketName,
    storage_class: 'STANDARD',
  };

  const versioning = attrs['versioning'] as Record<string, unknown> | undefined;
  if (versioning?.['enabled'] === true) {
    gcpAttrs['versioning'] = { enabled: true };
  }

  const lifecycleRules = attrs['lifecycle_rule'] as unknown[] | undefined;
  if (Array.isArray(lifecycleRules) && lifecycleRules.length > 0) {
    gcpAttrs['lifecycle_rule'] = lifecycleRules.map((rule) => {
      const r = rule as Record<string, unknown>;
      const condition: Record<string, unknown> = {};
      const action: Record<string, unknown> = {};

      const expiration = r['expiration'] as Record<string, unknown> | undefined;
      if (expiration?.['days'] !== undefined) {
        condition['age'] = expiration['days'];
      }
      const transition = r['transition'] as Record<string, unknown> | undefined;
      if (transition?.['storage_class']) {
        action['type'] = 'SetStorageClass';
        action['storage_class'] = transition['storage_class'];
      } else {
        action['type'] = 'Delete';
      }

      return { action, condition };
    });
  }

  const corsRules = attrs['cors_rule'] as unknown[] | undefined;
  if (Array.isArray(corsRules) && corsRules.length > 0) {
    gcpAttrs['cors'] = corsRules.map((rule) => {
      const r = rule as Record<string, unknown>;
      return {
        max_age_seconds: r['max_age_seconds'] ?? 3600,
        method: r['allowed_methods'] ?? [],
        origin: r['allowed_origins'] ?? [],
        response_header: r['allowed_headers'] ?? [],
      };
    });
  }

  const encryption = attrs['server_side_encryption_configuration'] as Record<string, unknown> | undefined;
  if (encryption) {
    const rule = encryption['rule'] as Record<string, unknown> | undefined;
    const kmsKeyId = (
      rule?.['apply_server_side_encryption_by_default'] as Record<string, unknown> | undefined
    )?.['kms_master_key_id'];
    if (typeof kmsKeyId === 'string') {
      gcpAttrs['encryption'] = { default_kms_key_name: kmsKeyId };
    }
  }

  const logging = attrs['logging'] as Record<string, unknown> | undefined;
  if (logging) {
    gcpAttrs['logging'] = {
      log_bucket: logging['target_bucket'] ?? '',
      log_object_prefix: logging['target_prefix'] ?? '',
    };
  }

  if (tags) {
    gcpAttrs['labels'] = transformTags('gcp', tags);
  }

  const website = attrs['website'] as Record<string, unknown> | undefined;
  if (website) {
    gcpAttrs['website'] = {
      main_page_suffix: website['index_document'] ?? 'index.html',
      not_found_page: website['error_document'] ?? '404.html',
    };
  }

  if (attrs['request_payer'] === 'Requester') {
    gcpAttrs['requester_pays'] = true;
  }

  const replicationConfig = attrs['replication_configuration'] as Record<string, unknown> | undefined;

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_storage_bucket',
      targetName: resource.sourceName,
      attributes: gcpAttrs,
      sourceId: resource.id,
      traceability,
    },
  ];

  const findings = collectUnmappedAttrs(resource.id, attrs, MAPPED_KEYS);

  const acl = attrs['acl'] as string | undefined;
  if (acl && acl !== 'private') {
    findings.push(createFinding(resource.id, 'info', 'S3_ACL_GCP_IAM', `S3 ACL '${acl}' maps to GCP IAM policies — manual IAM binding required`));
  }

  if (attrs['website']) findings.push(createFinding(resource.id, 'warning', 'S3_WEBSITE_HOSTING', 'S3 static website hosting maps to GCP website configuration — verify main_page_suffix and not_found_page'));
  if (attrs['object_lock_configuration']) findings.push(createFinding(resource.id, 'warning', 'S3_OBJECT_LOCK_UNSUPPORTED', 'S3 Object Lock has no direct GCP equivalent — use GCP retention policies'));
  if (attrs['request_payer'] === 'Requester') findings.push(createFinding(resource.id, 'info', 'S3_REQUESTER_PAYS', 'Requester Pays mapped to GCP requester_pays'));
  if (replicationConfig) findings.push(createFinding(resource.id, 'info', 'S3_REPLICATION_PARTIAL', 'S3 replication has no direct GCP equivalent — consider GCP dual/multi-region buckets'));
  if (encryption) findings.push(createFinding(resource.id, 'warning', 'S3_ENCRYPTION_KMS', 'Customer-managed KMS key detected — verify GCP Cloud KMS mapping'));

  return {
    translated,
    findings,
    contracts: [buildS3Contract(resource.id, attrs, translated, findings)],
  };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Translates an aws_s3_bucket resource to Azure or GCP equivalents.
 */
export function translateS3(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return translateToAzure(ctx);
  }
  return translateToGcp(ctx);
}
