/**
 * AWS-to-Azure region mapping and availability zone helpers.
 *
 * Re-exports the Azure column of the canonical REGION_MAP from
 * `attribute-transformer` to keep a single source of truth, then adds
 * Azure-specific helpers such as AZ-to-zone-number conversion.
 *
 * @module codegen/azure/region-mapping
 * @generated by code-generator (TASK-TRANS-006)
 */

import { REGION_MAP } from '../../engines/direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// AWS → Azure region map (derived from the canonical REGION_MAP)
// ---------------------------------------------------------------------------

/**
 * Maps AWS region identifiers to Azure region names.
 * 16 entries covering all major AWS regions.
 */
export const AWS_TO_AZURE_REGION: ReadonlyMap<string, string> = new Map(
  [...REGION_MAP.entries()].map(([aws, targets]) => [aws, targets.azure]),
);

// ---------------------------------------------------------------------------
// Region resolution
// ---------------------------------------------------------------------------

/** Default Azure region when no mapping is found. */
const DEFAULT_AZURE_REGION = 'eastus';

/**
 * Resolves an AWS region to the corresponding Azure region.
 * Returns `'eastus'` when no mapping exists.
 *
 * @param awsRegion - An AWS region string (e.g. `'us-west-2'`).
 * @returns The Azure region name.
 */
export function resolveAzureRegion(awsRegion: string): string {
  return AWS_TO_AZURE_REGION.get(awsRegion) ?? DEFAULT_AZURE_REGION;
}

// ---------------------------------------------------------------------------
// Availability zone helpers
// ---------------------------------------------------------------------------

/**
 * Converts an AWS availability zone suffix to an Azure zone number.
 *
 * AWS AZs end in a letter (`a`, `b`, `c`, ...); Azure zones are numbered
 * `1`, `2`, `3`. Letters beyond `c` wrap (mod 3) + 1.
 *
 * @param awsAz - An AWS AZ string (e.g. `'us-east-1a'`).
 * @returns The Azure zone number (1-3).
 */
export function azToAzureZone(awsAz: string): number {
  if (!awsAz || awsAz.length === 0) return 1;
  const lastChar = awsAz.charAt(awsAz.length - 1);
  const code = lastChar.charCodeAt(0);
  if (Number.isNaN(code)) return 1;
  const offset = code - 'a'.charCodeAt(0);
  // Non-letter or out-of-range → default zone 1
  if (offset < 0 || offset > 25) return 1;
  return (offset % 3) + 1;
}
