/**
 * Advisory mapping engine: dispatches to resource-specific advisory mappers
 * for AWS resources that have no automated translation (mapping type 'none').
 *
 * Advisory mappers emit ZERO translated resources — only warning-level
 * findings with structured migration guidance (steps + alternatives).
 *
 * Replaces the former inline noneEngine that emitted a single blocker.
 *
 * @module advisory-engine
 * @generated by code-generator (TASK-TRANS-008)
 */

import type { MappingEngine, TranslationContext, EngineResult } from './mapping-engine.js';
import { createFinding } from './direct/attribute-transformer.js';
import { translateDynamoDb } from './advisory/dynamodb-advisory.js';
import { translateIam } from './advisory/iam-advisory.js';
import { translateCloudfront } from './advisory/cloudfront-advisory.js';
import { translateRoute53Health } from './advisory/route53-health-advisory.js';
import { translateElasticacheCluster } from './advisory/elasticache-cluster-advisory.js';

// ---------------------------------------------------------------------------
// Dispatch table: source type -> advisory translator
// ---------------------------------------------------------------------------

const DISPATCH: ReadonlyMap<string, (ctx: TranslationContext) => EngineResult> =
  new Map([
    ['aws_dynamodb_table', translateDynamoDb],
    ['aws_iam_role', translateIam],
    ['aws_iam_policy', translateIam],
    ['aws_cloudfront_distribution', translateCloudfront],
    ['aws_route53_health_check', translateRoute53Health],
    ['aws_elasticache_cluster', translateElasticacheCluster],
  ]);

// ---------------------------------------------------------------------------
// Generic advisory fallback
// ---------------------------------------------------------------------------

/**
 * Fallback for resource types without a specialized advisory mapper.
 * Emits a warning with generic manual-migration guidance.
 */
function genericAdvisoryFallback(ctx: TranslationContext): EngineResult {
  return {
    translated: [],
    findings: [
      createFinding(
        ctx.resource.id,
        'warning',
        'ADVISORY_NO_MAPPER',
        `No automated mapping for ${ctx.resource.sourceType}. Manual migration required.`,
        JSON.stringify({
          migrationSteps: [
            'Review source resource configuration',
            'Identify target-cloud equivalent service',
            'Implement target resource manually in Terraform',
            'Validate functional parity with source resource',
          ],
          alternatives: [],
        }),
      ),
    ],
  };
}

// ---------------------------------------------------------------------------
// Engine export
// ---------------------------------------------------------------------------

/**
 * The advisory mapping engine. Handles resources with mapping type 'none'
 * by emitting migration guidance rather than translated resources.
 */
export const advisoryEngine: MappingEngine = {
  mappingType: 'none',
  translate(ctx: TranslationContext): EngineResult {
    const handler = DISPATCH.get(ctx.resource.sourceType) ?? genericAdvisoryFallback;
    return handler(ctx);
  },
};
