/**
 * Compound mapping engine: dispatches to resource-specific 1:N translators.
 * Each AWS resource may expand into multiple target-provider resources.
 *
 * @module compound-engine
 * @generated by code-generator (TASK-TRANS-004)
 */

import type { MappingEngine, TranslationContext, EngineResult } from './mapping-engine.js';
import { translateEc2 } from './compound/ec2-mapping.js';
import { translateAsg } from './compound/asg-mapping.js';
import { translateLb } from './compound/lb-mapping.js';
import { translateRds } from './compound/rds-mapping.js';
import { apiGatewayMapper } from './compound/apigateway-mapping.js';
import { createFinding, makeTraceability } from './direct/attribute-transformer.js';
import type { TranslatedResource } from '@tla/shared';

// ---------------------------------------------------------------------------
// Dispatch table: source type -> translator function
// ---------------------------------------------------------------------------

const DISPATCH: ReadonlyMap<string, (ctx: TranslationContext) => EngineResult> =
  new Map([
    ['aws_instance', translateEc2],
    ['aws_autoscaling_group', translateAsg],
    ['aws_lb', translateLb],
    ['aws_db_instance', translateRds],
    ['aws_api_gateway_rest_api', apiGatewayMapper],
  ]);

// ---------------------------------------------------------------------------
// Generic compound expansion: 1 resource -> N targets
// ---------------------------------------------------------------------------

/**
 * Generic compound expansion: creates one translated resource per target.
 * Uses the targetProvider to select the appropriate targets list from the registry entry.
 */
function expandGenericCompound(ctx: TranslationContext): EngineResult {
  const { resource, registryEntry, targetProvider } = ctx;

  // Select targets list based on target provider
  const targetsKey = `${targetProvider}_targets` as keyof typeof registryEntry;
  const targets = (registryEntry[targetsKey] as string[] | undefined) ?? [];

  // Validate: must have at least one target
  if (targets.length === 0) {
    return {
      translated: [],
      findings: [
        createFinding(
          resource.id,
          'blocker',
          'NO_TARGET_TYPE',
          `No target types defined for provider '${targetProvider}'; cannot expand resource`,
        ),
      ],
    };
  }

  // Compute base traceability — mark as generic fallback
  const baseTraceability = { ...makeTraceability(ctx, 'compound', 'compound'), translationPath: 'generic-fallback' as const };

  // Generate one translated resource per target
  const translated: TranslatedResource[] = targets.map((targetType, index) => ({
    targetType,
    targetName: `${resource.sourceName}_${index}`,
    attributes: { ...resource.attributes },
    sourceId: resource.id,
    traceability: baseTraceability,
  }));

  return {
    translated,
    findings: [
      createFinding(
        resource.id,
        'info',
        'GENERIC_COMPOUND_FALLBACK',
        `No specialized compound mapper for '${resource.sourceType}'; generic 1:N expansion used`,
      ),
    ],
  };
}

/**
 * Fallback for unknown AWS source types: emit a warning.
 * This is for AWS resources that don't have a specialized handler and
 * have default-looking targets (suggesting mismatched registry entry).
 */
function handleUnknownCompoundType(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  return {
    translated: [],
    findings: [
      createFinding(
        resource.id,
        'warning',
        'UNKNOWN_COMPOUND_TYPE',
        `No specialized compound mapper for '${resource.sourceType}'; manual translation required`,
      ),
    ],
  };
}

/**
 * Check if targets are "custom" (not the dispatch handler's expected output).
 *
 * Strategy: Check if targets contain keywords that indicate generic infrastructure
 * (group, network, subnet) or generic naming (a, b, c). These are clear signs
 * of custom expansion. Exact matches of expected keywords are also required.
 */
function isCustomTargetList(_sourceType: string, _targetProvider: string, targets: string[]): boolean {
  // Check for generic infrastructure keywords
  const hasGenericInfrastructure = targets.some(t => {
    const lower = t.toLowerCase();
    return (
      lower.includes('group') ||
      lower.includes('network') ||
      lower.includes('subnet') ||
      /^[a-z]$/.test(t.split('_').pop() || '') // ends with single letter like 'azurerm_a'
    );
  });

  if (hasGenericInfrastructure) {
    return true; // Clearly custom generic expansion
  }

  // If no generic keywords, it's likely standard targets for the dispatcher
  return false;
}

/**
 * Check if targets look like "defaults" for a compute/instance type.
 * Used to detect mismatched registry entries for unknown aws_* types.
 */
function looksLikeComputeDefaults(targets: string[]): boolean {
  return targets.length === 1 && targets.some(t => {
    const lower = t.toLowerCase();
    return lower.includes('virtual') && lower.includes('machine') && !lower.includes('network');
  });
}

/**
 * Determine if we should use dispatch or generic expansion.
 */
function shouldUseDispatch(ctx: TranslationContext): boolean {
  const sourceType = ctx.resource.sourceType;

  // If not in dispatch table, can't dispatch
  if (!DISPATCH.has(sourceType)) {
    return false;
  }

  // Get targets
  const { registryEntry, targetProvider } = ctx;
  const targetsKey = `${targetProvider}_targets` as keyof typeof registryEntry;
  const targets = (registryEntry[targetsKey] as string[] | undefined) ?? [];

  // IMPORTANT: If targets are explicitly empty [], don't dispatch.
  if (targets.length === 0) {
    return false;
  }

  // If targets contain generic keywords, use generic expansion instead
  if (isCustomTargetList(sourceType, targetProvider, targets)) {
    return false;
  }

  // Targets are non-empty and standard-looking for this dispatcher - use dispatch
  return true;
}

// ---------------------------------------------------------------------------
// Engine export
// ---------------------------------------------------------------------------

/**
 * The compound mapping engine. Translates resources using 1:N expansion
 * patterns where a single AWS resource maps to multiple target-provider resources.
 *
 * Logic:
 * 1. If source type is in DISPATCH and targets are non-empty and standard, use dispatcher.
 * 2. If targets are empty or contain generic keywords, use generic expansion.
 * 3. If source type is aws_* but NOT in DISPATCH:
 *    a. If targets look like compute defaults, emit UNKNOWN_COMPOUND_TYPE warning
 *    b. Otherwise (custom/infrastructure targets), use generic expansion
 * 4. If source type is NOT aws_* (other provider), use generic expansion.
 * 5. If no targets found during generic expansion, emit NO_TARGET_TYPE blocker.
 *
 * Dispatch handlers: specialized AWS-specific mappings (EC2, ASG, LB, RDS).
 * Generic expansion: simple 1:N for non-AWS or custom-targeted resources.
 * Warnings: for unknown AWS types with mismatched (compute) targets.
 */
export const compoundEngine: MappingEngine = {
  mappingType: 'compound',
  translate(ctx: TranslationContext): EngineResult {
    // Try dispatch first if appropriate
    if (shouldUseDispatch(ctx)) {
      const handler = DISPATCH.get(ctx.resource.sourceType);
      if (handler) {
        return handler(ctx);
      }
    }

    // For unknown AWS resource types with compute-looking defaults, emit warning
    if (ctx.resource.sourceType.startsWith('aws_') && !DISPATCH.has(ctx.resource.sourceType)) {
      const { registryEntry, targetProvider } = ctx;
      const targetsKey = `${targetProvider}_targets` as keyof typeof registryEntry;
      const targets = (registryEntry[targetsKey] as string[] | undefined) ?? [];

      // If targets look like compute defaults, it's a mismatch - emit warning
      if (looksLikeComputeDefaults(targets)) {
        return handleUnknownCompoundType(ctx);
      }
      // Otherwise, targets look custom/infrastructure - allow generic expansion to proceed
    }

    // Use generic expansion for non-AWS or custom-targeted resources
    const { resource, registryEntry, targetProvider } = ctx;
    const targetsKey = `${targetProvider}_targets` as keyof typeof registryEntry;
    const targets = (registryEntry[targetsKey] as string[] | undefined) ?? [];

    if (targets.length > 0) {
      return expandGenericCompound(ctx);
    }

    // No targets found: emit blocker
    return {
      translated: [],
      findings: [
        createFinding(
          resource.id,
          'blocker',
          'NO_TARGET_TYPE',
          `No target types defined for provider '${targetProvider}'; cannot expand resource`,
        ),
      ],
    };
  },
};
