/**
 * Direct mapping engine: dispatches to resource-specific translators.
 * Falls back to a generic pass-through for unmapped resource types.
 *
 * @module direct-engine
 * @generated by code-generator (TASK-TRANS-002)
 */

import type { MappingEngine, TranslationContext, EngineResult } from './mapping-engine.js';
import { translateS3 } from './direct/s3-mapping.js';
import { translateEcr } from './direct/ecr-mapping.js';
import { translateRedis } from './direct/redis-mapping.js';
import { translatePeering } from './direct/peering-mapping.js';
import { translateDns } from './direct/dns-mapping.js';
import { createFinding, makeTraceability } from './direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Dispatch table: source type -> translator function
// ---------------------------------------------------------------------------

const DISPATCH: ReadonlyMap<string, (ctx: TranslationContext) => EngineResult> =
  new Map([
    ['aws_s3_bucket', translateS3],
    ['aws_ecr_repository', translateEcr],
    ['aws_elasticache_replication_group', translateRedis],
    ['aws_vpc_peering_connection', translatePeering],
    ['aws_route53_zone', translateDns],
    ['aws_route53_record', translateDns],
  ]);

// ---------------------------------------------------------------------------
// Generic fallback
// ---------------------------------------------------------------------------

/**
 * Generic fallback: copies all attributes verbatim and emits an info finding.
 */
/**
 * Critical resource type prefixes that warrant a warning (not info) when
 * translated via generic fallback, because verbatim attribute copy is
 * unlikely to produce a working result for these families.
 */
const CRITICAL_FALLBACK_PREFIXES = [
  'aws_instance',
  'aws_db_',
  'aws_rds',
  'aws_security_group',
  'aws_iam',
] as const;

function genericFallback(ctx: TranslationContext): EngineResult {
  const { resource, registryEntry, targetProvider } = ctx;
  const targets =
    targetProvider === 'azure'
      ? registryEntry.azure_targets
      : registryEntry.gcp_targets;

  const targetType = targets[0];
  if (!targetType) {
    return {
      translated: [],
      findings: [
        createFinding(
          resource.id,
          'blocker',
          'NO_TARGET_TYPE',
          `No ${targetProvider} target defined for ${resource.sourceType}`,
        ),
      ],
    };
  }

  // Sort attribute keys for deterministic output
  const sortedAttrs: Record<string, unknown> = {};
  for (const key of Object.keys(resource.attributes).sort()) {
    sortedAttrs[key] = resource.attributes[key];
  }

  // Raise severity for critical resource families
  const isCritical = CRITICAL_FALLBACK_PREFIXES.some((prefix) =>
    resource.sourceType.startsWith(prefix),
  );

  return {
    translated: [
      {
        targetType,
        targetName: resource.sourceName,
        attributes: sortedAttrs,
        sourceId: resource.id,
        traceability: { ...makeTraceability(ctx, 'direct/generic'), translationPath: 'generic-fallback' as const },
      },
    ],
    findings: [
      createFinding(
        resource.id,
        isCritical ? 'warning' : 'info',
        'GENERIC_DIRECT_FALLBACK',
        `No specialized direct mapper for '${resource.sourceType}'; attributes copied verbatim`,
      ),
    ],
  };
}

// ---------------------------------------------------------------------------
// Engine export
// ---------------------------------------------------------------------------

/**
 * The direct mapping engine. Translates resources with 1:1 (or 1:2 for S3/Azure)
 * mappings using resource-type-specific translators.
 */
export const directEngine: MappingEngine = {
  mappingType: 'direct',
  translate(ctx: TranslationContext): EngineResult {
    const handler = DISPATCH.get(ctx.resource.sourceType) ?? genericFallback;
    return handler(ctx);
  },
};
