/**
 * Parametric mapping engine: dispatches to resource-specific translators.
 * Falls back to a generic parametric handler for unmapped resource types.
 *
 * @module parametric-engine
 * @generated by code-generator (TASK-TRANS-003)
 */

import type { MappingEngine, TranslationContext, EngineResult } from './mapping-engine.js';
// Note: aws_subnet moved to structural-engine (TASK-NET-002)
import { translateNat } from './parametric/nat-mapping.js';
import { translateKms } from './parametric/kms-mapping.js';
import { translateSecrets, translateSecretVersion } from './parametric/secrets-mapping.js';
import { translateEks } from './parametric/eks-mapping.js';
import { translateDxConnection, translateDxGateway } from './parametric/direct-connect-mapping.js';
import {
  translateVpnGateway,
  translateVpnConnection,
  translateCustomerGateway,
} from './parametric/vpn-mapping.js';
import { createFinding, makeTraceability } from './direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Dispatch table: source type -> translator function
// Note: aws_vpc moved to structural-engine (TASK-NET-001)
// ---------------------------------------------------------------------------

const DISPATCH: ReadonlyMap<string, (ctx: TranslationContext) => EngineResult> =
  new Map([
    // Note: aws_subnet moved to structural-engine (TASK-NET-002)
    ['aws_nat_gateway', translateNat],
    ['aws_kms_key', translateKms],
    ['aws_secretsmanager_secret', translateSecrets],
    ['aws_secretsmanager_secret_version', translateSecretVersion],
    ['aws_eks_cluster', translateEks],
    // Direct Connect (TASK-GAP-010)
    ['aws_dx_connection', translateDxConnection],
    ['aws_dx_gateway', translateDxGateway],
    ['aws_dx_gateway_association', translateDxGateway],
    // Site-to-Site VPN (TASK-GAP-010)
    ['aws_vpn_gateway', translateVpnGateway],
    ['aws_vpn_connection', translateVpnConnection],
    ['aws_customer_gateway', translateCustomerGateway],
  ]);

// ---------------------------------------------------------------------------
// Generic fallback
// ---------------------------------------------------------------------------

/**
 * Generic parametric fallback: copies attributes verbatim and emits a finding.
 */
function genericParametricFallback(ctx: TranslationContext): EngineResult {
  const { resource, registryEntry, targetProvider } = ctx;
  const targets =
    targetProvider === 'azure'
      ? registryEntry.azure_targets
      : registryEntry.gcp_targets;

  const targetType = targets[0];
  if (!targetType) {
    return {
      translated: [],
      findings: [
        createFinding(
          resource.id,
          'blocker',
          'NO_TARGET_TYPE',
          `No ${targetProvider} target defined for ${resource.sourceType}`,
        ),
      ],
    };
  }

  // Sort attribute keys for deterministic output
  const sortedAttrs: Record<string, unknown> = {};
  for (const key of Object.keys(resource.attributes).sort()) {
    sortedAttrs[key] = resource.attributes[key];
  }

  return {
    translated: [
      {
        targetType,
        targetName: resource.sourceName,
        attributes: sortedAttrs,
        sourceId: resource.id,
        traceability: makeTraceability(ctx, 'parametric/generic', 'parametric'),
      },
    ],
    findings: [
      createFinding(
        resource.id,
        'info',
        'GENERIC_PARAMETRIC_FALLBACK',
        `No specialized parametric mapper for '${resource.sourceType}'; attributes copied verbatim`,
      ),
    ],
  };
}

// ---------------------------------------------------------------------------
// Engine export
// ---------------------------------------------------------------------------

/**
 * The parametric mapping engine. Translates resources using parameter-aware
 * transformations with cross-reference resolution.
 */
export const parametricEngine: MappingEngine = {
  mappingType: 'parametric',
  translate(ctx: TranslationContext): EngineResult {
    const handler = DISPATCH.get(ctx.resource.sourceType) ?? genericParametricFallback;
    return handler(ctx);
  },
};
