/**
 * Structural mapping engine: dispatches to resource-specific translators
 * for AWS resources that require structural transformation (topology changes)
 * when moving across cloud providers.
 *
 * @module structural-engine
 * @generated by code-generator (TASK-TRANS-005, TASK-NET-001)
 */

import type { MappingEngine, TranslationContext, EngineResult } from './mapping-engine.js';
import { translateSecurityGroup } from './structural/security-group-mapping.js';
import { translateLambda } from './structural/lambda-mapping.js';
import { translateEcs } from './structural/ecs-mapping.js';
import { translateSqs } from './structural/sqs-mapping.js';
import { translateSns } from './structural/sns-mapping.js';
import { translateCloudwatchAlarm, translateCloudwatchLogs } from './structural/cloudwatch-mapping.js';
import { translateVpc } from './structural/vpc-mapping.js';
import { translateDhcpOptions } from './structural/dhcp-options-mapping.js';
import { translateFlowLog } from './structural/flow-log-mapping.js';
import { translateInternetGateway } from './structural/internet-gateway-mapping.js';
import { translateRouteTable } from './structural/route-table-mapping.js';
import { translateSubnet } from './structural/subnet-mapping.js';
import { translateDns } from './structural/dns-mapping.js';
import { translateTransitGateway, translateTransitGatewayRouteTable } from './structural/transit-gateway-mapping.js';
import { translateHybridConnectivity } from './structural/hybrid-connectivity-mapping.js';
import { translatePrivateLink } from './structural/privatelink-mapping.js';
import { wafMapper } from './structural/waf-mapping.js';
import { translateStepFunctions } from './structural/stepfunctions-mapping.js';
import { createFinding } from './direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Dispatch table: source type -> translator function
// ---------------------------------------------------------------------------

const DISPATCH: ReadonlyMap<string, (ctx: TranslationContext) => EngineResult> =
  new Map([
    ['aws_security_group', translateSecurityGroup],
    ['aws_lambda_function', translateLambda],
    ['aws_ecs_service', translateEcs],
    ['aws_sqs_queue', translateSqs],
    ['aws_sns_topic', translateSns],
    ['aws_cloudwatch_metric_alarm', translateCloudwatchAlarm],
    ['aws_cloudwatch_log_group', translateCloudwatchLogs],
    ['aws_vpc', translateVpc],
    ['aws_vpc_dhcp_options', translateDhcpOptions],
    ['aws_flow_log', translateFlowLog],
    ['aws_internet_gateway', translateInternetGateway],
    ['aws_route_table', translateRouteTable],
    ['aws_subnet', translateSubnet],
    ['aws_route53_zone', translateDns],
    ['aws_route53_record', translateDns],
    ['aws_ec2_transit_gateway', translateTransitGateway],
    ['aws_ec2_transit_gateway_vpc_attachment', translateTransitGateway],
    ['aws_ec2_transit_gateway_route_table', translateTransitGatewayRouteTable],
    ['aws_vpn_connection', translateHybridConnectivity],
    ['aws_vpn_gateway', translateHybridConnectivity],
    ['aws_dx_connection', translateHybridConnectivity],
    ['aws_dx_gateway', translateHybridConnectivity],
    ['aws_ec2_transit_gateway_peering_attachment', translateHybridConnectivity],
    ['aws_vpc_endpoint', translatePrivateLink],
    ['aws_vpc_endpoint_service', translatePrivateLink],
    ['aws_wafv2_web_acl', wafMapper],
    ['aws_wafv2_rule_group', wafMapper],
    // Step Functions (TASK-GAP-010)
    ['aws_sfn_state_machine', translateStepFunctions],
  ]);

// ---------------------------------------------------------------------------
// Generic structural fallback
// ---------------------------------------------------------------------------

/**
 * Fallback for unknown structural source types: emits a warning with no
 * translated resources.
 */
function genericStructuralFallback(ctx: TranslationContext): EngineResult {
  const { resource } = ctx;
  return {
    translated: [],
    findings: [
      createFinding(
        resource.id,
        'warning',
        'UNKNOWN_STRUCTURAL_TYPE',
        `No specialized structural mapper for '${resource.sourceType}'; manual translation required`,
      ),
    ],
  };
}

// ---------------------------------------------------------------------------
// Engine export
// ---------------------------------------------------------------------------

/**
 * The structural mapping engine. Translates resources that require topology
 * changes (e.g. security groups, serverless functions, container services,
 * messaging queues, observability) across cloud providers.
 */
export const structuralEngine: MappingEngine = {
  mappingType: 'structural',
  translate(ctx: TranslationContext): EngineResult {
    const handler = DISPATCH.get(ctx.resource.sourceType) ?? genericStructuralFallback;
    return handler(ctx);
  },
};
