/**
 * Main expression translation orchestrator.
 *
 * Scans HCL/Terraform expression strings for resource references and data
 * source references, rewrites each one for the target cloud provider, and
 * aggregates findings.
 *
 * @module expressions/expression-translator
 * @generated by code-generator (TASK-TRANS-009)
 */

import type { TranslationFinding } from '@tla/shared';
import type { ExpressionContext, TranslatedExpression } from './types.js';
import { rewriteReference } from './reference-rewriter.js';
import { mapDataSource, mapFunction } from './function-mapper.js';

// ---------------------------------------------------------------------------
// Patterns
// ---------------------------------------------------------------------------

/**
 * Matches Terraform-style references inside an expression string.
 * Captures dotted identifiers with optional bracket indexing:
 *   aws_instance.web.id
 *   aws_instance.web[0].id
 *   data.aws_caller_identity.current.account_id
 *   module.vpc.vpc_id
 */
const REFERENCE_RE =
  /(?:(?:data|module)\.)?[a-z_][a-z0-9_]*\.[a-z_][a-z0-9_]*(?:\[[^\]]*\])?(?:\.[a-z_][a-z0-9_]*)*/g;

/**
 * Matches function calls: name(args).
 * group 1: function name
 * group 2: opening paren position (we extract args separately)
 */
const FUNCTION_CALL_RE = /([a-z_][a-z0-9_]*)\s*\(/g;

/**
 * Detects interpolation wrapper: `${...}`
 */
const INTERPOLATION_RE = /^\$\{(.+)\}$/s;

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * Translates a single HCL expression string, rewriting all resource
 * references and data source references for the target cloud provider.
 *
 * @param expr - The raw expression (may include interpolation wrappers)
 * @param ctx  - Expression translation context
 * @returns The rewritten expression and aggregated findings
 */
export function translateExpression(
  expr: string,
  ctx: ExpressionContext,
): TranslatedExpression {
  if (typeof expr !== 'string' || expr.length === 0) {
    return { rewritten: expr, findings: [] };
  }

  // Short-circuit: if no dots, it's a plain literal — nothing to rewrite
  if (!expr.includes('.')) {
    return { rewritten: expr, findings: [] };
  }

  // Handle interpolation wrapper
  const interpMatch = INTERPOLATION_RE.exec(expr);
  if (interpMatch) {
    const inner = interpMatch[1]!;
    const result = translateExpressionInner(inner, ctx);
    return {
      rewritten: `\${${result.rewritten}}`,
      findings: result.findings,
    };
  }

  return translateExpressionInner(expr, ctx);
}

// ---------------------------------------------------------------------------
// Inner translator
// ---------------------------------------------------------------------------

function translateExpressionInner(
  expr: string,
  ctx: ExpressionContext,
): TranslatedExpression {
  const allFindings: TranslationFinding[] = [];

  // Collect function findings (but don't rewrite — functions pass through)
  let funcMatch: RegExpExecArray | null;
  const funcRe = new RegExp(FUNCTION_CALL_RE.source, FUNCTION_CALL_RE.flags);
  while ((funcMatch = funcRe.exec(expr)) !== null) {
    const funcName = funcMatch[1]!;
    const result = mapFunction(funcName, '', ctx);
    if (result) {
      allFindings.push(...result.findings);
    }
  }

  // Rewrite references: scan for reference patterns, replace each one
  const refRe = new RegExp(REFERENCE_RE.source, REFERENCE_RE.flags);
  let rewritten = '';
  let lastIndex = 0;

  let refMatch: RegExpExecArray | null;
  while ((refMatch = refRe.exec(expr)) !== null) {
    const fullMatch = refMatch[0];
    const matchStart = refMatch.index;

    // Skip references that are part of a function call (preceded by function name)
    // We still rewrite the reference itself — the function name stays

    // Append text before this match
    rewritten += expr.slice(lastIndex, matchStart);

    // Try data source mapping first
    const dsResult = mapDataSource(fullMatch, ctx);
    if (dsResult) {
      rewritten += dsResult.rewritten;
      allFindings.push(...dsResult.findings);
    } else {
      // Try reference rewriting
      const refResult = rewriteReference(fullMatch, ctx);
      rewritten += refResult.rewritten;
      allFindings.push(...refResult.findings);
    }

    lastIndex = matchStart + fullMatch.length;
  }

  // Append any remaining text after the last match
  rewritten += expr.slice(lastIndex);

  return { rewritten, findings: allFindings };
}
