/**
 * Expression translation subsystem — barrel re-exports.
 *
 * @module expressions
 * @generated by code-generator (TASK-TRANS-009)
 */

// Main orchestrator
export { translateExpression } from './expression-translator.js';

// Reference rewriting
export { rewriteReference, buildReferenceMap } from './reference-rewriter.js';

// Data source & function mapping
export { mapDataSource, mapFunction } from './function-mapper.js';

// Types
export type {
  ReferenceMap,
  ExpressionContext,
  TranslatedExpression,
} from './types.js';
