/**
 * Core reference rewriting logic for Terraform/HCL resource references.
 *
 * Parses references like `aws_instance.web.id` or `aws_instance.web[0].id`
 * and rewrites them to the target provider's equivalent type and attribute.
 *
 * @module expressions/reference-rewriter
 * @generated by code-generator (TASK-TRANS-009)
 */

import type { TranslationFinding } from '@tla/shared';
import type { ExpressionContext, ReferenceMap, TranslatedExpression } from './types.js';
import { createFinding } from '../engines/direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Reference parsing
// ---------------------------------------------------------------------------

/**
 * Regex to decompose a Terraform resource reference:
 *   group 1: resource type   (e.g. "aws_instance")
 *   group 2: resource name   (e.g. "web")
 *   group 3: optional index  (e.g. "[0]", "[*]", "[count.index]")
 *   group 4: attribute tail  (e.g. ".id", ".private_ip")
 */
const REF_RE =
  /^([a-z_][a-z0-9_]*)\.([a-z_][a-z0-9_]*)(\[[^\]]*\])?((?:\.[a-z_][a-z0-9_]*)*)$/;

/**
 * Regex for module output references:
 *   group 1: module name  (e.g. "vpc")
 *   group 2: output name  (e.g. "vpc_id")
 */
const MODULE_REF_RE = /^module\.([a-z_][a-z0-9_]*)\.([a-z_][a-z0-9_]*)$/;

// ---------------------------------------------------------------------------
// Reference rewriter
// ---------------------------------------------------------------------------

/**
 * Rewrites a single Terraform resource reference to the target provider.
 *
 * @param ref - The raw reference string (e.g. "aws_instance.web.id")
 * @param ctx - Expression translation context
 * @returns The rewritten reference and any findings
 */
export function rewriteReference(
  ref: string,
  ctx: ExpressionContext,
): TranslatedExpression {
  // Try data source reference first
  if (ref.startsWith('data.')) {
    return rewriteDataRef(ref, ctx);
  }

  // Try module output reference
  const moduleMatch = MODULE_REF_RE.exec(ref);
  if (moduleMatch) {
    return rewriteModuleRef(
      ref,
      moduleMatch[1]!,
      moduleMatch[2]!,
      ctx,
    );
  }

  // Try resource reference
  const resMatch = REF_RE.exec(ref);
  if (resMatch) {
    return rewriteResourceRef(
      ref,
      resMatch[1]!,
      resMatch[2]!,
      resMatch[3] ?? '',
      resMatch[4] ?? '',
      ctx,
    );
  }

  // Not a recognised reference shape — return as-is
  return { rewritten: ref, findings: [] };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function rewriteResourceRef(
  original: string,
  sourceType: string,
  name: string,
  index: string,
  attrTail: string,
  ctx: ExpressionContext,
): TranslatedExpression {
  const findings: TranslationFinding[] = [];

  // Look up target resource type
  const typeEntry = ctx.referenceMap.resourceTypeMap.get(sourceType);
  const targetType = typeEntry?.[ctx.target];

  if (!targetType) {
    // Unknown type — return original with a warning
    findings.push(
      createFinding(
        sourceType,
        'warning',
        'UNKNOWN_REF_TYPE',
        `No ${ctx.target} mapping for resource type '${sourceType}' in reference '${original}'`,
      ),
    );
    return { rewritten: original, findings };
  }

  // Rewrite attribute if present
  let rewrittenAttr = attrTail;
  if (attrTail.length > 0) {
    // attrTail starts with "." — strip leading dot for lookup, then re-add
    const attrName = attrTail.slice(1); // e.g. "id" or "private_ip"
    const attrMap = ctx.referenceMap.attributeMap.get(sourceType);
    const attrEntry = attrMap?.get(attrName);
    const targetAttr = attrEntry?.[ctx.target];

    if (targetAttr) {
      rewrittenAttr = `.${targetAttr}`;
    }
    // If no mapping, keep the original attribute name (many attrs are the same)
  }

  const rewritten = `${targetType}.${name}${index}${rewrittenAttr}`;
  return { rewritten, findings };
}

function rewriteModuleRef(
  original: string,
  moduleName: string,
  outputName: string,
  ctx: ExpressionContext,
): TranslatedExpression {
  const findings: TranslationFinding[] = [];

  const outputEntry = ctx.referenceMap.outputMap.get(outputName);
  const targetOutput = outputEntry?.[ctx.target];

  if (targetOutput) {
    return {
      rewritten: `module.${moduleName}.${targetOutput}`,
      findings,
    };
  }

  // No mapping — keep original, no warning (module outputs are often custom)
  return { rewritten: original, findings };
}

/**
 * Fallback handler for data-source references that were not matched by
 * mapDataSource in function-mapper. Returns the original reference unchanged.
 *
 * @param original - The raw data-source reference string
 * @param _ctx - Expression context (unused; reserved for future provider-specific data rewrites)
 */
function rewriteDataRef(
  original: string,
  _ctx: ExpressionContext,
): TranslatedExpression {
  // Data refs are handled by function-mapper's mapDataSource; if we get here
  // as a fallback, just return the original unchanged.
  return { rewritten: original, findings: [] };
}

// ---------------------------------------------------------------------------
// Reference map builder
// ---------------------------------------------------------------------------

/**
 * Builds a ReferenceMap from the known engine dispatch tables.
 *
 * This is a static mapping that captures the AWS source type to target type
 * relationships established by the direct, parametric, compound, and
 * structural engines.
 */
export function buildReferenceMap(): ReferenceMap {
  // Resource type mapping: aws_type -> { azure, gcp }
  const resourceTypeMap = new Map<string, Record<string, string>>([
    // Direct engine (P1)
    ['aws_s3_bucket', { azure: 'azurerm_storage_account', gcp: 'google_storage_bucket' }],
    ['aws_ecr_repository', { azure: 'azurerm_container_registry', gcp: 'google_artifact_registry_repository' }],
    ['aws_elasticache_replication_group', { azure: 'azurerm_redis_cache', gcp: 'google_redis_instance' }],
    ['aws_route53_zone', { azure: 'azurerm_dns_zone', gcp: 'google_dns_managed_zone' }],
    ['aws_route53_record', { azure: 'azurerm_dns_a_record', gcp: 'google_dns_record_set' }],
    ['aws_vpc_peering_connection', { azure: 'azurerm_virtual_network_peering', gcp: 'google_compute_network_peering' }],

    // Parametric engine (P2)
    ['aws_vpc', { azure: 'azurerm_virtual_network', gcp: 'google_compute_network' }],
    ['aws_subnet', { azure: 'azurerm_subnet', gcp: 'google_compute_subnetwork' }],
    ['aws_nat_gateway', { azure: 'azurerm_nat_gateway', gcp: 'google_compute_router_nat' }],
    ['aws_kms_key', { azure: 'azurerm_key_vault_key', gcp: 'google_kms_crypto_key' }],
    ['aws_secretsmanager_secret', { azure: 'azurerm_key_vault_secret', gcp: 'google_secret_manager_secret' }],
    ['aws_eks_cluster', { azure: 'azurerm_kubernetes_cluster', gcp: 'google_container_cluster' }],

    // Compound engine (1:N — primary target type)
    ['aws_instance', { azure: 'azurerm_linux_virtual_machine', gcp: 'google_compute_instance' }],
    ['aws_autoscaling_group', { azure: 'azurerm_linux_virtual_machine_scale_set', gcp: 'google_compute_instance_group_manager' }],
    ['aws_lb', { azure: 'azurerm_lb', gcp: 'google_compute_forwarding_rule' }],
    ['aws_db_instance', { azure: 'azurerm_postgresql_flexible_server', gcp: 'google_sql_database_instance' }],

    // Structural engine
    ['aws_security_group', { azure: 'azurerm_network_security_group', gcp: 'google_compute_firewall' }],
    ['aws_lambda_function', { azure: 'azurerm_linux_function_app', gcp: 'google_cloudfunctions2_function' }],
    ['aws_ecs_service', { azure: 'azurerm_container_app', gcp: 'google_cloud_run_v2_service' }],
    ['aws_sqs_queue', { azure: 'azurerm_servicebus_queue', gcp: 'google_pubsub_topic' }],
    ['aws_sns_topic', { azure: 'azurerm_servicebus_topic', gcp: 'google_pubsub_topic' }],
    ['aws_cloudwatch_metric_alarm', { azure: 'azurerm_monitor_metric_alert', gcp: 'google_monitoring_alert_policy' }],
    ['aws_cloudwatch_log_group', { azure: 'azurerm_log_analytics_workspace', gcp: 'google_logging_project_sink' }],
  ]);

  // Attribute mapping: common renames per resource type
  const attributeMap = new Map<string, ReadonlyMap<string, Record<string, string>>>([
    ['aws_instance', new Map([
      ['instance_type', { azure: 'size', gcp: 'machine_type' }],
      ['ami', { azure: 'source_image_id', gcp: 'boot_disk.initialize_params.image' }],
      ['subnet_id', { azure: 'subnet_id', gcp: 'network_interface.subnetwork' }],
      ['private_ip', { azure: 'private_ip_address', gcp: 'network_interface.network_ip' }],
    ])],
    ['aws_vpc', new Map([
      ['cidr_block', { azure: 'address_space', gcp: 'auto_create_subnetworks' }],
    ])],
    ['aws_subnet', new Map([
      ['cidr_block', { azure: 'address_prefixes', gcp: 'ip_cidr_range' }],
      ['availability_zone', { azure: 'zone', gcp: 'region' }],
    ])],
    ['aws_s3_bucket', new Map([
      ['bucket', { azure: 'name', gcp: 'name' }],
      ['acl', { azure: 'access_tier', gcp: 'uniform_bucket_level_access' }],
    ])],
    ['aws_security_group', new Map([
      ['vpc_id', { azure: 'resource_group_name', gcp: 'network' }],
    ])],
    ['aws_db_instance', new Map([
      ['engine', { azure: 'sku_name', gcp: 'database_version' }],
      ['instance_class', { azure: 'sku_name', gcp: 'tier' }],
      ['allocated_storage', { azure: 'storage_mb', gcp: 'disk_size' }],
    ])],
  ]);

  // Module output mapping: common outputs
  const outputMap = new Map<string, Record<string, string>>([
    ['vpc_id', { azure: 'vnet_id', gcp: 'network_id' }],
    ['subnet_id', { azure: 'subnet_id', gcp: 'subnetwork_id' }],
    ['cluster_endpoint', { azure: 'kube_config.0.host', gcp: 'endpoint' }],
    ['cluster_ca_certificate', { azure: 'kube_config.0.cluster_ca_certificate', gcp: 'master_auth.0.cluster_ca_certificate' }],
  ]);

  return { resourceTypeMap, attributeMap, outputMap };
}
