/**
 * Shared types for the expression translation subsystem.
 *
 * @module expressions/types
 * @generated by code-generator (TASK-TRANS-009)
 */

import type { CloudProvider, TranslationFinding } from '@tla/shared';

// ---------------------------------------------------------------------------
// Reference map — built once from engine dispatch tables
// ---------------------------------------------------------------------------

export interface ReferenceMap {
  /** aws_type -> { azure: target_type, gcp: target_type } */
  readonly resourceTypeMap: ReadonlyMap<string, Record<string, string>>;
  /** aws_type -> attr -> { azure: renamed, gcp: renamed } */
  readonly attributeMap: ReadonlyMap<string, ReadonlyMap<string, Record<string, string>>>;
  /** module_output -> { azure: renamed, gcp: renamed } */
  readonly outputMap: ReadonlyMap<string, Record<string, string>>;
}

// ---------------------------------------------------------------------------
// Expression context — passed to all translation functions
// ---------------------------------------------------------------------------

export interface ExpressionContext {
  readonly referenceMap: ReferenceMap;
  readonly target: CloudProvider;
}

// ---------------------------------------------------------------------------
// Result of translating a single expression or sub-expression
// ---------------------------------------------------------------------------

export interface TranslatedExpression {
  readonly rewritten: string;
  readonly findings: readonly TranslationFinding[];
}
