/**
 * GCP label transformation utilities.
 *
 * GCP labels have strict constraints:
 * - Keys: lowercase `[a-z][a-z0-9_-]{0,62}`, max 63 chars
 * - Values: lowercase, max 63 chars
 * - Keys starting with `goog` are reserved by Google
 * - Maximum 64 labels per resource
 *
 * This module transforms AWS-style tags into compliant GCP labels,
 * reporting warnings for any modifications.
 *
 * @module codegen/gcp/label-transformer
 * @generated by code-generator (TASK-TRANS-007)
 */

import { createComponentLogger } from '@tla/shared';

const logger = createComponentLogger('label-transformer');

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Result of transforming a set of tags into GCP labels.
 */
export interface LabelTransformResult {
  /** The transformed GCP-compliant labels. */
  readonly labels: Record<string, string>;
  /** Warnings about modifications made during transformation. */
  readonly warnings: string[];
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MAX_KEY_LEN = 63;
const MAX_VALUE_LEN = 63;
const MAX_LABELS = 64;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Sanitises a single label key to GCP constraints.
 *
 * - Lowercase
 * - Replace invalid chars with `_`
 * - Ensure starts with `[a-z]` (prepend `tag_` if not)
 * - Truncate to 63 chars
 */
function sanitizeKey(raw: string): { key: string; modified: boolean } {
  let key = raw.toLowerCase().replace(/[^a-z0-9_-]/g, '_');
  let modified = key !== raw.toLowerCase();

  // Ensure starts with a letter
  if (key.length > 0 && !/^[a-z]/.test(key)) {
    key = 'tag_' + key;
    modified = true;
  }

  // Truncate
  if (key.length > MAX_KEY_LEN) {
    key = key.slice(0, MAX_KEY_LEN);
    modified = true;
  }

  // Fallback for empty key
  if (key.length === 0) {
    key = 'tag';
    modified = true;
  }

  return { key, modified };
}

/**
 * Sanitises a single label value to GCP constraints.
 *
 * - Lowercase
 * - Truncate to 63 chars
 */
function sanitizeValue(raw: string): { value: string; modified: boolean } {
  let value = raw.toLowerCase();
  let modified = value !== raw;

  if (value.length > MAX_VALUE_LEN) {
    value = value.slice(0, MAX_VALUE_LEN);
    modified = true;
  }

  return { value, modified };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Transforms AWS-style tags into GCP-compliant labels.
 *
 * @param tags - Source tags (key-value pairs).
 * @returns Transformed labels and any warnings generated.
 */
export function transformLabels(
  tags: Readonly<Record<string, string>>,
): LabelTransformResult {
  const labels: Record<string, string> = {};
  const warnings: string[] = [];
  let count = 0;

  // Process keys in sorted order for determinism
  const sortedKeys = Object.keys(tags).sort();

  for (const rawKey of sortedKeys) {
    // Skip reserved prefixes
    const lowerKey = rawKey.toLowerCase();
    if (lowerKey.startsWith('goog') || rawKey.startsWith('aws:')) {
      warnings.push(
        `Dropped reserved label key '${rawKey}'`,
      );
      continue;
    }

    // Enforce max label count
    if (count >= MAX_LABELS) {
      warnings.push(
        `Exceeded maximum ${MAX_LABELS} labels; dropped key '${rawKey}'`,
      );
      continue;
    }

    const { key, modified: keyModified } = sanitizeKey(rawKey);
    const { value, modified: valueModified } = sanitizeValue(tags[rawKey]!);

    if (keyModified) {
      warnings.push(
        `Label key '${rawKey}' sanitised to '${key}'`,
      );
    }
    if (valueModified) {
      warnings.push(
        `Label value for '${rawKey}' sanitised to '${value}'`,
      );
    }

    // Handle duplicate keys after sanitisation (last wins with warning)
    if (key in labels) {
      warnings.push(
        `Duplicate label key '${key}' (from '${rawKey}'); overwriting previous value`,
      );
    }

    labels[key] = value;
    count++;
  }

  logger.debug({ labelCount: count, warningCount: warnings.length }, 'Labels transformed');

  return { labels, warnings };
}
