/**
 * GCP resource naming conventions and sanitisation.
 *
 * Most GCP resources follow a uniform naming rule: lowercase letters,
 * digits, and hyphens, starting with a letter, max 63 characters.
 * This module encodes that constraint and provides a
 * {@link sanitizeGcpName} function that cleans names to conform.
 *
 * @module codegen/gcp/naming
 * @generated by code-generator (TASK-TRANS-007)
 */

// ---------------------------------------------------------------------------
// Name constraint defaults
// ---------------------------------------------------------------------------

/**
 * Default GCP name limit. Most resources use the same 63-char,
 * lowercase-letter-start rule.
 */
const DEFAULT_MAX_LEN = 63;

// ---------------------------------------------------------------------------
// Per-type overrides (only where GCP diverges from the default)
// ---------------------------------------------------------------------------

/**
 * GCP type short key -> max length override.
 * Only entries that differ from the default 63 are listed.
 */
const GCP_NAME_MAX_OVERRIDES: ReadonlyMap<string, number> = new Map([
  ['gcs', 222],     // Storage bucket names can be up to 222 chars
  ['pubsub', 255],  // Pub/Sub topic names can be up to 255 chars
]);

// ---------------------------------------------------------------------------
// Sanitiser
// ---------------------------------------------------------------------------

/**
 * Sanitises a base name for a GCP resource.
 *
 * Steps:
 * 1. Convert to lowercase.
 * 2. Replace characters outside `[a-z0-9-]` with `-`.
 * 3. Collapse consecutive hyphens.
 * 4. Strip leading/trailing hyphens.
 * 5. Ensure the name starts with a letter (prepend `r-` if not).
 * 6. Truncate to the type's max length (default 63).
 * 7. Strip any trailing hyphen introduced by truncation.
 * 8. Fall back to `typeShort` or `'resource'` if empty.
 *
 * @param typeShort - The short GCP resource type key (e.g. `'vm'`, `'gke'`).
 * @param baseName  - The raw name to sanitise.
 * @returns A name that satisfies GCP naming constraints.
 */
export function sanitizeGcpName(
  typeShort: string,
  baseName: string,
): string {
  const maxLen = GCP_NAME_MAX_OVERRIDES.get(typeShort) ?? DEFAULT_MAX_LEN;

  // Step 1-2: lowercase, strip invalid chars
  let name = baseName.toLowerCase().replace(/[^a-z0-9-]/g, '-');

  // Step 3: collapse consecutive hyphens
  name = name.replace(/-{2,}/g, '-');

  // Step 4: strip leading/trailing hyphens
  name = name.replace(/^-+|-+$/g, '');

  // Step 5: ensure starts with a letter
  if (name.length > 0 && !/^[a-z]/.test(name)) {
    name = 'r-' + name;
  }

  // Step 6: truncate
  if (name.length > maxLen) {
    name = name.slice(0, maxLen);
  }

  // Step 7: strip trailing hyphen from truncation
  name = name.replace(/-+$/, '');

  // Step 8: fallback
  if (name.length === 0) {
    name = typeShort || 'resource';
  }

  return name;
}
