/**
 * AWS-to-GCP region mapping and availability zone helpers.
 *
 * Re-exports the GCP column of the canonical REGION_MAP from
 * `attribute-transformer` to keep a single source of truth, then adds
 * GCP-specific helpers such as AZ-to-zone-letter conversion.
 *
 * @module codegen/gcp/region-mapping
 * @generated by code-generator (TASK-TRANS-007)
 */

import { REGION_MAP } from '../../engines/direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// AWS -> GCP region map (derived from the canonical REGION_MAP)
// ---------------------------------------------------------------------------

/**
 * Maps AWS region identifiers to GCP region names.
 * 16 entries covering all major AWS regions.
 */
export const AWS_TO_GCP_REGION: ReadonlyMap<string, string> = new Map(
  [...REGION_MAP.entries()].map(([aws, targets]) => [aws, targets.gcp]),
);

// ---------------------------------------------------------------------------
// Region resolution
// ---------------------------------------------------------------------------

/** Default GCP region when no mapping is found. */
const DEFAULT_GCP_REGION = 'us-central1';

/**
 * Resolves an AWS region to the corresponding GCP region.
 * Returns `'us-central1'` when no mapping exists.
 *
 * @param awsRegion - An AWS region string (e.g. `'us-west-2'`).
 * @returns The GCP region name.
 */
export function resolveGcpRegion(awsRegion: string): string {
  return AWS_TO_GCP_REGION.get(awsRegion) ?? DEFAULT_GCP_REGION;
}

// ---------------------------------------------------------------------------
// Availability zone helpers
// ---------------------------------------------------------------------------

/**
 * Converts an AWS availability zone to a GCP zone string.
 *
 * AWS AZs end in a letter (`a`, `b`, `c`, ...); GCP zones use the same
 * convention: `region-letter` (e.g. `'us-east1-b'`).
 *
 * @param awsAz - An AWS AZ string (e.g. `'us-east-1a'`).
 * @returns A GCP zone string (e.g. `'us-east1-a'`).
 */
export function awsAzToGcpZone(awsAz: string): string {
  if (!awsAz || awsAz.length === 0) {
    return resolveGcpRegion('') + '-a';
  }

  const lastChar = awsAz.charAt(awsAz.length - 1);
  const code = lastChar.charCodeAt(0);
  const offset = code - 'a'.charCodeAt(0);

  // Non-letter or out-of-range -> default zone 'a'
  if (Number.isNaN(code) || offset < 0 || offset > 25) {
    return resolveGcpRegion('') + '-a';
  }

  // Extract the region part (everything except the trailing letter)
  const regionPart = awsAz.slice(0, -1);
  const gcpRegion = resolveGcpRegion(regionPart);

  return gcpRegion + '-' + lastChar;
}
