/**
 * Shared helpers for the advisory (none-mapping) engine.
 * Advisory mappers emit NO translated resources — only findings with
 * migration guidance for resources that cannot be automatically translated.
 *
 * @module advisory/advisory-helpers
 * @generated by code-generator (TASK-TRANS-008)
 */

import type { TranslationFinding } from '@tla/shared';
import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import { createFinding } from '../direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Advisory stub builder
// ---------------------------------------------------------------------------

/**
 * Creates a standard advisory EngineResult: zero translated resources plus
 * a single warning finding that carries structured migration guidance.
 *
 * @param ctx            - Current translation context
 * @param advisoryCode   - Finding code (e.g. 'DYNAMODB_ADVISORY')
 * @param reason         - Human-readable explanation
 * @param migrationSteps - Ordered list of manual migration steps
 * @param alternatives   - Possible target-cloud alternatives
 */
export function createAdvisoryStub(
  ctx: TranslationContext,
  advisoryCode: string,
  reason: string,
  migrationSteps: readonly string[],
  alternatives: readonly string[],
): EngineResult {
  return {
    translated: [],
    findings: [
      createFinding(
        ctx.resource.id,
        'warning',
        advisoryCode,
        reason,
        JSON.stringify({ migrationSteps, alternatives }),
      ),
    ],
  };
}

// ---------------------------------------------------------------------------
// Manual task finding helper
// ---------------------------------------------------------------------------

/**
 * Creates a standalone warning finding for a manual migration task.
 */
export function createManualTaskFinding(
  resourceId: string,
  code: string,
  message: string,
  detail: string,
): TranslationFinding {
  return createFinding(resourceId, 'warning', code, message, detail);
}
