/**
 * Advisory mapper for aws_cloudfront_distribution.
 *
 * CloudFront CDN configurations require manual migration — origin
 * routing, cache behaviours, and edge function patterns differ across clouds.
 *
 * @module advisory/cloudfront-advisory
 * @generated by code-generator (TASK-TRANS-008)
 */

import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import { createAdvisoryStub } from './advisory-helpers.js';

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Emits advisory findings for aws_cloudfront_distribution.
 */
export function translateCloudfront(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return createAdvisoryStub(
      ctx,
      'CLOUDFRONT_ADVISORY',
      'CloudFront distribution requires manual migration to Azure Front Door or Azure CDN. ' +
        'Origin routing, cache policies, and edge functions must be redesigned.',
      [
        'Inventory CloudFront origins, cache behaviours, and edge functions',
        'Choose Azure Front Door (global load balancing + CDN) or Azure CDN (pure CDN)',
        'Map origin groups to Azure Front Door origin groups or CDN endpoints',
        'Translate cache behaviours to Azure Front Door routing rules or CDN caching rules',
        'Migrate Lambda@Edge / CloudFront Functions to Azure Front Door Rules Engine',
        'Update DNS records to point to the Azure Front Door or CDN endpoint',
      ],
      ['Azure Front Door', 'Azure CDN (Standard/Premium)'],
    );
  }

  return createAdvisoryStub(
    ctx,
    'CLOUDFRONT_ADVISORY',
    'CloudFront distribution requires manual migration to GCP Cloud CDN. ' +
      'GCP CDN is tightly coupled with external HTTP(S) Load Balancer — architecture differs significantly.',
    [
      'Inventory CloudFront origins, cache behaviours, and edge functions',
      'Create external HTTP(S) Load Balancer with Cloud CDN enabled',
      'Map CloudFront origins to backend services or backend buckets',
      'Configure Cloud CDN cache policies to match CloudFront cache behaviours',
      'Migrate Lambda@Edge to Cloud Functions or Cloud Run behind the load balancer',
      'Update DNS records to point to the load balancer frontend IP',
    ],
    ['Cloud CDN with external HTTP(S) LB', 'Cloud CDN with Cloud Armor'],
  );
}
