/**
 * Advisory mapper for aws_elasticache_cluster.
 *
 * This covers standalone ElastiCache clusters (non-replication-group).
 * aws_elasticache_replication_group is handled by the direct engine.
 *
 * Standalone clusters may use Memcached or Redis in single-node mode,
 * requiring different target-cloud equivalents.
 *
 * @module advisory/elasticache-cluster-advisory
 * @generated by code-generator (TASK-TRANS-008)
 */

import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import { createAdvisoryStub } from './advisory-helpers.js';

// ---------------------------------------------------------------------------
// Engine detection helper
// ---------------------------------------------------------------------------

function getEngine(ctx: TranslationContext): 'memcached' | 'redis' {
  const attrs = ctx.resource.attributes as Record<string, unknown>;
  const engine = typeof attrs['engine'] === 'string' ? attrs['engine'].toLowerCase() : '';
  return engine === 'memcached' ? 'memcached' : 'redis';
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Emits advisory findings for aws_elasticache_cluster.
 */
export function translateElasticacheCluster(ctx: TranslationContext): EngineResult {
  const engine = getEngine(ctx);

  if (ctx.targetProvider === 'azure') {
    return createAdvisoryStub(
      ctx,
      'ELASTICACHE_CLUSTER_ADVISORY',
      `ElastiCache cluster (${engine}) requires manual migration to Azure Cache for Redis. ` +
        (engine === 'memcached'
          ? 'Memcached has no native Azure equivalent — Redis is the recommended replacement.'
          : 'Standalone Redis clusters should be migrated to Azure Cache for Redis with appropriate SKU.'),
      [
        `Inventory ElastiCache cluster configuration (engine: ${engine}, node type, parameter group)`,
        engine === 'memcached'
          ? 'Redesign caching layer to use Redis data structures instead of Memcached'
          : 'Select Azure Cache for Redis SKU matching current node type and memory',
        'Configure virtual network integration for private access',
        'Migrate data using Redis DUMP/RESTORE or application-level cache warming',
        'Update application connection strings and client libraries',
      ],
      ['Azure Cache for Redis (Basic/Standard/Premium)', 'Azure Cache for Redis Enterprise'],
    );
  }

  return createAdvisoryStub(
    ctx,
    'ELASTICACHE_CLUSTER_ADVISORY',
    `ElastiCache cluster (${engine}) requires manual migration to GCP Memorystore. ` +
      (engine === 'memcached'
        ? 'GCP offers Memorystore for Memcached as a managed replacement.'
        : 'Standalone Redis clusters should be migrated to Memorystore for Redis.'),
    [
      `Inventory ElastiCache cluster configuration (engine: ${engine}, node type, parameter group)`,
      engine === 'memcached'
        ? 'Create Memorystore for Memcached instance with equivalent node count and memory'
        : 'Create Memorystore for Redis instance with appropriate tier and memory size',
      'Configure authorized VPC network for private access',
      engine === 'memcached'
        ? 'Update application to use Memorystore for Memcached endpoint'
        : 'Migrate data using Redis DUMP/RESTORE or application-level cache warming',
      'Update application connection strings and client libraries',
    ],
    engine === 'memcached'
      ? ['Memorystore for Memcached', 'Memorystore for Redis']
      : ['Memorystore for Redis', 'Memorystore for Redis Cluster'],
  );
}
