/**
 * Advisory mapper for aws_iam_role and aws_iam_policy.
 *
 * IAM concepts do not translate 1:1 across clouds. Each provider has a
 * unique identity and access management model that requires manual redesign.
 *
 * SECURITY: Policy document content is NEVER included in findings to
 * prevent accidental exposure of permission details in reports.
 *
 * @module advisory/iam-advisory
 * @generated by code-generator (TASK-TRANS-008)
 */

import type { TranslationContext, EngineResult } from '../mapping-engine.js';
import { createAdvisoryStub } from './advisory-helpers.js';

// ---------------------------------------------------------------------------
// Azure guidance
// ---------------------------------------------------------------------------

function advisoryAzure(ctx: TranslationContext): EngineResult {
  const sourceType = ctx.resource.sourceType;
  const isRole = sourceType === 'aws_iam_role';

  return createAdvisoryStub(
    ctx,
    'IAM_ADVISORY',
    `AWS ${isRole ? 'IAM Role' : 'IAM Policy'} requires manual migration to Azure RBAC / Entra ID. ` +
      'AWS IAM policies have no direct Azure equivalent — Azure uses role assignments and managed identities.',
    [
      `Audit the AWS ${isRole ? 'role trust policy and attached policies' : 'policy document actions and resources'}`,
      'Map AWS actions to Azure RBAC built-in roles or create custom role definitions',
      isRole
        ? 'Create Azure Managed Identity (system-assigned or user-assigned) for workload identity'
        : 'Define Azure Policy or RBAC role assignment with equivalent scope',
      'Configure role assignments at the appropriate scope (subscription, resource group, resource)',
      'Replace AWS STS assume-role calls with Azure Managed Identity token acquisition',
      'Validate least-privilege access with Azure Access Reviews',
    ],
    isRole
      ? ['Azure Managed Identity', 'Azure AD App Registration', 'Entra Workload Identity']
      : ['Azure RBAC Role Definition', 'Azure Policy', 'Entra ID Conditional Access'],
  );
}

// ---------------------------------------------------------------------------
// GCP guidance
// ---------------------------------------------------------------------------

function advisoryGcp(ctx: TranslationContext): EngineResult {
  const sourceType = ctx.resource.sourceType;
  const isRole = sourceType === 'aws_iam_role';

  return createAdvisoryStub(
    ctx,
    'IAM_ADVISORY',
    `AWS ${isRole ? 'IAM Role' : 'IAM Policy'} requires manual migration to GCP IAM. ` +
      'GCP uses a resource-hierarchy-based IAM model with service accounts instead of IAM roles.',
    [
      `Audit the AWS ${isRole ? 'role trust policy and attached policies' : 'policy document actions and resources'}`,
      'Map AWS actions to GCP IAM predefined roles or create custom roles',
      isRole
        ? 'Create GCP Service Account for workload identity'
        : 'Define GCP IAM policy bindings at the appropriate resource level',
      'Configure Workload Identity Federation for cross-cloud access if needed',
      'Replace AWS STS calls with GCP service account key or Workload Identity token exchange',
      'Validate access with IAM Policy Analyzer and Recommender',
    ],
    isRole
      ? ['GCP Service Account', 'GCP Workload Identity Federation', 'GCP IAM Custom Role']
      : ['GCP IAM Policy Binding', 'GCP Organization Policy', 'GCP IAM Custom Role'],
  );
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Emits advisory findings for aws_iam_role or aws_iam_policy.
 */
export function translateIam(ctx: TranslationContext): EngineResult {
  if (ctx.targetProvider === 'azure') {
    return advisoryAzure(ctx);
  }
  return advisoryGcp(ctx);
}
