/**
 * Generates Azure Storage (azurerm) backend configuration from S3 attributes.
 *
 * @module state/azure-backend
 * @generated by code-generator (TASK-DATA-004)
 */

import type { HclMapEntry, HclValue } from '../codegen/hcl-writer.js';
import { literal, expr, block } from '../codegen/hcl-writer.js';
import type { S3BackendAttributes } from './s3-detector.js';

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

export interface AzureBackendOptions {
  /** Override resource group name (default: var.resource_group_name). */
  readonly resourceGroupName?: string;
  /** Override storage account name (default: var.storage_account_name). */
  readonly storageAccountName?: string;
  /** Override container name (default: derived from bucket). */
  readonly containerName?: string;
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Generates an Azure Storage backend HclMapEntry from S3 backend attributes.
 *
 * Mapping:
 * - bucket -> container_name
 * - key -> key (passthrough)
 * - resource_group_name, storage_account_name via var.* expressions
 *
 * @returns An HclMapEntry with key `backend "azurerm"` and a block value.
 */
export function generateAzureBackend(
  attrs: S3BackendAttributes,
  options?: AzureBackendOptions,
): HclMapEntry {
  const body: Record<string, HclValue> = {
    resource_group_name: expr(
      options?.resourceGroupName ?? 'var.resource_group_name',
    ),
    storage_account_name: expr(
      options?.storageAccountName ?? 'var.storage_account_name',
    ),
    container_name: literal(options?.containerName ?? attrs.bucket),
    key: literal(attrs.key),
  };

  return {
    key: 'backend "azurerm"',
    value: block(body),
  };
}
