/**
 * Orchestrates the full state backend migration pipeline:
 * detect -> scrub -> generate -> runbook.
 *
 * @module state/backend-migrator
 * @generated by code-generator (TASK-DATA-004)
 */

import type { HclBackend } from '@tla/shared';
import type { TranslationFinding } from '@tla/shared';
import type { HclMapEntry } from '../codegen/hcl-writer.js';
import { writeTerraformBlock } from '../codegen/hcl-writer.js';
import { detectS3Backend } from './s3-detector.js';
import type { S3BackendAttributes } from './s3-detector.js';
import { scrubCredentials } from './credential-scrubber.js';
import { generateAzureBackend } from './azure-backend.js';
import type { AzureBackendOptions } from './azure-backend.js';
import { generateGcpBackend } from './gcp-backend.js';
import type { GcpBackendOptions } from './gcp-backend.js';
import { generateRunbook } from './runbook-generator.js';
import type { TargetProvider } from './runbook-generator.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface BackendMigrationOptions {
  /** Target cloud provider. */
  readonly targetProvider: TargetProvider;
  /** Azure-specific overrides. */
  readonly azure?: AzureBackendOptions;
  /** GCP-specific overrides. */
  readonly gcp?: GcpBackendOptions;
}

export interface BackendMigrationResult {
  /** The detected S3 backend attributes (after scrubbing). */
  readonly sourceAttrs: S3BackendAttributes;
  /** The generated target backend HCL entry. */
  readonly targetBackend: HclMapEntry;
  /** The rendered HCL snippet for the target backend. */
  readonly hclSnippet: string;
  /** The migration runbook in Markdown. */
  readonly runbook: string;
  /** All findings from detection, scrubbing, and generation. */
  readonly findings: readonly TranslationFinding[];
}

// ---------------------------------------------------------------------------
// Orchestrator
// ---------------------------------------------------------------------------

/**
 * Runs the full state backend migration pipeline.
 *
 * @param backend - The parsed HCL backend block.
 * @param options - Migration options (target provider, overrides).
 * @returns The migration result, or null if the backend is not S3.
 */
export function migrateBackend(
  backend: HclBackend,
  options: BackendMigrationOptions,
): BackendMigrationResult | null {
  // 1. Detect S3 backend
  const detection = detectS3Backend(backend);
  if (detection === null) {
    return null;
  }

  const allFindings: TranslationFinding[] = [...detection.findings];

  // 2. Scrub credentials — we only need the findings here because
  //    detection.attrs already contains the typed (credential-free) attributes.
  //    The scrubbed map is intentionally unused.
  const { findings: scrubFindings } = scrubCredentials(backend.attributes);
  allFindings.push(...scrubFindings);

  // 3. Generate target backend
  let targetBackend: HclMapEntry;
  if (options.targetProvider === 'azure') {
    targetBackend = generateAzureBackend(detection.attrs, options.azure);
  } else {
    targetBackend = generateGcpBackend(detection.attrs, options.gcp);
  }

  // 4. Render HCL snippet
  const hclSnippet = writeTerraformBlock([targetBackend]);

  // 5. Generate runbook
  const runbook = generateRunbook(
    detection.attrs,
    options.targetProvider,
    hclSnippet,
  );

  return {
    sourceAttrs: detection.attrs,
    targetBackend,
    hclSnippet,
    runbook,
    findings: allFindings,
  };
}
