/**
 * Generates GCS backend configuration from S3 attributes.
 *
 * @module state/gcp-backend
 * @generated by code-generator (TASK-DATA-004)
 */

import type { HclMapEntry, HclValue } from '../codegen/hcl-writer.js';
import { literal, block } from '../codegen/hcl-writer.js';
import type { S3BackendAttributes } from './s3-detector.js';

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

export interface GcpBackendOptions {
  /** Override GCS bucket name (default: same as S3 bucket). */
  readonly bucket?: string;
  /** Override prefix (default: derived from key path). */
  readonly prefix?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Extracts the directory prefix from an S3 key path.
 * e.g. "env/prod/terraform.tfstate" -> "env/prod"
 * If no directory component, returns the key as-is.
 */
function keyToPrefix(key: string): string {
  const lastSlash = key.lastIndexOf('/');
  if (lastSlash > 0) {
    return key.substring(0, lastSlash);
  }
  return key;
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Generates a GCS backend HclMapEntry from S3 backend attributes.
 *
 * Mapping:
 * - bucket -> bucket
 * - key path directory -> prefix
 *
 * @returns An HclMapEntry with key `backend "gcs"` and a block value.
 */
export function generateGcpBackend(
  attrs: S3BackendAttributes,
  options?: GcpBackendOptions,
): HclMapEntry {
  const body: Record<string, HclValue> = {
    bucket: literal(options?.bucket ?? attrs.bucket),
    prefix: literal(options?.prefix ?? keyToPrefix(attrs.key)),
  };

  return {
    key: 'backend "gcs"',
    value: block(body),
  };
}
