/**
 * State backend migration module.
 *
 * @module state
 * @generated by code-generator (TASK-DATA-004)
 */

export { detectS3Backend } from './s3-detector.js';
export type { S3BackendAttributes, S3DetectionResult } from './s3-detector.js';

export { scrubCredentials } from './credential-scrubber.js';
export type { ScrubResult } from './credential-scrubber.js';

export { generateAzureBackend } from './azure-backend.js';
export type { AzureBackendOptions } from './azure-backend.js';

export { generateGcpBackend } from './gcp-backend.js';
export type { GcpBackendOptions } from './gcp-backend.js';

export { generateRunbook } from './runbook-generator.js';
export type { TargetProvider } from './runbook-generator.js';

export { migrateBackend } from './backend-migrator.js';
export type { BackendMigrationOptions, BackendMigrationResult } from './backend-migrator.js';

export { transformState } from './state-transformer.js';
export type {
  StateTransformPlan,
  StateMoveCommand,
  StateImportCommand,
  StateRemoveCommand,
} from './state-transformer.js';

export { shellQuote } from './shell-quote.js';

export { generateRollback } from './rollback-generator.js';
export type {
  RollbackManifest,
  InverseMoveCommand,
  InverseImportCommand,
} from './rollback-generator.js';
