/**
 * Generates rollback manifests for state transformation plans.
 *
 * Given the forward move/import/remove commands, produces an inverse
 * manifest that can undo the transformation by restoring from a snapshot.
 *
 * @module state/rollback-generator
 * @generated by code-generator (TASK-DATA-005)
 */

import type {
  StateMoveCommand,
  StateImportCommand,
  StateRemoveCommand,
} from './state-transformer.js';
import { shellQuote } from './shell-quote.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * An inverse move command (swaps source and destination).
 */
export interface InverseMoveCommand {
  readonly source: string;
  readonly destination: string;
  readonly commandString: string;
}

/**
 * An inverse import command (removes the imported address).
 */
export interface InverseImportCommand {
  readonly address: string;
  readonly commandString: string;
}

/**
 * A manifest describing how to undo a state transformation.
 */
export interface RollbackManifest {
  readonly snapshotRef: string;
  readonly inverseMoves: readonly InverseMoveCommand[];
  readonly inverseImports: readonly InverseImportCommand[];
  readonly inverseRemoves: readonly string[];
  readonly timestamp: string;
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Generates a rollback manifest from forward transformation commands.
 *
 * - Forward moves become inverse moves (source/destination swapped).
 * - Forward imports become state rm commands for the imported address.
 * - Forward removes become warning strings (must restore from snapshot).
 *
 * @param moves    - Forward move commands.
 * @param imports  - Forward import commands.
 * @param removes  - Forward remove commands.
 * @param timestamp - Optional ISO timestamp (defaults to current time).
 * @returns A rollback manifest with inverse operations.
 */
export function generateRollback(
  moves: readonly StateMoveCommand[],
  imports: readonly StateImportCommand[],
  removes: readonly StateRemoveCommand[],
  timestamp?: string,
): RollbackManifest {
  const ts = timestamp ?? new Date().toISOString();

  const inverseMoves: InverseMoveCommand[] = [...moves]
    .sort((a, b) => a.source.localeCompare(b.source))
    .map((m) => ({
      source: m.destination,
      destination: m.source,
      commandString: `terraform state mv ${shellQuote(m.destination)} ${shellQuote(m.source)}`,
    }));

  const inverseImports: InverseImportCommand[] = [...imports]
    .sort((a, b) => a.address.localeCompare(b.address))
    .map((imp) => ({
      address: imp.address,
      commandString: `terraform state rm ${shellQuote(imp.address)}`,
    }));

  const inverseRemoves: string[] = [...removes]
    .sort((a, b) => a.address.localeCompare(b.address))
    .map(
      (r) =>
        `WARNING: Cannot auto-reverse removal of ${shellQuote(r.address)}. ` +
        `Restore from snapshot ${shellQuote(`tfstate-snapshot-${ts}`)}.`,
    );

  return {
    snapshotRef: `tfstate-snapshot-${ts}`,
    inverseMoves,
    inverseImports,
    inverseRemoves,
    timestamp: ts,
  };
}
