/**
 * Generates a Markdown migration runbook for state backend migration.
 *
 * @module state/runbook-generator
 * @generated by code-generator (TASK-DATA-004)
 */

import type { S3BackendAttributes } from './s3-detector.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type TargetProvider = 'azure' | 'gcp';

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Generates a Markdown migration runbook.
 *
 * @param attrs - The detected S3 backend attributes.
 * @param provider - The target cloud provider ('azure' | 'gcp').
 * @param hclSnippet - The rendered HCL backend block for the target.
 * @param generatedDate - Optional ISO date string (YYYY-MM-DD) for the header.
 *   Defaults to today's date. Accepting this parameter keeps output deterministic
 *   for tests and reproducible builds.
 * @returns A complete Markdown runbook string.
 */
export function generateRunbook(
  attrs: S3BackendAttributes,
  provider: TargetProvider,
  hclSnippet: string,
  generatedDate?: string,
): string {
  const providerLabel = provider === 'azure' ? 'Azure Storage' : 'Google Cloud Storage';
  const backendType = provider === 'azure' ? 'azurerm' : 'gcs';
  const initCmd = 'terraform init -migrate-state';

  const sections: string[] = [];

  // 1. Header
  sections.push(
    `# Terraform State Backend Migration Runbook`,
    '',
    `**Source**: S3 backend (bucket: \`${attrs.bucket}\`, key: \`${attrs.key}\`)`,
    `**Target**: ${providerLabel} backend (\`${backendType}\`)`,
    `**Generated**: ${generatedDate ?? new Date().toISOString().split('T')[0]}`,
    '',
  );

  // 2. Source Configuration
  sections.push(
    '## 1. Source Configuration (Current)',
    '',
    '```hcl',
    'backend "s3" {',
    `  bucket = "${attrs.bucket}"`,
    `  key    = "${attrs.key}"`,
  );
  if (attrs.region) {
    sections.push(`  region = "${attrs.region}"`);
  }
  if (attrs.encrypt !== undefined) {
    sections.push(`  encrypt = ${attrs.encrypt}`);
  }
  if (attrs.dynamodb_table) {
    sections.push(`  dynamodb_table = "${attrs.dynamodb_table}"`);
  }
  sections.push('}', '```', '');

  // 3. Target Configuration
  sections.push(
    '## 2. Target Configuration',
    '',
    '```hcl',
    hclSnippet,
    '```',
    '',
  );

  // 4. Pre-Migration Checklist
  sections.push(
    '## 3. Pre-Migration Checklist',
    '',
    '- [ ] Back up current state file: `terraform state pull > backup.tfstate`',
    `- [ ] Verify ${providerLabel} target resource exists and is accessible`,
    '- [ ] Ensure no other team members are running Terraform operations',
    '- [ ] Confirm CI/CD pipelines are paused',
  );
  if (attrs.dynamodb_table) {
    sections.push(`- [ ] Note: DynamoDB lock table \`${attrs.dynamodb_table}\` will not be migrated (target uses native locking)`);
  }
  if (attrs.workspace_key_prefix) {
    sections.push(`- [ ] Workspace prefix \`${attrs.workspace_key_prefix}\` requires manual workspace setup on target`);
  }
  sections.push('');

  // 5. Migration Steps
  sections.push(
    '## 4. Migration Steps',
    '',
    '1. Replace the backend block in your Terraform configuration with the target configuration above.',
    '',
    '2. Run the migration:',
    '   ```bash',
    `   ${initCmd}`,
    '   ```',
    '',
    '3. When prompted, confirm the state migration by typing `yes`.',
    '',
    '4. Verify the migration completed without errors.',
    '',
  );

  // 6. Verification
  sections.push(
    '## 5. Verification',
    '',
    '```bash',
    '# Verify state is accessible',
    'terraform state list',
    '',
    '# Run a plan to confirm no unexpected changes',
    'terraform plan',
    '```',
    '',
    'Expected: `No changes. Your infrastructure matches the configuration.`',
    '',
  );

  // 7. Rollback
  sections.push(
    '## 6. Rollback',
    '',
    'If the migration fails:',
    '',
    '1. Restore the original S3 backend block in your configuration.',
    '',
    '2. Restore the backed-up state:',
    '   ```bash',
    '   terraform init -migrate-state',
    '   # Or force push the backup:',
    '   terraform state push backup.tfstate',
    '   ```',
    '',
    '3. Verify with `terraform state list` and `terraform plan`.',
    '',
  );

  return sections.join('\n');
}
