/**
 * Detects S3 backend configuration and extracts typed attributes.
 *
 * @module state/s3-detector
 * @generated by code-generator (TASK-DATA-004)
 */

import type { HclBackend } from '@tla/shared';
import type { TranslationFinding } from '@tla/shared';
import { createFinding } from '../engines/direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Exported types
// ---------------------------------------------------------------------------

export interface S3BackendAttributes {
  readonly bucket: string;
  readonly key: string;
  readonly region?: string;
  readonly encrypt?: boolean;
  readonly dynamodb_table?: string;
  readonly workspace_key_prefix?: string;
  readonly profile?: string;
  readonly role_arn?: string;
  readonly acl?: string;
}

// ---------------------------------------------------------------------------
// Detection result
// ---------------------------------------------------------------------------

export interface S3DetectionResult {
  readonly attrs: S3BackendAttributes;
  readonly findings: readonly TranslationFinding[];
}

const RESOURCE_ID = 'terraform.backend';

// ---------------------------------------------------------------------------
// Detector
// ---------------------------------------------------------------------------

/**
 * Detects an S3 backend block and extracts typed attributes.
 * Returns null if the backend type is not 's3'.
 */
export function detectS3Backend(backend: HclBackend): S3DetectionResult | null {
  if (backend.type !== 's3') {
    return null;
  }

  const a = backend.attributes;
  const findings: TranslationFinding[] = [];

  const bucket = typeof a['bucket'] === 'string' ? a['bucket'] : '';
  const key = typeof a['key'] === 'string' ? a['key'] : '';

  const attrs: S3BackendAttributes = {
    bucket,
    key,
    region: typeof a['region'] === 'string' ? a['region'] : undefined,
    encrypt: typeof a['encrypt'] === 'boolean' ? a['encrypt'] : undefined,
    dynamodb_table: typeof a['dynamodb_table'] === 'string' ? a['dynamodb_table'] : undefined,
    workspace_key_prefix: typeof a['workspace_key_prefix'] === 'string' ? a['workspace_key_prefix'] : undefined,
    profile: typeof a['profile'] === 'string' ? a['profile'] : undefined,
    role_arn: typeof a['role_arn'] === 'string' ? a['role_arn'] : undefined,
    acl: typeof a['acl'] === 'string' ? a['acl'] : undefined,
  };

  findings.push(
    createFinding(RESOURCE_ID, 'info', 'STATE_BACKEND_DETECTED', `S3 backend detected: bucket=${bucket}, key=${key}`),
  );

  if (attrs.workspace_key_prefix !== undefined) {
    findings.push(
      createFinding(
        RESOURCE_ID,
        'warning',
        'STATE_WORKSPACE_ADVISORY',
        'Terraform workspaces detected via workspace_key_prefix; target backend may require manual workspace setup',
      ),
    );
  }

  if (attrs.dynamodb_table !== undefined) {
    findings.push(
      createFinding(
        RESOURCE_ID,
        'warning',
        'STATE_DYNAMO_LOCK_ADVISORY',
        `DynamoDB state locking table '${attrs.dynamodb_table}' has no direct equivalent; target backend uses native locking`,
      ),
    );
  }

  return { attrs, findings };
}
