/**
 * Exit-path generator — produces native Terraform HCL strings for portable
 * resources without going through the full translation pipeline.
 *
 * Useful for:
 *   - Generating human-readable migration guides
 *   - Emitting provider-specific HCL snippets in advisory outputs
 *   - Tooling that needs raw HCL strings rather than TranslatedResource objects
 *
 * @module provider/exit-path
 * @generated by code-generator (TASK-MCP-006)
 */

import type { CloudProvider } from '@tla/shared';
import type { PortableResource } from '@tla/shared';
import { compilePortableResource } from './portable-compiler.js';
import {
  writeResourceBlock,
  literal,
  block,
  hclMap,
  list,
} from '../codegen/hcl-writer.js';
import type { HclValue, HclMapEntry } from '../codegen/hcl-writer.js';

// ---------------------------------------------------------------------------
// Value converter
// ---------------------------------------------------------------------------

/**
 * Converts an unknown attribute value from a TranslatedResource to an HclValue.
 *
 * Handles:
 *   - null / undefined  → literal(null)
 *   - string / number / boolean → literal(v)
 *   - Array              → list of converted items
 *   - plain object       → block with recursively converted entries
 */
function toHclValue(value: unknown): HclValue {
  if (value === null || value === undefined) {
    return literal(null);
  }
  if (typeof value === 'boolean') {
    return literal(value);
  }
  if (typeof value === 'number') {
    return literal(value);
  }
  if (typeof value === 'string') {
    return literal(value);
  }
  if (Array.isArray(value)) {
    return list(value.map(toHclValue));
  }
  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    const body: Record<string, HclValue> = {};
    for (const [k, v] of Object.entries(obj)) {
      body[k] = toHclValue(v);
    }
    return block(body);
  }
  // Fallback for unexpected types
  return literal(String(value));
}

/**
 * Converts a flat attributes record to an array of HclMapEntry values,
 * sorted by key for deterministic output.
 */
function attrsToEntries(attrs: Record<string, unknown>): HclMapEntry[] {
  return Object.keys(attrs)
    .sort()
    .map((key) => ({ key, value: toHclValue(attrs[key]) }));
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates a native Terraform HCL string for the given portable resource
 * when targeting the specified cloud provider.
 *
 * The output is a complete, self-contained set of `resource "..." "..." { }`
 * blocks (multiple blocks separated by blank lines when the portable type
 * expands into more than one native resource, e.g. Azure storage account +
 * storage container).
 *
 * @param resource - The portable resource descriptor.
 * @param target   - The target cloud provider.
 * @returns A valid HCL string ready to write to a `.tf` file.
 *
 * @example
 * ```ts
 * const hcl = emitNativeEquivalent(
 *   { resource_type: 'cloud_object_storage', name: 'my-bucket', versioning_enabled: true },
 *   'aws',
 * );
 * // → resource "aws_s3_bucket" "my-bucket" { ... }
 * ```
 */
export function emitNativeEquivalent(
  resource: PortableResource,
  target: CloudProvider,
): string {
  const { translated } = compilePortableResource(resource, target);

  const blocks: string[] = translated.map((tr) => {
    const entries = attrsToEntries(tr.attributes as Record<string, unknown>);
    return writeResourceBlock(tr.targetType, tr.targetName, entries, {
      comment: `Portable source: ${resource.resource_type} "${resource.name}" → ${target}`,
      sortKeys: false, // entries are already sorted by attrsToEntries
    });
  });

  return blocks.join('\n\n');
}
