/**
 * Portable resource compiler — translates cloud_* resources into native
 * provider-specific Terraform resources.
 *
 * Supported portable types:
 *   cloud_object_storage      → aws_s3_bucket / azurerm_storage_account + container / google_storage_bucket
 *   cloud_container_registry  → aws_ecr_repository / azurerm_container_registry / google_artifact_registry_repository
 *   cloud_cache_redis         → aws_elasticache_replication_group / azurerm_redis_cache / google_redis_instance
 *
 * Unsupported attributes are surfaced as explicit error findings — they are
 * NEVER silently dropped.
 *
 * @module provider/portable-compiler
 * @generated by code-generator (TASK-MCP-006)
 */

import type { CloudProvider, TranslatedResource, TranslationFinding } from '@tla/shared';
import type {
  PortableResource,
  CloudObjectStorage,
  CloudContainerRegistry,
  CloudCacheRedis,
} from '@tla/shared';
import { createFinding } from '../engines/direct/attribute-transformer.js';
import {
  REGION_MAP,
  NODE_TYPE_SKU_MAP,
} from '../engines/direct/attribute-transformer.js';

// ---------------------------------------------------------------------------
// Result type
// ---------------------------------------------------------------------------

/**
 * Result of compiling a single portable resource.
 */
export interface PortableCompileResult {
  readonly translated: TranslatedResource[];
  readonly findings: TranslationFinding[];
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Baseline traceability for portable-compiled resources.
 */
function makePortableTraceability(
  resourceName: string,
  resourceType: string,
  target: CloudProvider,
): TranslatedResource['traceability'] {
  return {
    sourceId: `portable:${resourceType}:${resourceName}`,
    sourceType: resourceType,
    registryEntryId: null,
    mappingType: 'direct',
    confidence: 0.9,
    engineUsed: `portable-compiler/${target}`,
  };
}

/**
 * Normalises a resource name for the target provider.
 * - AWS / GCP: allow alphanumeric, hyphens, underscores
 * - Azure: strip non-alphanumeric (storage accounts require ^[a-z0-9]{3,24})
 */
function normalizeNameForProvider(name: string, target: CloudProvider): string {
  if (target === 'azure') {
    return name.replace(/[^a-z0-9]/g, '').slice(0, 24);
  }
  return name;
}

/**
 * Converts portable tags to provider label format.
 * GCP labels must be lowercase [a-z0-9_-].
 */
function convertTags(
  tags: Record<string, string>,
  target: CloudProvider,
): Record<string, string> {
  if (target === 'gcp') {
    const result: Record<string, string> = {};
    for (const [k, v] of Object.entries(tags)) {
      result[k.toLowerCase().replace(/[^a-z0-9_-]/g, '_')] = v;
    }
    return result;
  }
  return { ...tags };
}

/**
 * Resolves a default AWS region to the target provider region string.
 */
function defaultRegion(target: CloudProvider): string {
  const entry = REGION_MAP.get('us-east-1');
  if (!entry) return 'us-east-1';
  return target === 'azure' ? entry.azure : entry.gcp;
}

// ---------------------------------------------------------------------------
// Redis size → SKU mapping
// ---------------------------------------------------------------------------

/** Maps portable size to the closest node type for SKU lookup. */
const SIZE_TO_NODE_TYPE: Record<string, string> = {
  xs: 'cache.t3.micro',
  sm: 'cache.t3.medium',
  md: 'cache.m5.large',
  lg: 'cache.r5.large',
  xl: 'cache.r5.2xlarge',
};

function parseAzureSku(sku: string): { sku_name: string; family: string; capacity: number } {
  const parts = sku.split('_');
  const tier = parts[0] ?? 'Standard';
  const sizeCode = parts[1] ?? 'C1';
  const family = sizeCode.charAt(0);
  const capacity = parseInt(sizeCode.slice(1), 10) || 1;
  return { sku_name: tier, family, capacity };
}

function parseGcpTier(tierStr: string): { tier: string; memory_size_gb: number } {
  const isHa = tierStr.includes('HA');
  const gbMatch = tierStr.match(/(\d+)GB$/);
  const memorySizeGb = gbMatch ? parseInt(gbMatch[1]!, 10) : 1;
  return { tier: isHa ? 'STANDARD_HA' : 'BASIC', memory_size_gb: memorySizeGb };
}

// ---------------------------------------------------------------------------
// cloud_object_storage compilers
// ---------------------------------------------------------------------------

function compileObjectStorageAws(res: CloudObjectStorage): PortableCompileResult {
  const attrs: Record<string, unknown> = {
    bucket: res.name,
  };

  const findings: TranslationFinding[] = [];

  if (res.versioning_enabled === true) {
    attrs['versioning'] = { enabled: true };
  }

  if (res.encryption) {
    if (res.encryption.kms_key_ref) {
      attrs['server_side_encryption_configuration'] = {
        rule: {
          apply_server_side_encryption_by_default: {
            sse_algorithm: 'aws:kms',
            kms_master_key_id: res.encryption.kms_key_ref,
          },
        },
      };
    } else if (res.encryption.enabled) {
      attrs['server_side_encryption_configuration'] = {
        rule: {
          apply_server_side_encryption_by_default: {
            sse_algorithm: 'AES256',
          },
        },
      };
    }
  }

  if (res.tags) {
    attrs['tags'] = convertTags(res.tags, 'aws');
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'aws_s3_bucket',
      targetName: res.name,
      attributes: attrs,
      sourceId: `portable:cloud_object_storage:${res.name}`,
      traceability: makePortableTraceability(res.name, 'cloud_object_storage', 'aws'),
    },
  ];

  return { translated, findings };
}

function compileObjectStorageAzure(res: CloudObjectStorage): PortableCompileResult {
  const findings: TranslationFinding[] = [];
  const saName = normalizeNameForProvider(res.name, 'azure');

  const accountAttrs: Record<string, unknown> = {
    account_kind: 'StorageV2',
    account_replication_type: 'LRS',
    account_tier: 'Standard',
    location: defaultRegion('azure'),
    name: saName,
  };

  if (res.versioning_enabled === true) {
    accountAttrs['blob_properties'] = { versioning_enabled: true };
  }

  if (res.encryption?.kms_key_ref) {
    accountAttrs['customer_managed_key'] = {
      key_vault_key_id: res.encryption.kms_key_ref,
    };
  }

  if (res.tags) {
    accountAttrs['tags'] = convertTags(res.tags, 'azure');
  }

  const containerAttrs: Record<string, unknown> = {
    container_access_type: 'private',
    name: res.name,
    storage_account_name: saName,
  };

  const traceability = makePortableTraceability(res.name, 'cloud_object_storage', 'azure');

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_storage_account',
      targetName: `${res.name}_account`,
      attributes: accountAttrs,
      sourceId: `portable:cloud_object_storage:${res.name}`,
      traceability,
    },
    {
      targetType: 'azurerm_storage_container',
      targetName: `${res.name}_container`,
      attributes: containerAttrs,
      sourceId: `portable:cloud_object_storage:${res.name}`,
      traceability,
    },
  ];

  return { translated, findings };
}

function compileObjectStorageGcp(res: CloudObjectStorage): PortableCompileResult {
  const findings: TranslationFinding[] = [];

  const gcpAttrs: Record<string, unknown> = {
    location: defaultRegion('gcp'),
    name: res.name,
    storage_class: 'STANDARD',
  };

  if (res.versioning_enabled === true) {
    gcpAttrs['versioning'] = { enabled: true };
  }

  if (res.encryption?.kms_key_ref) {
    gcpAttrs['encryption'] = { default_kms_key_name: res.encryption.kms_key_ref };
  }

  if (res.tags) {
    gcpAttrs['labels'] = convertTags(res.tags, 'gcp');
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_storage_bucket',
      targetName: res.name,
      attributes: gcpAttrs,
      sourceId: `portable:cloud_object_storage:${res.name}`,
      traceability: makePortableTraceability(res.name, 'cloud_object_storage', 'gcp'),
    },
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// cloud_container_registry compilers
// ---------------------------------------------------------------------------

function compileContainerRegistryAws(res: CloudContainerRegistry): PortableCompileResult {
  const attrs: Record<string, unknown> = {
    name: res.name,
  };

  const findings: TranslationFinding[] = [];

  if (res.immutable_tags === true) {
    attrs['image_tag_mutability'] = 'IMMUTABLE';
  } else {
    attrs['image_tag_mutability'] = 'MUTABLE';
  }

  if (res.scan_on_push === true) {
    attrs['image_scanning_configuration'] = { scan_on_push: true };
  }

  if (res.encryption?.kms_key_ref) {
    attrs['encryption_configuration'] = {
      encryption_type: 'KMS',
      kms_key: res.encryption.kms_key_ref,
    };
  }

  if (res.tags) {
    attrs['tags'] = convertTags(res.tags, 'aws');
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'aws_ecr_repository',
      targetName: res.name,
      attributes: attrs,
      sourceId: `portable:cloud_container_registry:${res.name}`,
      traceability: makePortableTraceability(res.name, 'cloud_container_registry', 'aws'),
    },
  ];

  return { translated, findings };
}

function compileContainerRegistryAzure(res: CloudContainerRegistry): PortableCompileResult {
  const findings: TranslationFinding[] = [];
  const repoName = res.name.replace(/[^a-zA-Z0-9]/g, '');

  const azureAttrs: Record<string, unknown> = {
    admin_enabled: res.immutable_tags === true ? false : true,
    name: repoName,
    sku: 'Basic',
  };

  if (res.encryption?.kms_key_ref) {
    azureAttrs['sku'] = 'Premium';
    azureAttrs['encryption'] = { key_vault_key_id: res.encryption.kms_key_ref };
  }

  if (res.scan_on_push === true) {
    azureAttrs['trust_policy'] = { enabled: true };
  }

  if (res.tags) {
    azureAttrs['tags'] = convertTags(res.tags, 'azure');
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_container_registry',
      targetName: res.name,
      attributes: azureAttrs,
      sourceId: `portable:cloud_container_registry:${res.name}`,
      traceability: makePortableTraceability(res.name, 'cloud_container_registry', 'azure'),
    },
  ];

  return { translated, findings };
}

function compileContainerRegistryGcp(res: CloudContainerRegistry): PortableCompileResult {
  const findings: TranslationFinding[] = [];

  const gcpAttrs: Record<string, unknown> = {
    format: 'DOCKER',
    repository_id: res.name,
  };

  if (res.encryption?.kms_key_ref) {
    gcpAttrs['kms_key_name'] = res.encryption.kms_key_ref;
  }

  if (res.scan_on_push === true) {
    findings.push(
      createFinding(
        `portable:cloud_container_registry:${res.name}`,
        'info',
        'PORTABLE_REGISTRY_SCAN',
        'GCP Artifact Registry uses Container Analysis for vulnerability scanning (separate resource)',
      ),
    );
  }

  if (res.tags) {
    gcpAttrs['labels'] = convertTags(res.tags, 'gcp');
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_artifact_registry_repository',
      targetName: res.name,
      attributes: gcpAttrs,
      sourceId: `portable:cloud_container_registry:${res.name}`,
      traceability: makePortableTraceability(res.name, 'cloud_container_registry', 'gcp'),
    },
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// cloud_cache_redis compilers
// ---------------------------------------------------------------------------

function compileRedisAws(res: CloudCacheRedis): PortableCompileResult {
  const findings: TranslationFinding[] = [];
  const nodeType = SIZE_TO_NODE_TYPE[res.size ?? 'sm'] ?? 'cache.t3.medium';

  const attrs: Record<string, unknown> = {
    description: `Portable cache: ${res.name}`,
    node_type: nodeType,
    replication_group_id: res.name,
  };

  if (res.engine_version) {
    attrs['engine_version'] = res.engine_version;
  }

  if (res.replicas !== undefined && res.replicas > 0) {
    attrs['num_cache_clusters'] = res.replicas + 1;
    attrs['automatic_failover_enabled'] = true;
  }

  if (res.transit_encryption === true) {
    attrs['transit_encryption_enabled'] = true;
  }

  if (res.encryption?.enabled !== false) {
    attrs['at_rest_encryption_enabled'] = true;
  }

  if (res.encryption?.kms_key_ref) {
    attrs['kms_key_id'] = res.encryption.kms_key_ref;
  }

  if (res.tags) {
    attrs['tags'] = convertTags(res.tags, 'aws');
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'aws_elasticache_replication_group',
      targetName: res.name,
      attributes: attrs,
      sourceId: `portable:cloud_cache_redis:${res.name}`,
      traceability: makePortableTraceability(res.name, 'cloud_cache_redis', 'aws'),
    },
  ];

  return { translated, findings };
}

function compileRedisAzure(res: CloudCacheRedis): PortableCompileResult {
  const findings: TranslationFinding[] = [];
  const nodeType = SIZE_TO_NODE_TYPE[res.size ?? 'sm'] ?? 'cache.t3.medium';
  const skuEntry = NODE_TYPE_SKU_MAP.get(nodeType);

  let skuName = 'Standard';
  let family = 'C';
  let capacity = 1;

  if (skuEntry) {
    const parsed = parseAzureSku(skuEntry.azure);
    skuName = parsed.sku_name;
    family = parsed.family;
    capacity = parsed.capacity;
  }

  // At-rest encryption requires Premium tier on Azure
  if (res.encryption?.enabled !== false && skuName !== 'Premium') {
    findings.push(
      createFinding(
        `portable:cloud_cache_redis:${res.name}`,
        'warning',
        'PORTABLE_REDIS_ENCRYPTION_TIER',
        'At-rest encryption requires Premium SKU in Azure; the compiled SKU may need upgrading',
      ),
    );
  }

  const azureAttrs: Record<string, unknown> = {
    capacity,
    family,
    location: defaultRegion('azure'),
    name: res.name,
    redis_version: res.engine_version ?? '6',
    sku_name: skuName,
  };

  if (res.replicas !== undefined && res.replicas > 0) {
    azureAttrs['replicas_per_master'] = res.replicas;
    azureAttrs['shard_count'] = 1;
  }

  if (res.transit_encryption === true) {
    azureAttrs['enable_non_ssl_port'] = false;
    azureAttrs['minimum_tls_version'] = '1.2';
  }

  if (res.tags) {
    azureAttrs['tags'] = convertTags(res.tags, 'azure');
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'azurerm_redis_cache',
      targetName: res.name,
      attributes: azureAttrs,
      sourceId: `portable:cloud_cache_redis:${res.name}`,
      traceability: makePortableTraceability(res.name, 'cloud_cache_redis', 'azure'),
    },
  ];

  return { translated, findings };
}

function compileRedisGcp(res: CloudCacheRedis): PortableCompileResult {
  const findings: TranslationFinding[] = [];
  const nodeType = SIZE_TO_NODE_TYPE[res.size ?? 'sm'] ?? 'cache.t3.medium';
  const skuEntry = NODE_TYPE_SKU_MAP.get(nodeType);

  let tier = 'BASIC';
  let memorySizeGb = 4;

  if (skuEntry) {
    const parsed = parseGcpTier(skuEntry.gcp);
    tier = parsed.tier;
    memorySizeGb = parsed.memory_size_gb;
  }

  const gcpAttrs: Record<string, unknown> = {
    display_name: res.name,
    memory_size_gb: memorySizeGb,
    name: res.name,
    redis_version: res.engine_version
      ? `REDIS_${res.engine_version.replace('.', '_')}`
      : 'REDIS_6_X',
    region: defaultRegion('gcp'),
    tier,
  };

  if (res.replicas !== undefined && res.replicas > 0) {
    gcpAttrs['replica_count'] = res.replicas;
  }

  if (res.transit_encryption === true) {
    gcpAttrs['transit_encryption_mode'] = 'SERVER_AUTHENTICATION';
  }

  if (res.tags) {
    gcpAttrs['labels'] = convertTags(res.tags, 'gcp');
  }

  const translated: TranslatedResource[] = [
    {
      targetType: 'google_redis_instance',
      targetName: res.name,
      attributes: gcpAttrs,
      sourceId: `portable:cloud_cache_redis:${res.name}`,
      traceability: makePortableTraceability(res.name, 'cloud_cache_redis', 'gcp'),
    },
  ];

  return { translated, findings };
}

// ---------------------------------------------------------------------------
// Provider override helper
// ---------------------------------------------------------------------------

/**
 * Applies `provider_overrides` from the portable resource onto compiled
 * translated resources.
 *
 * Behaviour:
 *   - If `provider_overrides[target]` exists, every key in that map is
 *     shallow-merged into each translated resource's attributes.  One
 *     `PORTABLE_OVERRIDE_APPLIED` info finding is emitted per applied key.
 *   - If `provider_overrides` contains a key for a *different* provider
 *     (i.e. not the active target), a `PORTABLE_OVERRIDE_IGNORED` warning
 *     finding is emitted for that provider key so the caller is aware of
 *     the ignored configuration.
 *   - AWS overrides are not supported in `provider_overrides` (the field
 *     only accepts 'azure' and 'gcp') so no ignored-warning is needed for
 *     'aws' targets.
 *
 * @param result   - The compile result produced by the per-provider compilers.
 * @param resource - The original portable resource (may carry provider_overrides).
 * @param target   - The active target cloud provider.
 * @returns A new {@link PortableCompileResult} with overrides applied and
 *   findings appended.
 */
function applyOverrides(
  result: PortableCompileResult,
  resource: PortableResource,
  target: CloudProvider,
): PortableCompileResult {
  const overrides = (resource as { provider_overrides?: { azure?: Record<string, unknown>; gcp?: Record<string, unknown> } }).provider_overrides;
  if (!overrides) {
    return result;
  }

  const extraFindings: TranslationFinding[] = [];
  const sourceId = `portable:${resource.resource_type}:${resource.name}`;

  // Emit warnings for overrides targeting the wrong provider.
  const otherProviders = (['azure', 'gcp'] as const).filter((p) => p !== target);
  for (const other of otherProviders) {
    if (overrides[other] && Object.keys(overrides[other]!).length > 0) {
      extraFindings.push(
        createFinding(
          sourceId,
          'warning',
          'PORTABLE_OVERRIDE_IGNORED',
          `provider_overrides.${other} is ignored because the active target is '${target}'`,
        ),
      );
    }
  }

  // Apply overrides for the active target provider (azure or gcp only).
  const activeOverrides =
    (target === 'azure' || target === 'gcp') ? overrides[target] : undefined;

  if (!activeOverrides || Object.keys(activeOverrides).length === 0) {
    return {
      translated: result.translated,
      findings: [...result.findings, ...extraFindings],
    };
  }

  // Shallow-merge each override key into every translated resource's attributes.
  const mergedTranslated = result.translated.map((tr) => ({
    ...tr,
    attributes: { ...(tr.attributes as Record<string, unknown>), ...activeOverrides },
  }));

  // Emit one info finding per applied key.
  for (const key of Object.keys(activeOverrides)) {
    extraFindings.push(
      createFinding(
        sourceId,
        'info',
        'PORTABLE_OVERRIDE_APPLIED',
        `provider_overrides.${target}.${key} applied to translated resource(s)`,
      ),
    );
  }

  return {
    translated: mergedTranslated,
    findings: [...result.findings, ...extraFindings],
  };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Compiles a portable resource into native target-provider Terraform resources.
 *
 * Unsupported attribute combinations are returned as explicit findings with
 * severity 'warning' or 'info' — they are never silently dropped.
 *
 * @param resource - The portable resource descriptor (validated via Zod).
 * @param target   - The target cloud provider.
 * @returns         Translated native resources + diagnostic findings.
 *
 * @throws {Error} If the combination of resource_type and target is not
 *   supported (should not happen for valid inputs; included as a safety net).
 */
export function compilePortableResource(
  resource: PortableResource,
  target: CloudProvider,
): PortableCompileResult {
  switch (resource.resource_type) {
    case 'cloud_object_storage': {
      let r: PortableCompileResult;
      switch (target) {
        case 'aws':   r = compileObjectStorageAws(resource); break;
        case 'azure': r = compileObjectStorageAzure(resource); break;
        case 'gcp':   r = compileObjectStorageGcp(resource); break;
      }
      return applyOverrides(r!, resource, target);
    }

    case 'cloud_container_registry': {
      let r: PortableCompileResult;
      switch (target) {
        case 'aws':   r = compileContainerRegistryAws(resource); break;
        case 'azure': r = compileContainerRegistryAzure(resource); break;
        case 'gcp':   r = compileContainerRegistryGcp(resource); break;
      }
      return applyOverrides(r!, resource, target);
    }

    case 'cloud_cache_redis': {
      let r: PortableCompileResult;
      switch (target) {
        case 'aws':   r = compileRedisAws(resource); break;
        case 'azure': r = compileRedisAzure(resource); break;
        case 'gcp':   r = compileRedisGcp(resource); break;
      }
      return applyOverrides(r!, resource, target);
    }
  }

  // TypeScript exhaustiveness guard — should be unreachable at runtime.
  const exhaustive = resource as { resource_type: string };
  throw new Error(
    `compilePortableResource: unsupported resource_type '${exhaustive.resource_type}' for target '${target}'`,
  );
}
